<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- Generator: ControlBuild -->

<CB_COMPONENT NAME="axle_tri" COMMENTS="This module simulates the behaviour of a limited axle to which a translation speed is imparted." COMMENTS_PATTERN="This module simulates the behaviour of a limited axle to which a translation speed is imparted." PICTURE_PATH="" INSTANCE_NAMIMG_PATTERN="" COMPONENT_CLASS="" AP_DEC="" SIGNATURE="" GENERATION_DATE="" SAFE_MODE="False" BREAKPOINT="False" GEN_STATUS="good" COMPONENT_CLASS_UUID="" PLMId="">
	<MODEL_REQUIREMENTS>
		<FUNCTIONAL_TREE TYPE="c" />
	</MODEL_REQUIREMENTS>
	<externalSrcs />
</CB_COMPONENT>