/*2023-10-03T11:13:22-01:00*/

/********************************************************************
 * switch_3pos_2outputs.c
 * 
 * generated by: plcgen 3.1.391
 ********************************************************************/

#include "cb_comp.h"
#include "iec_1131.h"

#include "switch_3pos_2outputs.h"


/**************************** Variables *****************************/

CB_Index switch_3pos_2outputs__num = 0;
CB_Mem_Bool *switch_3pos_2outputs_leftVariable;
CB_Mem_Bool *switch_3pos_2outputs_rightVariable;
CB_Mem_Bool *switch_3pos_2outputs_leftPosition;
CB_Mem_Bool *switch_3pos_2outputs_middlePosition;
CB_Mem_Bool *switch_3pos_2outputs_rightPosition;

/**************************** Variables *****************************/

#define leftVariable (switch_3pos_2outputs_leftVariable->CB_current_value)
#define rightVariable (switch_3pos_2outputs_rightVariable->CB_current_value)
#define leftPosition (switch_3pos_2outputs_leftPosition->CB_current_value)
#define middlePosition (switch_3pos_2outputs_middlePosition->CB_current_value)
#define rightPosition (switch_3pos_2outputs_rightPosition->CB_current_value)


/************************ Components offsets ************************/


/********************* Initialization function **********************/

int _equipment_library__switch_3pos_2outputs_init(void)
{
	self.Bool+=3;


	return 0;
}


/************************ Behavior function *************************/

int equipment_library__switch_3pos_2outputs(void)
{
	if (exec_term_node(self_num)) {

		/*********************** Internals variables ************************/

		switch_3pos_2outputs_leftPosition = self.Bool+0;
		switch_3pos_2outputs_middlePosition = self.Bool+1;
		switch_3pos_2outputs_rightPosition = self.Bool+2;

		/********************* Pre-conditions execution *********************/

		/*no Pre-conditions*/

		/************************ Behavior execution ************************/

		{
			if (leftPosition) {
				leftVariable = 1;
				rightVariable = 0;
			}
			if (middlePosition) {
				leftVariable = 0;
				rightVariable = 0;
			}
			if (rightPosition) {
				leftVariable = 0;
				rightVariable = 1;
			}
			leftPosition = 0;
			middlePosition = 0;
			rightPosition = 0;
		}

		CB_post_bool(switch_3pos_2outputs_leftVariable);
		CB_post_bool(switch_3pos_2outputs_rightVariable);

		/******************** Post-conditions execution *********************/

		/*no Post-conditions*/
	}

	/*************************** self update ****************************/

	self.Bool += 3;

	return 0;
}

