/*2023-10-03T11:13:10-01:00*/

/********************************************************************
 * motor_1dir_2speed.c
 * 
 * generated by: plcgen 3.1.391
 ********************************************************************/

#include "cb_comp.h"
#include "iec_1131.h"

#include "motor_1dir_2speed.h"



/**************************** Variables *****************************/

CB_Index motor_1dir_2speed__num = 0;
CB_Mem_Bool *motor_1dir_2speed_voltage380;
CB_Mem_Bool *motor_1dir_2speed_cmdSupply;
CB_Mem_Bool *motor_1dir_2speed_sensorSupply;
CB_Mem_Bool *motor_1dir_2speed_highSpeed;
CB_Mem_Bool *motor_1dir_2speed_lowSpeed;
CB_Mem_Bool *motor_1dir_2speed_highSpeedFB;
CB_Mem_Bool *motor_1dir_2speed_lowSpeedFB;
CB_Mem_Bool *motor_1dir_2speed_thermal;
CB_Mem_Float *motor_1dir_2speed_speedVal;
CB_Mem_Float *motor_1dir_2speed_speedPercent;
CB_Mem_Float *motor_1dir_2speed_increment;
CB_Mem_Bool *motor_1dir_2speed_memoHighSpeed;
CB_Mem_Bool *motor_1dir_2speed_memoLowSpeed;
CB_Mem_Bool *motor_1dir_2speed_highSpeedState;
CB_Mem_Bool *motor_1dir_2speed_lowSpeedState;
CB_Mem_Float *motor_1dir_2speed_wantedSpeed;
CB_Mem_Float *motor_1dir_2speed_nominalTime;
CB_Mem_Bool *motor_1dir_2speed_thermalLogic;
CB_Mem_Bool *motor_1dir_2speed_highSpeedFBLogic;
CB_Mem_Bool *motor_1dir_2speed_lowSpeedFBLogic;
CB_Mem_Float *motor_1dir_2speed_nominalLowSpeed;
CB_Mem_Float *motor_1dir_2speed_nominalHighSpeed;
CB_Mem_Bool *motor_1dir_2speed_d_locking;
CB_Mem_Float *motor_1dir_2speed_v_d_locking;
CB_Mem_Bool *motor_1dir_2speed_d_electrical;
CB_Mem_Bool *motor_1dir_2speed_v_d_electrical;
CB_Mem_Bool *motor_1dir_2speed_d_highSpeedFB;
CB_Mem_Bool *motor_1dir_2speed_v_d_highSpeedFB;
CB_Mem_Bool *motor_1dir_2speed_d_lowSpeedFB;
CB_Mem_Bool *motor_1dir_2speed_v_d_lowSpeedFB;

/**************************** Variables *****************************/

#define voltage380 (motor_1dir_2speed_voltage380->CB_current_value)
#define cmdSupply (motor_1dir_2speed_cmdSupply->CB_current_value)
#define sensorSupply (motor_1dir_2speed_sensorSupply->CB_current_value)
#define highSpeed (motor_1dir_2speed_highSpeed->CB_current_value)
#define lowSpeed (motor_1dir_2speed_lowSpeed->CB_current_value)
#define highSpeedFB (motor_1dir_2speed_highSpeedFB->CB_current_value)
#define lowSpeedFB (motor_1dir_2speed_lowSpeedFB->CB_current_value)
#define thermal (motor_1dir_2speed_thermal->CB_current_value)
#define speedVal (motor_1dir_2speed_speedVal->CB_current_value)
#define speedPercent (motor_1dir_2speed_speedPercent->CB_current_value)
#define increment (motor_1dir_2speed_increment->CB_current_value)
#define memoHighSpeed (motor_1dir_2speed_memoHighSpeed->CB_current_value)
#define memoLowSpeed (motor_1dir_2speed_memoLowSpeed->CB_current_value)
#define highSpeedState (motor_1dir_2speed_highSpeedState->CB_current_value)
#define lowSpeedState (motor_1dir_2speed_lowSpeedState->CB_current_value)
#define wantedSpeed (motor_1dir_2speed_wantedSpeed->CB_current_value)
#define nominalTime (motor_1dir_2speed_nominalTime->CB_current_value)
#define thermalLogic (motor_1dir_2speed_thermalLogic->CB_current_value)
#define highSpeedFBLogic (motor_1dir_2speed_highSpeedFBLogic->CB_current_value)
#define lowSpeedFBLogic (motor_1dir_2speed_lowSpeedFBLogic->CB_current_value)
#define nominalLowSpeed (motor_1dir_2speed_nominalLowSpeed->CB_current_value)
#define nominalHighSpeed (motor_1dir_2speed_nominalHighSpeed->CB_current_value)
#define d_locking (motor_1dir_2speed_d_locking->CB_current_value)
#define v_d_locking (motor_1dir_2speed_v_d_locking->CB_current_value)
#define d_electrical (motor_1dir_2speed_d_electrical->CB_current_value)
#define v_d_electrical (motor_1dir_2speed_v_d_electrical->CB_current_value)
#define d_highSpeedFB (motor_1dir_2speed_d_highSpeedFB->CB_current_value)
#define v_d_highSpeedFB (motor_1dir_2speed_v_d_highSpeedFB->CB_current_value)
#define d_lowSpeedFB (motor_1dir_2speed_d_lowSpeedFB->CB_current_value)
#define v_d_lowSpeedFB (motor_1dir_2speed_v_d_lowSpeedFB->CB_current_value)


/************************ Components offsets ************************/


/********************* Initialization function **********************/

int _equipment_library__motor_1dir_2speed_init(void)
{
	(motor_1dir_2speed_voltage380)->CB_current_value = 1; /*voltage380*/
	(motor_1dir_2speed_cmdSupply)->CB_current_value = 1; /*cmdSupply*/
	(motor_1dir_2speed_sensorSupply)->CB_current_value = 1; /*sensorSupply*/
	(self.Float+2)->CB_current_value = 0.5; /*nominalTime*/
	(self.Bool+5)->CB_current_value = 1; /*highSpeedFBLogic*/
	(self.Bool+6)->CB_current_value = 1; /*lowSpeedFBLogic*/
	(self.Float+3)->CB_current_value = 2500.0; /*nominalLowSpeed*/
	(self.Float+4)->CB_current_value = 5000.0; /*nominalHighSpeed*/
	(self.Float+5)->CB_current_value = 0.5; /*v_d_locking*/
	self.Bool+=14;
	self.Float+=6;


	return 0;
}


/************************ Behavior function *************************/

int equipment_library__motor_1dir_2speed(void)
{
	if (exec_term_node(self_num)) {

		/*********************** Internals variables ************************/

		motor_1dir_2speed_increment = self.Float+0;
		motor_1dir_2speed_memoHighSpeed = self.Bool+0;
		motor_1dir_2speed_memoLowSpeed = self.Bool+1;
		motor_1dir_2speed_highSpeedState = self.Bool+2;
		motor_1dir_2speed_lowSpeedState = self.Bool+3;
		motor_1dir_2speed_wantedSpeed = self.Float+1;
		motor_1dir_2speed_nominalTime = self.Float+2;
		motor_1dir_2speed_thermalLogic = self.Bool+4;
		motor_1dir_2speed_highSpeedFBLogic = self.Bool+5;
		motor_1dir_2speed_lowSpeedFBLogic = self.Bool+6;
		motor_1dir_2speed_nominalLowSpeed = self.Float+3;
		motor_1dir_2speed_nominalHighSpeed = self.Float+4;
		motor_1dir_2speed_d_locking = self.Bool+7;
		motor_1dir_2speed_v_d_locking = self.Float+5;
		motor_1dir_2speed_d_electrical = self.Bool+8;
		motor_1dir_2speed_v_d_electrical = self.Bool+9;
		motor_1dir_2speed_d_highSpeedFB = self.Bool+10;
		motor_1dir_2speed_v_d_highSpeedFB = self.Bool+11;
		motor_1dir_2speed_d_lowSpeedFB = self.Bool+12;
		motor_1dir_2speed_v_d_lowSpeedFB = self.Bool+13;

		/********************* Pre-conditions execution *********************/

		/*no Pre-conditions*/

		/************************ Behavior execution ************************/

		{
			/* ----------------------------------------------------------------	*/
			/* Type : Model of Operative Behaviour					*/
			/* Category :  Associations - motors					*/
			/* Author : Dassault Systemes						*/
			/* Update date : June 2018							*/
			/* ----------------------------------------------------------------	*/
			/* This module simulates a motor with 1 direction and 2 speeds	*/
			/* and its electrical control logic.					*/
			/* ----------------------------------------------------------------	*/


			/* ----------------------------------------------------------------	*/
			/* Management of orders from Control Part					*/
			/*	if there is no power supply for command 				*/
			/*     the contactors don't understand the control order		*/
			/*	The contactors are not mechanically bound.			*/
			/* ----------------------------------------------------------------	*/
			if (!memoHighSpeed && lowSpeed && cmdSupply) memoLowSpeed = 1;
			if (!lowSpeed || !cmdSupply || d_electrical) memoLowSpeed = 0;
			if (highSpeed && !memoLowSpeed && cmdSupply) memoHighSpeed = 1;
			if (!highSpeed || !cmdSupply || d_electrical) memoHighSpeed = 0;

			/* ----------------------------------------------------------------	*/
			/* Calculation of the on-state of contactor				*/
			/* ----------------------------------------------------------------	*/
			highSpeedState=memoHighSpeed & voltage380;
			lowSpeedState=memoLowSpeed & voltage380;

			/* ----------------------------------------------------------------	*/
			/* Management of the speed ramp						*/
			/* ----------------------------------------------------------------	*/
			if (d_locking)  speedVal = v_d_locking;
			else {
				/* Compute the wanted speed according to the state of contactors	*/
				wantedSpeed = 0.0;
				if (highSpeedState) {
					wantedSpeed = nominalHighSpeed;
					if (nominalTime > 0.0)
						increment = (nominalHighSpeed / nominalTime) * (CLOCK_PERIOD/1000000.0);
				}
				else if (lowSpeedState) {
					wantedSpeed = nominalLowSpeed;
					if (nominalTime > 0.0)
						increment = (nominalLowSpeed / nominalTime) * (CLOCK_PERIOD/1000000.0);
				}

				/* Compute speed ramp	*/
				if ( speedVal < wantedSpeed ) {
					speedVal += increment;
					if ( speedVal > wantedSpeed ) speedVal = wantedSpeed;
				}
				if ( speedVal > wantedSpeed ) {
					speedVal -= increment;
					if (speedVal < wantedSpeed) speedVal = wantedSpeed;
				}
			}


			/* ----------------------------------------------------------------	*/
			/* Compute the percentage between the current and nominal speed	*/
			/* ----------------------------------------------------------------	*/
			if (nominalHighSpeed != 0.0)
				speedPercent = ((speedVal/nominalHighSpeed)*100);

			/* ----------------------------------------------------------------	*/
			/* Management of the thermal feedback					*/
			/* ----------------------------------------------------------------	*/
			if (d_electrical) thermal=v_d_electrical;
			else
				thermal= ! thermalLogic && sensorSupply;


			/* ----------------------------------------------------------------	*/
			/* Management of feedback to Control Part					*/
			/*     if a fault is required, the contactor feed-back 		*/
			/*		 takes a preset state.					*/
			/*	if there is no power supply for sensors 				*/
			/*         contactor feed-back returns nothing				*/
			/*     else contactor feed-back returns the contactor state combined	*/
			/*	    with wiring logic.						*/
			/* ----------------------------------------------------------------	*/
			if (d_highSpeedFB) highSpeedFB = v_d_highSpeedFB;
			else 	
				highSpeedFB = (memoHighSpeed ^ ! highSpeedFBLogic) && sensorSupply;


			if (d_lowSpeedFB) lowSpeedFB = v_d_lowSpeedFB;
			else	
				lowSpeedFB = (memoLowSpeed ^ ! lowSpeedFBLogic) && sensorSupply;


		}

		CB_post_bool(motor_1dir_2speed_highSpeedFB);
		CB_post_bool(motor_1dir_2speed_lowSpeedFB);
		CB_post_bool(motor_1dir_2speed_thermal);
		CB_post_float(motor_1dir_2speed_speedVal);
		CB_post_float(motor_1dir_2speed_speedPercent);

		/******************** Post-conditions execution *********************/

		/*no Post-conditions*/
	}

	/*************************** self update ****************************/

	self.Bool += 14;
	self.Float += 6;

	return 0;
}

