/*2023-10-03T11:12:45-01:00*/

/********************************************************************
 * cb_ctud.c
 * 
 * generated by: plcgen 3.1.391
 ********************************************************************/

#include "cb_comp.h"
#include "iec_1131.h"

#include "cb_ctud.h"



/**************************** Variables *****************************/

CB_Index cb_ctud__num = 0;
CB_Mem_Bool *cb_ctud_CU;
CB_Mem_Bool *cb_ctud_CD;
CB_Mem_Bool *cb_ctud_R;
CB_Mem_Bool *cb_ctud_LOAD;
CB_Mem_Int *cb_ctud_PV;
CB_Mem_Bool *cb_ctud_QU;
CB_Mem_Bool *cb_ctud_QD;
CB_Mem_Int *cb_ctud_CV;

/**************************** Variables *****************************/

#define CU (cb_ctud_CU->CB_current_value)
#define CD (cb_ctud_CD->CB_current_value)
#define R (cb_ctud_R->CB_current_value)
#define LOAD (cb_ctud_LOAD->CB_current_value)
#define PV (*((short *)&(cb_ctud_PV->CB_current_value) + ALIGN_OFFSET_SHORT))
#define QU (cb_ctud_QU->CB_current_value)
#define QD (cb_ctud_QD->CB_current_value)
#define CV (*((short *)&(cb_ctud_CV->CB_current_value) + ALIGN_OFFSET_SHORT))


/************************ Components offsets ************************/


/********************* Initialization function **********************/

int _timers_counters__cb_ctud_init(void)
{


	return 0;
}


/************************ Behavior function *************************/

int timers_counters__cb_ctud(void)
{
	if (exec_term_node(self_num)) {

		/*********************** Internals variables ************************/


		/********************* Pre-conditions execution *********************/

		/*no Pre-conditions*/

		/************************ Behavior execution ************************/

		{
			/* -----------------------------------------------------------------	*/
			/* Type : BFU									*/
			/* Copyright : Geensoft							*/
			/* Version : 1.1 23/03/2010							*/
			/* -----------------------------------------------------------------	*/
			/* This is a Up-counter / down-counter	(CTUD)				*/
			/* -------------------------------------------------------------	*/
			if(R) { CV = 0; }
			else {
				if (LOAD) {CV = PV;}
				else {
					if (! (CU && CD)) {
						if(CU && (CV < 32767)) {CV = CV + 1;}
						else {
							if(CD && (CV > -32768)) {CV = CV - 1;}
						}
					}
				}
			}
			QU = (CV >= PV);
			QD = (CV <= 0);
		}

		CB_post_bool(cb_ctud_QU);
		CB_post_bool(cb_ctud_QD);
		CB_post_int(cb_ctud_CV);

		/******************** Post-conditions execution *********************/

		/*no Post-conditions*/
	}

	/*************************** self update ****************************/


	return 0;
}

