/*2023-10-03T11:13:16-01:00*/

/********************************************************************
 * single_acting_rod.c
 * 
 * generated by: plcgen 3.1.391
 ********************************************************************/

#include "cb_comp.h"
#include "iec_1131.h"

#include "single_acting_rod.h"



/**************************** Variables *****************************/

CB_Index single_acting_rod__num = 0;
CB_Mem_Bool *single_acting_rod_pipeWork;
CB_Mem_Float *single_acting_rod_rodPosition;
CB_Mem_Float *single_acting_rod_rodPercent;
CB_Mem_Float *single_acting_rod_increment;
CB_Mem_Float *single_acting_rod_length;
CB_Mem_Float *single_acting_rod_timeOutput;
CB_Mem_Bool *single_acting_rod_d_locking;
CB_Mem_Float *single_acting_rod_v_d_locking;

/**************************** Variables *****************************/

#define pipeWork (single_acting_rod_pipeWork->CB_current_value)
#define rodPosition (single_acting_rod_rodPosition->CB_current_value)
#define rodPercent (single_acting_rod_rodPercent->CB_current_value)
#define increment (single_acting_rod_increment->CB_current_value)
#define length (single_acting_rod_length->CB_current_value)
#define timeOutput (single_acting_rod_timeOutput->CB_current_value)
#define d_locking (single_acting_rod_d_locking->CB_current_value)
#define v_d_locking (single_acting_rod_v_d_locking->CB_current_value)


/************************ Components offsets ************************/


/********************* Initialization function **********************/

int _equipment_library__single_acting_rod_init(void)
{
	(self.Float+1)->CB_current_value = 1000.0; /*length*/
	(self.Float+2)->CB_current_value = 10.0; /*timeOutput*/
	(self.Float+3)->CB_current_value = 10.0; /*v_d_locking*/
	self.Bool+=1;
	self.Float+=4;


	return 0;
}


/************************ Behavior function *************************/

int equipment_library__single_acting_rod(void)
{
	if (exec_term_node(self_num)) {

		/*********************** Internals variables ************************/

		single_acting_rod_increment = self.Float+0;
		single_acting_rod_length = self.Float+1;
		single_acting_rod_timeOutput = self.Float+2;
		single_acting_rod_d_locking = self.Bool+0;
		single_acting_rod_v_d_locking = self.Float+3;

		/********************* Pre-conditions execution *********************/

		/*no Pre-conditions*/

		/************************ Behavior execution ************************/

		{
			/* ----------------------------------------------------------------	*/
			/* Type : Model of Operative Behaviour					*/
			/* Category :  Actuators							*/
			/* Author : Dassault Systemes						*/
			/* Update date : June 2018							*/
			/* ----------------------------------------------------------------	*/
			/* This module simulates the behaviour of a single-acting cylinder	*/
			/* rod according to the working state of pipe.				*/
			/* ----------------------------------------------------------------	*/

			if (d_locking) increment=0;
			else {
				increment=(length/timeOutput)*(CLOCK_PERIOD/1000000);
				if (pipeWork) {
					if ( rodPosition < length ) (rodPosition)+= increment;
					if ( rodPosition > length ) rodPosition = length;
				}
				else {
					if ( rodPosition > 0 ) (rodPosition)-= increment;
					if ( rodPosition < 0 ) rodPosition = 0;
				}
			}

			/* ----------------------------------------------------------------	*/
			/* Compute the percentage of cylinder rod's length			*/
			/* ----------------------------------------------------------------	*/
			if (length > 0.0)
				rodPercent = ((rodPosition/length)*100);

		}

		CB_post_float(single_acting_rod_rodPosition);
		CB_post_float(single_acting_rod_rodPercent);

		/******************** Post-conditions execution *********************/

		/*no Post-conditions*/
	}

	/*************************** self update ****************************/

	self.Bool += 1;
	self.Float += 4;

	return 0;
}

