/*2023-10-03T11:13:48-01:00*/

/********************************************************************
 * controller.h
 * 
 * generated by: plcgen 3.1.391
 ********************************************************************/

#ifndef _TNI_CLOCK__CONTROLLER_H
#define _TNI_CLOCK__CONTROLLER_H


/********************** Variable declarations ***********************/

extern CB_Index controller__num;
extern CB_Mem_Int *controller_pressure;
extern CB_Mem_Bool *controller_tick;
extern CB_Mem_Bool *controller_B1;
extern CB_Mem_Bool *controller_B2;
extern CB_Mem_Bool *controller_B3;
extern CB_Mem_Bool *controller_B4;
extern CB_Mem_Int *controller_displayValue;
extern CB_Mem_Bool *controller_stepMotorSecond;
extern CB_Mem_Bool *controller_stepMotorMinute;
extern CB_Mem_Bool *controller_stepMotorHour;
extern CB_Mem_Bool *controller_switchOnLight;

/********************** Function declarations ***********************/

extern int _tni_clock__controller_init(void);
extern int tni_clock__controller(void);

#endif /*_TNI_CLOCK__CONTROLLER_H*/
