/*2023-10-03T11:13:42-01:00*/

/********************************************************************
 * pumping.h
 * 
 * generated by: plcgen 3.1.391
 ********************************************************************/

#ifndef _BOTTLING_LINE__PUMPING_H
#define _BOTTLING_LINE__PUMPING_H


/********************** Variable declarations ***********************/

extern CB_Index pumping__num;
extern CB_Mem_Bool *pumping_fillingValve;
extern CB_Mem_Bool *pumping_emptyingValve;
extern CB_Mem_Bool *pumping_extractionPump;
extern CB_Mem_Bool *pumping_acknowledgePB;
extern CB_Mem_Bool *pumping_autoMode;
extern CB_Mem_Bool *pumping_manualMode;
extern CB_Mem_Bool *pumping_lowLevel;
extern CB_Mem_Bool *pumping_highLevel;
extern CB_Mem_Float *pumping_pumpingFlow;
extern CB_Mem_Float *pumping_level;

/********************** Function declarations ***********************/

extern int _bottling_line__pumping_init(void);
extern int bottling_line__pumping(void);

#endif /*_BOTTLING_LINE__PUMPING_H*/
