/*2023-10-03T11:13:42-01:00*/

/********************************************************************
 * pumping.c
 * 
 * generated by: plcgen 3.1.391
 ********************************************************************/

#include "cb_comp.h"
#include "iec_1131.h"

#include "pumping.h"
#include "io_library/functional/io_single_acting_valve/io_single_acting_valve.h"
#include "equipment_library/functional/tank/tank.h"
#include "io_library/functional/io_on_off_pump/io_on_off_pump.h"
#include "equipment_library/functional/bounded_scale/bounded_scale.h"
#include "equipment_library/functional/threshold_sensor/threshold_sensor.h"
#include "equipment_library/functional/analog_sensor/analog_sensor.h"


/**************************** Variables *****************************/

CB_Index pumping__num = 0;
CB_Mem_Bool *pumping_fillingValve;
CB_Mem_Bool *pumping_emptyingValve;
CB_Mem_Bool *pumping_extractionPump;
CB_Mem_Bool *pumping_acknowledgePB;
CB_Mem_Bool *pumping_autoMode;
CB_Mem_Bool *pumping_manualMode;
CB_Mem_Bool *pumping_lowLevel;
CB_Mem_Bool *pumping_highLevel;
CB_Mem_Float *pumping_pumpingFlow;
CB_Mem_Float *pumping_level;

/**************************** Variables *****************************/



/************************ Components offsets ************************/

static CB_Offset bottling_line__pumping_offset_filling;
static CB_Offset bottling_line__pumping_offset_emptying;
static CB_Offset bottling_line__pumping_offset_tank;
static CB_Offset bottling_line__pumping_offset_extraction;
static CB_Offset bottling_line__pumping_offset_levelScale;
static CB_Offset bottling_line__pumping_offset_highLevel;
static CB_Offset bottling_line__pumping_offset_lowLevel;
static CB_Offset bottling_line__pumping_offset_levelMeasurement;
static CB_Offset bottling_line__pumping_offset__end = {0, 0, 0, 0};


/********************* Initialization function **********************/

int _bottling_line__pumping_init(void)
{
	CB_Object __start = self;
	self.Bool+=10;
	self.Int+=2;
	self.Float+=10;

	/*initialize child filling (io_library.io_single_acting_valve):*/
	self_num++;
	bottling_line__pumping_offset_filling.Bool = self.Bool - __start.Bool;
	bottling_line__pumping_offset_filling.Int = self.Int - __start.Int;
	bottling_line__pumping_offset_filling.Float = self.Float - __start.Float;
	bottling_line__pumping_offset_filling.Char = self.Char - __start.Char;
	io_single_acting_valve_acknowledgePB = pumping_acknowledgePB;
	io_single_acting_valve_autoMode = pumping_autoMode;
	io_single_acting_valve_manualMode = pumping_manualMode;
	io_single_acting_valve_autoOpenCmd = pumping_fillingValve;
	io_single_acting_valve_inputFlow = __start.Float+5; /*pumping__cn_5*/
	io_single_acting_valve_openedSensor = __start.Bool+9; /*pumping__cn_6*/
	io_single_acting_valve_closedSensor = __start.Bool+8; /*pumping__cn_7*/
	io_single_acting_valve_generalFault = __start.Bool+7; /*pumping__cn_8*/
	io_single_acting_valve_outputFlow = __start.Float+7; /*pumping__cn_3*/
	io_single_acting_valve_percentOpening = __start.Float+4; /*pumping__cn_9*/
	_io_library__io_single_acting_valve_init();

	/*initialize child emptying (io_library.io_single_acting_valve):*/
	self_num++;
	bottling_line__pumping_offset_emptying.Bool = self.Bool - __start.Bool;
	bottling_line__pumping_offset_emptying.Int = self.Int - __start.Int;
	bottling_line__pumping_offset_emptying.Float = self.Float - __start.Float;
	bottling_line__pumping_offset_emptying.Char = self.Char - __start.Char;
	io_single_acting_valve_acknowledgePB = pumping_acknowledgePB;
	io_single_acting_valve_autoMode = pumping_autoMode;
	io_single_acting_valve_manualMode = pumping_manualMode;
	io_single_acting_valve_autoOpenCmd = pumping_emptyingValve;
	io_single_acting_valve_inputFlow = __start.Float+6; /*pumping__cn_4*/
	io_single_acting_valve_openedSensor = __start.Bool+6; /*pumping__cn_10*/
	io_single_acting_valve_closedSensor = __start.Bool+5; /*pumping__cn_11*/
	io_single_acting_valve_generalFault = __start.Bool+4; /*pumping__cn_12*/
	io_single_acting_valve_outputFlow = pumping_pumpingFlow;
	io_single_acting_valve_percentOpening = __start.Float+3; /*pumping__cn_13*/
	_io_library__io_single_acting_valve_init();

	/*initialize child tank (equipment_library.tank):*/
	self_num++;
	bottling_line__pumping_offset_tank.Bool = self.Bool - __start.Bool;
	bottling_line__pumping_offset_tank.Int = self.Int - __start.Int;
	bottling_line__pumping_offset_tank.Float = self.Float - __start.Float;
	bottling_line__pumping_offset_tank.Char = self.Char - __start.Char;
	tank_inletFlow = __start.Float+7; /*pumping__cn_3*/
	tank_outletFlow = pumping_pumpingFlow;
	tank_tankLevel = __start.Float+8; /*pumping__cn_2*/
	_equipment_library__tank_init();

	/*initialize child extraction (io_library.io_on_off_pump):*/
	self_num++;
	bottling_line__pumping_offset_extraction.Bool = self.Bool - __start.Bool;
	bottling_line__pumping_offset_extraction.Int = self.Int - __start.Int;
	bottling_line__pumping_offset_extraction.Float = self.Float - __start.Float;
	bottling_line__pumping_offset_extraction.Char = self.Char - __start.Char;
	io_on_off_pump_acknowledgePB = pumping_acknowledgePB;
	io_on_off_pump_autoMode = pumping_autoMode;
	io_on_off_pump_manualMode = pumping_manualMode;
	io_on_off_pump_autoCmd = pumping_extractionPump;
	io_on_off_pump_inputFlow = __start.Float+8; /*pumping__cn_2*/
	io_on_off_pump_generalFault = __start.Bool+3; /*pumping__cn_14*/
	io_on_off_pump_speedVal = __start.Float+2; /*pumping__cn_15*/
	io_on_off_pump_outputFlow = __start.Float+6; /*pumping__cn_4*/
	_io_library__io_on_off_pump_init();

	/*initialize child levelScale (equipment_library.bounded_scale):*/
	self_num++;
	bottling_line__pumping_offset_levelScale.Bool = self.Bool - __start.Bool;
	bottling_line__pumping_offset_levelScale.Int = self.Int - __start.Int;
	bottling_line__pumping_offset_levelScale.Float = self.Float - __start.Float;
	bottling_line__pumping_offset_levelScale.Char = self.Char - __start.Char;
	bounded_scale_inputValue = __start.Float+8; /*pumping__cn_2*/
	bounded_scale_realValue = __start.Float+9; /*pumping__cn_1*/
	bounded_scale_dintValue = __start.Int+1; /*pumping__cn_16*/
	bounded_scale_intValue = __start.Int+0; /*pumping__cn_17*/
	_equipment_library__bounded_scale_init();

	/*initialize child highLevel (equipment_library.threshold_sensor):*/
	self_num++;
	bottling_line__pumping_offset_highLevel.Bool = self.Bool - __start.Bool;
	bottling_line__pumping_offset_highLevel.Int = self.Int - __start.Int;
	bottling_line__pumping_offset_highLevel.Float = self.Float - __start.Float;
	bottling_line__pumping_offset_highLevel.Char = self.Char - __start.Char;
	threshold_sensor_level = __start.Float+8; /*pumping__cn_2*/
	threshold_sensor_sensorSupply = __start.Bool+2; /*pumping__cn_18*/
	threshold_sensor_thresholdSensor = pumping_highLevel;
	_equipment_library__threshold_sensor_init();

	/*initialize child lowLevel (equipment_library.threshold_sensor):*/
	self_num++;
	bottling_line__pumping_offset_lowLevel.Bool = self.Bool - __start.Bool;
	bottling_line__pumping_offset_lowLevel.Int = self.Int - __start.Int;
	bottling_line__pumping_offset_lowLevel.Float = self.Float - __start.Float;
	bottling_line__pumping_offset_lowLevel.Char = self.Char - __start.Char;
	threshold_sensor_level = __start.Float+8; /*pumping__cn_2*/
	threshold_sensor_sensorSupply = __start.Bool+1; /*pumping__cn_19*/
	threshold_sensor_thresholdSensor = pumping_lowLevel;
	_equipment_library__threshold_sensor_init();

	/*initialize child levelMeasurement (equipment_library.analog_sensor):*/
	self_num++;
	bottling_line__pumping_offset_levelMeasurement.Bool = self.Bool - __start.Bool;
	bottling_line__pumping_offset_levelMeasurement.Int = self.Int - __start.Int;
	bottling_line__pumping_offset_levelMeasurement.Float = self.Float - __start.Float;
	bottling_line__pumping_offset_levelMeasurement.Char = self.Char - __start.Char;
	analog_sensor_measure = __start.Float+9; /*pumping__cn_1*/
	analog_sensor_sensorSupply = __start.Bool+0; /*pumping__cn_20*/
	analog_sensor_realValue = pumping_level;
	analog_sensor_intValue = __start.Float+1; /*pumping__cn_21*/
	analog_sensor_dintValue = __start.Float+0; /*pumping__cn_22*/
	_equipment_library__analog_sensor_init();

	bottling_line__pumping_offset__end.Bool = self.Bool - __start.Bool;
	bottling_line__pumping_offset__end.Int = self.Int - __start.Int;
	bottling_line__pumping_offset__end.Float = self.Float - __start.Float;
	bottling_line__pumping_offset__end.Char = self.Char - __start.Char;

	return 0;
}


/************************ Behavior function *************************/

int bottling_line__pumping(void)
{
	CB_Object __start = self;
	int __ret;
	if (exec_mac_node(self_num)) {

		/*********************** Internals variables ************************/

																																												
		/********************* Pre-conditions execution *********************/

		/*no Pre-conditions*/

		/************************ Behavior execution ************************/

		{
			self.Bool = __start.Bool + bottling_line__pumping_offset_filling.Bool;
			self.Int = __start.Int + bottling_line__pumping_offset_filling.Int;
			self.Float = __start.Float + bottling_line__pumping_offset_filling.Float;
			self.Char = __start.Char + bottling_line__pumping_offset_filling.Char;

			/************************ filling execution *************************/

			self_num++;
			if (io_single_acting_valve__num != self_num) {
				io_single_acting_valve__num = self_num;
				io_single_acting_valve_acknowledgePB = pumping_acknowledgePB;
				io_single_acting_valve_autoMode = pumping_autoMode;
				io_single_acting_valve_manualMode = pumping_manualMode;
				io_single_acting_valve_autoOpenCmd = pumping_fillingValve;
				io_single_acting_valve_inputFlow = __start.Float+5; /*pumping__cn_5*/
				io_single_acting_valve_openedSensor = __start.Bool+9; /*pumping__cn_6*/
				io_single_acting_valve_closedSensor = __start.Bool+8; /*pumping__cn_7*/
				io_single_acting_valve_generalFault = __start.Bool+7; /*pumping__cn_8*/
				io_single_acting_valve_outputFlow = __start.Float+7; /*pumping__cn_3*/
				io_single_acting_valve_percentOpening = __start.Float+4; /*pumping__cn_9*/
			}
			__ret = io_library__io_single_acting_valve();
			if (__ret != 0) {
				return __ret; /*child execution failure*/
			}

			/************************ emptying execution ************************/

			self_num++;
			if (io_single_acting_valve__num != self_num) {
				io_single_acting_valve__num = self_num;
				io_single_acting_valve_acknowledgePB = pumping_acknowledgePB;
				io_single_acting_valve_autoMode = pumping_autoMode;
				io_single_acting_valve_manualMode = pumping_manualMode;
				io_single_acting_valve_autoOpenCmd = pumping_emptyingValve;
				io_single_acting_valve_inputFlow = __start.Float+6; /*pumping__cn_4*/
				io_single_acting_valve_openedSensor = __start.Bool+6; /*pumping__cn_10*/
				io_single_acting_valve_closedSensor = __start.Bool+5; /*pumping__cn_11*/
				io_single_acting_valve_generalFault = __start.Bool+4; /*pumping__cn_12*/
				io_single_acting_valve_outputFlow = pumping_pumpingFlow;
				io_single_acting_valve_percentOpening = __start.Float+3; /*pumping__cn_13*/
			}
			__ret = io_library__io_single_acting_valve();
			if (__ret != 0) {
				return __ret; /*child execution failure*/
			}

			/************************** tank execution **************************/

			self_num++;
			if (tank__num != self_num) {
				tank__num = self_num;
				tank_inletFlow = __start.Float+7; /*pumping__cn_3*/
				tank_outletFlow = pumping_pumpingFlow;
				tank_tankLevel = __start.Float+8; /*pumping__cn_2*/
			}
			__ret = equipment_library__tank();
			if (__ret != 0) {
				return __ret; /*child execution failure*/
			}

			/*********************** extraction execution ***********************/

			self_num++;
			if (io_on_off_pump__num != self_num) {
				io_on_off_pump__num = self_num;
				io_on_off_pump_acknowledgePB = pumping_acknowledgePB;
				io_on_off_pump_autoMode = pumping_autoMode;
				io_on_off_pump_manualMode = pumping_manualMode;
				io_on_off_pump_autoCmd = pumping_extractionPump;
				io_on_off_pump_inputFlow = __start.Float+8; /*pumping__cn_2*/
				io_on_off_pump_generalFault = __start.Bool+3; /*pumping__cn_14*/
				io_on_off_pump_speedVal = __start.Float+2; /*pumping__cn_15*/
				io_on_off_pump_outputFlow = __start.Float+6; /*pumping__cn_4*/
			}
			__ret = io_library__io_on_off_pump();
			if (__ret != 0) {
				return __ret; /*child execution failure*/
			}

			/*********************** levelScale execution ***********************/

			self_num++;
			if (bounded_scale__num != self_num) {
				bounded_scale__num = self_num;
				bounded_scale_inputValue = __start.Float+8; /*pumping__cn_2*/
				bounded_scale_realValue = __start.Float+9; /*pumping__cn_1*/
				bounded_scale_dintValue = __start.Int+1; /*pumping__cn_16*/
				bounded_scale_intValue = __start.Int+0; /*pumping__cn_17*/
			}
			__ret = equipment_library__bounded_scale();
			if (__ret != 0) {
				return __ret; /*child execution failure*/
			}

			/*********************** highLevel execution ************************/

			self_num++;
			if (threshold_sensor__num != self_num) {
				threshold_sensor__num = self_num;
				threshold_sensor_level = __start.Float+8; /*pumping__cn_2*/
				threshold_sensor_sensorSupply = __start.Bool+2; /*pumping__cn_18*/
				threshold_sensor_thresholdSensor = pumping_highLevel;
			}
			__ret = equipment_library__threshold_sensor();
			if (__ret != 0) {
				return __ret; /*child execution failure*/
			}

			/************************ lowLevel execution ************************/

			self_num++;
			if (threshold_sensor__num != self_num) {
				threshold_sensor__num = self_num;
				threshold_sensor_level = __start.Float+8; /*pumping__cn_2*/
				threshold_sensor_sensorSupply = __start.Bool+1; /*pumping__cn_19*/
				threshold_sensor_thresholdSensor = pumping_lowLevel;
			}
			__ret = equipment_library__threshold_sensor();
			if (__ret != 0) {
				return __ret; /*child execution failure*/
			}

			/******************** levelMeasurement execution ********************/

			self_num++;
			if (analog_sensor__num != self_num) {
				analog_sensor__num = self_num;
				analog_sensor_measure = __start.Float+9; /*pumping__cn_1*/
				analog_sensor_sensorSupply = __start.Bool+0; /*pumping__cn_20*/
				analog_sensor_realValue = pumping_level;
				analog_sensor_intValue = __start.Float+1; /*pumping__cn_21*/
				analog_sensor_dintValue = __start.Float+0; /*pumping__cn_22*/
			}
			__ret = equipment_library__analog_sensor();
			if (__ret != 0) {
				return __ret; /*child execution failure*/
			}

		}


		/******************** Post-conditions execution *********************/

		/*no Post-conditions*/
	}

	/*************************** self update ****************************/

	self.Bool = __start.Bool + bottling_line__pumping_offset__end.Bool;
	self.Int = __start.Int + bottling_line__pumping_offset__end.Int;
	self.Float = __start.Float + bottling_line__pumping_offset__end.Float;
	self.Char = __start.Char + bottling_line__pumping_offset__end.Char;

	return 0;
}

