/********************************************************************
 * _init.h
 * 
 * generated by: plcgen 3.1.391
 ********************************************************************/

#define mx_use_equipment_library__momentary_button
#define mx_use_equipment_library__switch_2pos_2outputs
#define mx_use_equipment_library__maintained_button
#define mx_use_batch__recipe
#define mx_use_batch__mode
#define mx_use_batch__management
#define mx_use_batch__manufacturing
#define mx_use_batch__flour
#define mx_use_io_library__io_on_off_valve
#define mx_use_equipment_library__switch_3pos_2outputs
#define mx_use_cmd_equipment_library__cmd_on_off_valve
#define mx_use_timers_counters__cb_ton
#define mx_use_equipment_library__on_off_valve
#define mx_use_equipment_library__tank
#define mx_use_equipment_library__flow_compute
#define mx_use_equipment_library__analog_sensor
#define mx_use_batch__flour_weighing
#define mx_use_equipment_library__bounded_scale
#define mx_use_batch__syrup
#define mx_use_batch__syrup_weighing
#define mx_use_batch__add_syrup
#define mx_use_batch__mixture
#define mx_use_batch__kneading
#define mx_use_io_library__io_agitator_1speed
#define mx_use_equipment_library__agitator_1speed
#define mx_use_cmd_equipment_library__cmd_agitator_1speed
#define mx_use_batch__batch


