/*2023-10-03T11:13:41-01:00*/

/********************************************************************
 * bottling_line.h
 * 
 * generated by: plcgen 3.1.391
 ********************************************************************/

#ifndef _BOTTLING_LINE__BOTTLING_LINE_H
#define _BOTTLING_LINE__BOTTLING_LINE_H


/********************** Variable declarations ***********************/

extern CB_Index bottling_line__num;

/********************** Function declarations ***********************/

extern int _bottling_line__bottling_line_init(void);
extern int bottling_line__bottling_line(void);

#endif /*_BOTTLING_LINE__BOTTLING_LINE_H*/
