/*2023-10-03T11:13:29-01:00*/

/********************************************************************
 * logical_and.c
 * 
 * generated by: plcgen 3.1.391
 ********************************************************************/

#include "cb_comp.h"
#include "iec_1131.h"

#include "logical_and.h"



/**************************** Variables *****************************/

CB_Index logical_and__num = 0;
CB_Mem_Bool *logical_and_inputBit1;
CB_Mem_Bool *logical_and_inputBit2;
CB_Mem_Bool *logical_and_ouputBit;
CB_Mem_Bool *logical_and_input1Logic;
CB_Mem_Bool *logical_and_input2Logic;
CB_Mem_Bool *logical_and_outputLogic;
CB_Mem_Bool *logical_and_d_output;
CB_Mem_Bool *logical_and_v_d_output;

/**************************** Variables *****************************/

#define inputBit1 (logical_and_inputBit1->CB_current_value)
#define inputBit2 (logical_and_inputBit2->CB_current_value)
#define ouputBit (logical_and_ouputBit->CB_current_value)
#define input1Logic (logical_and_input1Logic->CB_current_value)
#define input2Logic (logical_and_input2Logic->CB_current_value)
#define outputLogic (logical_and_outputLogic->CB_current_value)
#define d_output (logical_and_d_output->CB_current_value)
#define v_d_output (logical_and_v_d_output->CB_current_value)


/************************ Components offsets ************************/


/********************* Initialization function **********************/

int _equipment_library__logical_and_init(void)
{
	(self.Bool+0)->CB_current_value = 1; /*input1Logic*/
	(self.Bool+1)->CB_current_value = 1; /*input2Logic*/
	(self.Bool+2)->CB_current_value = 1; /*outputLogic*/
	(self.Bool+4)->CB_current_value = 1; /*v_d_output*/
	self.Bool+=5;


	return 0;
}


/************************ Behavior function *************************/

int equipment_library__logical_and(void)
{
	if (exec_term_node(self_num)) {

		/*********************** Internals variables ************************/

		logical_and_input1Logic = self.Bool+0;
		logical_and_input2Logic = self.Bool+1;
		logical_and_outputLogic = self.Bool+2;
		logical_and_d_output = self.Bool+3;
		logical_and_v_d_output = self.Bool+4;

		/********************* Pre-conditions execution *********************/

		/*no Pre-conditions*/

		/************************ Behavior execution ************************/

		{
			/* ----------------------------------------------------------------	*/
			/* Type : Model of Operative Behaviour					*/
			/* Category :  Toolbox							*/
			/* Author : Dassault Systemes						*/
			/* Update date : June 2018						*/
			/* ----------------------------------------------------------------	*/
			/* This module makes a "logical AND" operation between two inputs.	*/
			/* Result is a boolean.							*/
			/* The output can be preset	by the user					*/
			/* ----------------------------------------------------------------	*/

			if (d_output) ouputBit = v_d_output;
			else
				ouputBit = ((inputBit1 ^ ! input1Logic) & (inputBit2 ^ ! input2Logic)) ^ ! outputLogic;
		}

		CB_post_bool(logical_and_ouputBit);

		/******************** Post-conditions execution *********************/

		/*no Post-conditions*/
	}

	/*************************** self update ****************************/

	self.Bool += 5;

	return 0;
}

