/*2023-10-03T11:13:46-01:00*/

/********************************************************************
 * mdescent.h
 * 
 * generated by: plcgen 3.1.391
 ********************************************************************/

#ifndef _DRILL__MDESCENT_H
#define _DRILL__MDESCENT_H


/********************** Variable declarations ***********************/

extern CB_Index mdescent__num;
extern CB_Mem_Bool *mdescent_slowAscent;
extern CB_Mem_Bool *mdescent_fastAscent;
extern CB_Mem_Bool *mdescent_slowDescent;
extern CB_Mem_Bool *mdescent_fastDescent;
extern CB_Mem_Bool *mdescent_acknowledgePB;
extern CB_Mem_Bool *mdescent_autoMode;
extern CB_Mem_Bool *mdescent_manualMode;
extern CB_Mem_Bool *mdescent_ascentEnd;
extern CB_Mem_Bool *mdescent_topDeceleration;
extern CB_Mem_Bool *mdescent_downDeceleration;
extern CB_Mem_Bool *mdescent_descentEnd;
extern CB_Mem_Int *mdescent_motorFault;

/********************** Function declarations ***********************/

extern int _drill__mdescent_init(void);
extern int drill__mdescent(void);

#endif /*_DRILL__MDESCENT_H*/
