/*2023-10-03T11:12:47-01:00*/

/********************************************************************
 * io_double_acting_jack.h
 * 
 * generated by: plcgen 3.1.391
 ********************************************************************/

#ifndef _IO_LIBRARY__IO_DOUBLE_ACTING_JACK_H
#define _IO_LIBRARY__IO_DOUBLE_ACTING_JACK_H


/********************** Variable declarations ***********************/

extern CB_Index io_double_acting_jack__num;
extern CB_Mem_Bool *io_double_acting_jack_acknowledgePB;
extern CB_Mem_Bool *io_double_acting_jack_autoMode;
extern CB_Mem_Bool *io_double_acting_jack_manualMode;
extern CB_Mem_Bool *io_double_acting_jack_autoWorkCmd;
extern CB_Mem_Bool *io_double_acting_jack_autoRestCmd;
extern CB_Mem_Bool *io_double_acting_jack_generalFault;
extern CB_Mem_Float *io_double_acting_jack_rodPosition;
extern CB_Mem_Float *io_double_acting_jack_rodPercent;
extern CB_Mem_Float *io_double_acting_jack_incrementValue;
extern CB_Mem_Bool *io_double_acting_jack_inletSensor;
extern CB_Mem_Bool *io_double_acting_jack_outletSensor;

/********************** Function declarations ***********************/

extern int _io_library__io_double_acting_jack_init(void);
extern int io_library__io_double_acting_jack(void);

#endif /*_IO_LIBRARY__IO_DOUBLE_ACTING_JACK_H*/
