/*2023-10-03T11:13:25-01:00*/

/********************************************************************
 * trend.h
 * 
 * generated by: plcgen 3.1.391
 ********************************************************************/

#ifndef _EQUIPMENT_LIBRARY__TREND_H
#define _EQUIPMENT_LIBRARY__TREND_H


/********************** Variable declarations ***********************/

extern CB_Index trend__num;
extern CB_Mem_Float *trend_gradient;
extern CB_Mem_Float *trend_interceptPoint;
extern CB_Mem_Float *trend_A;
extern CB_Mem_Float *trend_B;
extern CB_Mem_Float *trend_time;
extern CB_Mem_Float *trend_realOutput;
extern CB_Mem_Float *trend_theoricalOutput;
extern CB_Mem_Float *trend_memoSlope;
extern CB_Mem_Float *trend_memoInc;
extern CB_Mem_Bool *trend_d_resetParameters;
extern CB_Mem_Bool *trend_v_d_resetParameters;
extern CB_Mem_Bool *trend_d_intermediatePresetting;
extern CB_Mem_Float *trend_v_d_intermediatePresetting;

/********************** Function declarations ***********************/

extern int _equipment_library__trend_init(void);
extern int equipment_library__trend(void);

#endif /*_EQUIPMENT_LIBRARY__TREND_H*/
