/*2023-10-03T11:12:58-01:00*/

/********************************************************************
 * balance.h
 * 
 * generated by: plcgen 3.1.391
 ********************************************************************/

#ifndef _EQUIPMENT_LIBRARY__BALANCE_H
#define _EQUIPMENT_LIBRARY__BALANCE_H


/********************** Variable declarations ***********************/

extern CB_Index balance__num;
extern CB_Mem_Bool *balance_reset;
extern CB_Mem_Float *balance_weight;
extern CB_Mem_Bool *balance_calibration;
extern CB_Mem_Float *balance_valueWeight;
extern CB_Mem_Bool *balance_stableWeight;
extern CB_Mem_Float *balance_tare;
extern CB_Mem_Float *balance_oldWeight;
extern CB_Mem_Bool *balance_stableLogic;
extern CB_Mem_Bool *balance_d_stable;
extern CB_Mem_Bool *balance_v_d_stable;
extern CB_Mem_Bool *balance_d_measure;
extern CB_Mem_Float *balance_v_d_measure;

/********************** Function declarations ***********************/

extern int _equipment_library__balance_init(void);
extern int equipment_library__balance(void);

#endif /*_EQUIPMENT_LIBRARY__BALANCE_H*/
