/*2023-10-03T11:13:44-01:00*/

/********************************************************************
 * mode_cov.c
 * 
 * generated by: plcgen 3.1.391
 ********************************************************************/

#include "cb_comp.h"
#include "cb_covs.h"
#include "iec_1131.h"

#include "mode.h"


/**************************** Variables *****************************/

CB_Index mode__num = 0;
CB_Mem_Bool *mode_powerUpPB;
CB_Mem_Bool *mode_startCyclePB;
CB_Mem_Bool *mode_emergencyStop;
CB_Mem_Bool *mode_batchCycle;
CB_Mem_Bool *mode_pieceCycle;
CB_Mem_Bool *mode_autoSwitch;
CB_Mem_Bool *mode_manualSwitch;
CB_Mem_Bool *mode_cycleEnd;
CB_Mem_Bool *mode_acknowledgePB;
CB_Mem_Bool *mode_live;
CB_Mem_Bool *mode_autoMode;
CB_Mem_Bool *mode_manualMode;
CB_Mem_Bool *mode_emptyProd;
CB_Mem_Bool *mode_unitProd;
CB_Mem_Bool *mode_batchProd;
CB_Mem_Bool *mode_emergencyState;
CB_Mem_Bool *mode_sr1_Q1;
CB_Mem_Int *mode_sr1_i_sr;
CB_Mem_Bool *mode_powerUpPB_PREV;
CB_Mem_Int *mode_powerUpPB_EDGE;
CB_Mem_Bool *mode_acknowledgePB_PREV;
CB_Mem_Int *mode_acknowledgePB_EDGE;
CB_Mem_Bool *mode_startCyclePB_PREV;
CB_Mem_Int *mode_startCyclePB_EDGE;
CB_Mem_Bool *mode_cycleEnd_PREV;
CB_Mem_Int *mode_cycleEnd_EDGE;

/**************************** Variables *****************************/

#define powerUpPB (mode_powerUpPB->CB_current_value)
#define startCyclePB (mode_startCyclePB->CB_current_value)
#define emergencyStop (mode_emergencyStop->CB_current_value)
#define batchCycle (mode_batchCycle->CB_current_value)
#define pieceCycle (mode_pieceCycle->CB_current_value)
#define autoSwitch (mode_autoSwitch->CB_current_value)
#define manualSwitch (mode_manualSwitch->CB_current_value)
#define cycleEnd (mode_cycleEnd->CB_current_value)
#define acknowledgePB (mode_acknowledgePB->CB_current_value)
#define live (mode_live->CB_current_value)
#define autoMode (mode_autoMode->CB_current_value)
#define manualMode (mode_manualMode->CB_current_value)
#define emptyProd (mode_emptyProd->CB_current_value)
#define unitProd (mode_unitProd->CB_current_value)
#define batchProd (mode_batchProd->CB_current_value)
#define emergencyState (mode_emergencyState->CB_current_value)
#define sr1_Q1 (mode_sr1_Q1->CB_current_value)
#define sr1_i_sr (*((short *)&(mode_sr1_i_sr->CB_current_value) + ALIGN_OFFSET_SHORT))
#define powerUpPB_PREV (mode_powerUpPB_PREV->CB_current_value)
#define powerUpPB_EDGE (mode_powerUpPB_EDGE->CB_current_value)
#define acknowledgePB_PREV (mode_acknowledgePB_PREV->CB_current_value)
#define acknowledgePB_EDGE (mode_acknowledgePB_EDGE->CB_current_value)
#define startCyclePB_PREV (mode_startCyclePB_PREV->CB_current_value)
#define startCyclePB_EDGE (mode_startCyclePB_EDGE->CB_current_value)
#define cycleEnd_PREV (mode_cycleEnd_PREV->CB_current_value)
#define cycleEnd_EDGE (mode_cycleEnd_EDGE->CB_current_value)


/************************ Components offsets ************************/


/********************* Initialization function **********************/

int _drill__mode_init(void)
{
	self.Bool+=6;
	self.Int+=5;


	return 0;
}


/************************ Behavior function *************************/

int drill__mode(void)
{
	static char *__comp_name = "drill.mode";
	if (exec_term_node(self_num)) {

		/*********************** Internals variables ************************/

		mode_emergencyState = self.Bool+0;
		mode_sr1_Q1 = self.Bool+1;
		mode_sr1_i_sr = self.Int+0;
		mode_powerUpPB_PREV = self.Bool+2;
		mode_powerUpPB_EDGE = self.Int+1;
		mode_acknowledgePB_PREV = self.Bool+3;
		mode_acknowledgePB_EDGE = self.Int+2;
		mode_startCyclePB_PREV = self.Bool+4;
		mode_startCyclePB_EDGE = self.Int+3;
		mode_cycleEnd_PREV = self.Bool+5;
		mode_cycleEnd_EDGE = self.Int+4;

		/********************* Pre-conditions execution *********************/

		/*no Pre-conditions*/

		/************************ Behavior execution ************************/

		{
			unsigned char _5;
			unsigned char _4;
			unsigned char _3;
			unsigned char _9;
			unsigned char _7;
			unsigned char _8;
			unsigned char _13;
			unsigned char _46;
			unsigned char _15;
			unsigned char _14;
			unsigned char _16;
			unsigned char _36;
			unsigned char _44;
			unsigned char _39;
			unsigned char _42;
			unsigned char _17;
			unsigned char _21;
			unsigned char _28;
			unsigned char _29;
			unsigned char _18;
			unsigned char _22;
			unsigned char _27;
			unsigned char _30;
			unsigned char _37;
			unsigned char _38;
			unsigned char _32;
			unsigned char _31;
			unsigned char _45;
			unsigned char _34;
			unsigned char _23;
			unsigned char _25;
			unsigned char _43;
			startCyclePB_EDGE = CB_edge_bool(startCyclePB, startCyclePB_PREV);
			cycleEnd_EDGE = CB_edge_bool(cycleEnd, cycleEnd_PREV);
			powerUpPB_EDGE = CB_edge_bool(powerUpPB, powerUpPB_PREV);
			acknowledgePB_EDGE = CB_edge_bool(acknowledgePB, acknowledgePB_PREV);
			_5 = powerUpPB_EDGE > 0;
			cov_output(__comp_name, self_num, 5, 0, _5);
			_4 = _5 && !live;
			cov_output(__comp_name, self_num, 4, 0, _4);
			_3 = _5 && live;
			cov_output(__comp_name, self_num, 3, 0, _3);
			sr1_Q1 = sr_Q1(_4, _3, &sr1_i_sr);
			cov_output(__comp_name, self_num, 2, 1, sr1_Q1);
			live = sr1_Q1;
			cov_output(__comp_name, self_num, 1, 0, live);
			_9 = !emergencyStop;
			cov_output(__comp_name, self_num, 9, 0, _9);
			if (_9) {
				emergencyState = 1;
			}
			cov_output(__comp_name, self_num, 10, 0, emergencyState);
			_7 = acknowledgePB_EDGE < 0;
			cov_output(__comp_name, self_num, 7, 0, _7);
			_8 = _7 && emergencyStop;
			cov_output(__comp_name, self_num, 8, 0, _8);
			if (_8) {
				emergencyState = 0;
			}
			cov_output(__comp_name, self_num, 11, 0, emergencyState);
			_13 = live;
			cov_output(__comp_name, self_num, 13, 0, _13);
			_46 = _13 && !emergencyState;
			cov_output(__comp_name, self_num, 46, 0, _46);
			_15 = _46 && autoSwitch;
			cov_output(__comp_name, self_num, 15, 0, _15);
			_14 = _15 && !manualSwitch;
			cov_output(__comp_name, self_num, 14, 0, _14);
			autoMode = _14;
			cov_output(__comp_name, self_num, 40, 0, autoMode);
			_16 = _46 && !autoSwitch;
			cov_output(__comp_name, self_num, 16, 0, _16);
			_36 = _16 && manualSwitch;
			cov_output(__comp_name, self_num, 36, 0, _36);
			manualMode = _36;
			cov_output(__comp_name, self_num, 41, 0, manualMode);
			_44 = startCyclePB_EDGE > 0;
			cov_output(__comp_name, self_num, 44, 0, _44);
			_39 = _44 && cycleEnd;
			cov_output(__comp_name, self_num, 39, 0, _39);
			_42 = _39 && autoMode;
			cov_output(__comp_name, self_num, 42, 0, _42);
			_17 = _42 && pieceCycle;
			cov_output(__comp_name, self_num, 17, 0, _17);
			_21 = _17 && !batchCycle;
			cov_output(__comp_name, self_num, 21, 0, _21);
			_28 = _21 && !batchProd;
			cov_output(__comp_name, self_num, 28, 0, _28);
			_29 = _28 && !emptyProd;
			cov_output(__comp_name, self_num, 29, 0, _29);
			if (_29) {
				unitProd = 1;
			}
			cov_output(__comp_name, self_num, 19, 0, unitProd);
			_18 = _42 && !pieceCycle;
			cov_output(__comp_name, self_num, 18, 0, _18);
			_22 = _18 && batchCycle;
			cov_output(__comp_name, self_num, 22, 0, _22);
			_27 = _22 && !unitProd;
			cov_output(__comp_name, self_num, 27, 0, _27);
			_30 = _27 && !emptyProd;
			cov_output(__comp_name, self_num, 30, 0, _30);
			if (_30) {
				batchProd = 1;
			}
			cov_output(__comp_name, self_num, 20, 0, batchProd);
			_37 = _42 && !pieceCycle;
			cov_output(__comp_name, self_num, 37, 0, _37);
			_38 = _37 && !batchCycle;
			cov_output(__comp_name, self_num, 38, 0, _38);
			_32 = _38 && !unitProd;
			cov_output(__comp_name, self_num, 32, 0, _32);
			_31 = _32 && !batchProd;
			cov_output(__comp_name, self_num, 31, 0, _31);
			if (_31) {
				emptyProd = 1;
			}
			cov_output(__comp_name, self_num, 33, 0, emptyProd);
			_45 = cycleEnd_EDGE < 0;
			cov_output(__comp_name, self_num, 45, 0, _45);
			_34 = _45 && emptyProd;
			cov_output(__comp_name, self_num, 34, 0, _34);
			if (_34) {
				emptyProd = 0;
			}
			cov_output(__comp_name, self_num, 35, 0, emptyProd);
			_23 = _45 && unitProd;
			cov_output(__comp_name, self_num, 23, 0, _23);
			if (_23) {
				unitProd = 0;
			}
			cov_output(__comp_name, self_num, 24, 0, unitProd);
			_25 = _45 && batchProd;
			cov_output(__comp_name, self_num, 25, 0, _25);
			_43 = _25 && !autoMode;
			cov_output(__comp_name, self_num, 43, 0, _43);
			if (_43) {
				batchProd = 0;
			}
			cov_output(__comp_name, self_num, 26, 0, batchProd);
			startCyclePB_PREV = startCyclePB;
			cycleEnd_PREV = cycleEnd;
			powerUpPB_PREV = powerUpPB;
			acknowledgePB_PREV = acknowledgePB;
		}

		if(nb_alloc > 0) {
			free_all_alloc();
		}

		CB_post_bool(mode_live);
		CB_post_bool(mode_autoMode);
		CB_post_bool(mode_manualMode);
		CB_post_bool(mode_emptyProd);
		CB_post_bool(mode_unitProd);
		CB_post_bool(mode_batchProd);

		/******************** Post-conditions execution *********************/

		/*no Post-conditions*/
	}

	/*************************** self update ****************************/

	self.Bool += 6;
	self.Int += 5;

	return 0;
}

