/*2023-10-03T11:13:32-01:00*/

/********************************************************************
 * coef_scale.h
 * 
 * generated by: plcgen 3.1.391
 ********************************************************************/

#ifndef _EQUIPMENT_LIBRARY__COEF_SCALE_H
#define _EQUIPMENT_LIBRARY__COEF_SCALE_H


/********************** Variable declarations ***********************/

extern CB_Index coef_scale__num;
extern CB_Mem_Float *coef_scale_inputValue;
extern CB_Mem_Float *coef_scale_outputValue;
extern CB_Mem_Float *coef_scale_coefficient;
extern CB_Mem_Bool *coef_scale_d_scale;
extern CB_Mem_Float *coef_scale_v_d_scale;

/********************** Function declarations ***********************/

extern int _equipment_library__coef_scale_init(void);
extern int equipment_library__coef_scale(void);

#endif /*_EQUIPMENT_LIBRARY__COEF_SCALE_H*/
