/*2023-10-03T11:13:48-01:00*/

/********************************************************************
 * tni_clock.c
 * 
 * generated by: plcgen 3.1.391
 ********************************************************************/

#include "cb_comp.h"
#include "iec_1131.h"

#include "tni_clock.h"
#include "tni_clock/functional/environment/environment.h"
#include "tni_clock/functional/controller/controller.h"
#include "tni_clock/functional/lcd/lcd.h"
#include "tni_clock/functional/motors/motors.h"
#include "tni_clock/functional/lightclock/lightclock.h"


/**************************** Variables *****************************/

CB_Index tni_clock__num = 0;
CB_Mem_Bool *tni_clock_B1;
CB_Mem_Bool *tni_clock_B2;
CB_Mem_Bool *tni_clock_B3;
CB_Mem_Bool *tni_clock_B4;
CB_Mem_Int *tni_clock_depth;

/**************************** Variables *****************************/



/************************ Components offsets ************************/

static CB_Offset tni_clock__tni_clock_offset_environment;
static CB_Offset tni_clock__tni_clock_offset_controller;
static CB_Offset tni_clock__tni_clock_offset_LCD;
static CB_Offset tni_clock__tni_clock_offset_motors;
static CB_Offset tni_clock__tni_clock_offset_light;
static CB_Offset tni_clock__tni_clock_offset__end = {0, 0, 0, 0};


/********************* Initialization function **********************/

int _tni_clock__tni_clock_init(void)
{
	CB_Object __start = self;
	self.Bool+=5;
	self.Int+=11;

	/*initialize child environment (tni_clock.environment):*/
	self_num++;
	tni_clock__tni_clock_offset_environment.Bool = self.Bool - __start.Bool;
	tni_clock__tni_clock_offset_environment.Int = self.Int - __start.Int;
	tni_clock__tni_clock_offset_environment.Float = self.Float - __start.Float;
	tni_clock__tni_clock_offset_environment.Char = self.Char - __start.Char;
	environment_depth = tni_clock_depth;
	environment_B1 = tni_clock_B1;
	environment_B2 = tni_clock_B2;
	environment_B3 = tni_clock_B3;
	environment_B4 = tni_clock_B4;
	environment_pressure = __start.Int+0; /*tni_clock__cn_7*/
	environment_tick = __start.Bool+0; /*tni_clock__cn_6*/
	_tni_clock__environment_init();

	/*initialize child controller (tni_clock.controller):*/
	self_num++;
	tni_clock__tni_clock_offset_controller.Bool = self.Bool - __start.Bool;
	tni_clock__tni_clock_offset_controller.Int = self.Int - __start.Int;
	tni_clock__tni_clock_offset_controller.Float = self.Float - __start.Float;
	tni_clock__tni_clock_offset_controller.Char = self.Char - __start.Char;
	controller_pressure = __start.Int+0; /*tni_clock__cn_7*/
	controller_tick = __start.Bool+0; /*tni_clock__cn_6*/
	controller_B1 = tni_clock_B1;
	controller_B2 = tni_clock_B2;
	controller_B3 = tni_clock_B3;
	controller_B4 = tni_clock_B4;
	controller_displayValue = __start.Int+1; /*tni_clock__cn_5*/
	controller_stepMotorSecond = __start.Bool+1; /*tni_clock__cn_4*/
	controller_stepMotorMinute = __start.Bool+2; /*tni_clock__cn_3*/
	controller_stepMotorHour = __start.Bool+3; /*tni_clock__cn_2*/
	controller_switchOnLight = __start.Bool+4; /*tni_clock__cn_1*/
	_tni_clock__controller_init();

	/*initialize child LCD (tni_clock.lcd):*/
	self_num++;
	tni_clock__tni_clock_offset_LCD.Bool = self.Bool - __start.Bool;
	tni_clock__tni_clock_offset_LCD.Int = self.Int - __start.Int;
	tni_clock__tni_clock_offset_LCD.Float = self.Float - __start.Float;
	tni_clock__tni_clock_offset_LCD.Char = self.Char - __start.Char;
	lcd_displayValue = __start.Int+1; /*tni_clock__cn_5*/
	_tni_clock__lcd_init();

	/*initialize child motors (tni_clock.motors):*/
	self_num++;
	tni_clock__tni_clock_offset_motors.Bool = self.Bool - __start.Bool;
	tni_clock__tni_clock_offset_motors.Int = self.Int - __start.Int;
	tni_clock__tni_clock_offset_motors.Float = self.Float - __start.Float;
	tni_clock__tni_clock_offset_motors.Char = self.Char - __start.Char;
	motors_stepMotorSecond = __start.Bool+1; /*tni_clock__cn_4*/
	motors_stepMotorMinute = __start.Bool+2; /*tni_clock__cn_3*/
	motors_stepMotorHour = __start.Bool+3; /*tni_clock__cn_2*/
	_tni_clock__motors_init();

	/*initialize child light (tni_clock.lightclock):*/
	self_num++;
	tni_clock__tni_clock_offset_light.Bool = self.Bool - __start.Bool;
	tni_clock__tni_clock_offset_light.Int = self.Int - __start.Int;
	tni_clock__tni_clock_offset_light.Float = self.Float - __start.Float;
	tni_clock__tni_clock_offset_light.Char = self.Char - __start.Char;
	lightclock_switchOnLight = __start.Bool+4; /*tni_clock__cn_1*/
	_tni_clock__lightclock_init();

	tni_clock__tni_clock_offset__end.Bool = self.Bool - __start.Bool;
	tni_clock__tni_clock_offset__end.Int = self.Int - __start.Int;
	tni_clock__tni_clock_offset__end.Float = self.Float - __start.Float;
	tni_clock__tni_clock_offset__end.Char = self.Char - __start.Char;

	return 0;
}


/************************ Behavior function *************************/

int tni_clock__tni_clock(void)
{
	CB_Object __start = self;
	int __ret;
	if (exec_mac_node(self_num)) {

		/*********************** Internals variables ************************/

														
		/********************* Pre-conditions execution *********************/

		/*no Pre-conditions*/

		/************************ Behavior execution ************************/

		{
			self.Bool = __start.Bool + tni_clock__tni_clock_offset_environment.Bool;
			self.Int = __start.Int + tni_clock__tni_clock_offset_environment.Int;
			self.Float = __start.Float + tni_clock__tni_clock_offset_environment.Float;
			self.Char = __start.Char + tni_clock__tni_clock_offset_environment.Char;

			/********************** environment execution ***********************/

			self_num++;
			if (environment__num != self_num) {
				environment__num = self_num;
				environment_depth = tni_clock_depth;
				environment_B1 = tni_clock_B1;
				environment_B2 = tni_clock_B2;
				environment_B3 = tni_clock_B3;
				environment_B4 = tni_clock_B4;
				environment_pressure = __start.Int+0; /*tni_clock__cn_7*/
				environment_tick = __start.Bool+0; /*tni_clock__cn_6*/
			}
			__ret = tni_clock__environment();
			if (__ret != 0) {
				return __ret; /*child execution failure*/
			}

			/*********************** controller execution ***********************/

			self_num++;
			if (controller__num != self_num) {
				controller__num = self_num;
				controller_pressure = __start.Int+0; /*tni_clock__cn_7*/
				controller_tick = __start.Bool+0; /*tni_clock__cn_6*/
				controller_B1 = tni_clock_B1;
				controller_B2 = tni_clock_B2;
				controller_B3 = tni_clock_B3;
				controller_B4 = tni_clock_B4;
				controller_displayValue = __start.Int+1; /*tni_clock__cn_5*/
				controller_stepMotorSecond = __start.Bool+1; /*tni_clock__cn_4*/
				controller_stepMotorMinute = __start.Bool+2; /*tni_clock__cn_3*/
				controller_stepMotorHour = __start.Bool+3; /*tni_clock__cn_2*/
				controller_switchOnLight = __start.Bool+4; /*tni_clock__cn_1*/
			}
			__ret = tni_clock__controller();
			if (__ret != 0) {
				return __ret; /*child execution failure*/
			}

			/************************** LCD execution ***************************/

			self_num++;
			if (lcd__num != self_num) {
				lcd__num = self_num;
				lcd_displayValue = __start.Int+1; /*tni_clock__cn_5*/
			}
			__ret = tni_clock__lcd();
			if (__ret != 0) {
				return __ret; /*child execution failure*/
			}

			/************************* motors execution *************************/

			self_num++;
			if (motors__num != self_num) {
				motors__num = self_num;
				motors_stepMotorSecond = __start.Bool+1; /*tni_clock__cn_4*/
				motors_stepMotorMinute = __start.Bool+2; /*tni_clock__cn_3*/
				motors_stepMotorHour = __start.Bool+3; /*tni_clock__cn_2*/
			}
			__ret = tni_clock__motors();
			if (__ret != 0) {
				return __ret; /*child execution failure*/
			}

			/************************* light execution **************************/

			self_num++;
			if (lightclock__num != self_num) {
				lightclock__num = self_num;
				lightclock_switchOnLight = __start.Bool+4; /*tni_clock__cn_1*/
			}
			__ret = tni_clock__lightclock();
			if (__ret != 0) {
				return __ret; /*child execution failure*/
			}

		}


		/******************** Post-conditions execution *********************/

		/*no Post-conditions*/
	}

	/*************************** self update ****************************/

	self.Bool = __start.Bool + tni_clock__tni_clock_offset__end.Bool;
	self.Int = __start.Int + tni_clock__tni_clock_offset__end.Int;
	self.Float = __start.Float + tni_clock__tni_clock_offset__end.Float;
	self.Char = __start.Char + tni_clock__tni_clock_offset__end.Char;

	return 0;
}

