/*2023-10-03T11:13:43-01:00*/

/********************************************************************
 * piece_cov.c
 * 
 * generated by: plcgen 3.1.391
 ********************************************************************/

#include "cb_comp.h"
#include "cb_covs.h"
#include "iec_1131.h"

#include "piece.h"



/**************************** Variables *****************************/

CB_Index piece__num = 0;
CB_Mem_Bool *piece_loadingRequest;
CB_Mem_Bool *piece_unloadingRequest;
CB_Mem_Bool *piece_piece;
CB_Mem_Int *piece_count;
CB_Mem_Int *piece_loadingDuration;

/**************************** Variables *****************************/

#define loadingRequest (piece_loadingRequest->CB_current_value)
#define unloadingRequest (piece_unloadingRequest->CB_current_value)
#define piece (piece_piece->CB_current_value)
#define count (piece_count->CB_current_value)
#define loadingDuration (piece_loadingDuration->CB_current_value)


/************************ Components offsets ************************/


/********************* Initialization function **********************/

int _drill__piece_init(void)
{
	(self.Int+1)->CB_current_value = 10; /*loadingDuration*/
	self.Int+=2;


	return 0;
}


/************************ Behavior function *************************/

int drill__piece(void)
{
	static char *__comp_name = "drill.piece";
	if (exec_term_node(self_num)) {

		/*********************** Internals variables ************************/

		piece_count = self.Int+0;
		piece_loadingDuration = self.Int+1;

		/********************* Pre-conditions execution *********************/

		/*no Pre-conditions*/

		/************************ Behavior execution ************************/

		{
			if (loadingRequest)
			   {
			   piece = 1;
			   count = 0;
			   }
			if (unloadingRequest)
			   {
			   count = count+1;
			   if (count == loadingDuration) piece=0;
			   }
		}

		CB_post_bool(piece_piece);

		/******************** Post-conditions execution *********************/

		/*no Post-conditions*/
	}

	/*************************** self update ****************************/

	self.Int += 2;

	return 0;
}

