/*2024-04-12T14:05:57-01:00*/

/********************************************************************
 * flour_weighing.h
 * 
 * generated by: plcgen 3.1.391
 ********************************************************************/

#ifndef _COPIE_BATCH__FLOUR_WEIGHING_H
#define _COPIE_BATCH__FLOUR_WEIGHING_H


/********************** Variable declarations ***********************/

extern CB_Index flour_weighing__num;
extern CB_Mem_Bool *flour_weighing_weighingRequest;
extern CB_Mem_Bool *flour_weighing_cycleInProgress;
extern CB_Mem_Int *flour_weighing_weighedWeight;
extern CB_Mem_Int *flour_weighing_flourWeight;
extern CB_Mem_Bool *flour_weighing_weighingOk;
extern CB_Mem_Bool *flour_weighing_introduceFlour;
extern CB_Mem_Bool *flour_weighing_introFlourEnd;
extern CB_Mem_Bool *flour_weighing_exitFlour;
extern CB_Mem_Bool *flour_weighing_exitFlourEnd;
extern CB_Mem_Int *flour_weighing_totalWeight;
extern CB_Mem_Bool *flour_weighing_endOfWeighing;
extern CB_Mem_Int *flour_weighing_maxWeight;

/********************** Function declarations ***********************/

extern int _copie_batch__flour_weighing_init(void);
extern int copie_batch__flour_weighing(void);

#endif /*_COPIE_BATCH__FLOUR_WEIGHING_H*/
