/*2023-10-03T11:13:46-01:00*/

/********************************************************************
 * mclamping.c
 * 
 * generated by: plcgen 3.1.391
 ********************************************************************/

#include "cb_comp.h"
#include "iec_1131.h"

#include "mclamping.h"
#include "drill/functional/clamping/clamping.h"
#include "io_library/functional/io_single_acting_jack/io_single_acting_jack.h"


/**************************** Variables *****************************/

CB_Index mclamping__num = 0;
CB_Mem_Bool *mclamping_acknowledgePB;
CB_Mem_Bool *mclamping_autoMode;
CB_Mem_Bool *mclamping_manualMode;
CB_Mem_Bool *mclamping_releasing;
CB_Mem_Bool *mclamping_clamping;
CB_Mem_Bool *mclamping_clampingOK;
CB_Mem_Bool *mclamping_releasingOK;
CB_Mem_Int *mclamping_clampingFault;

/**************************** Variables *****************************/



/************************ Components offsets ************************/

static CB_Offset drill__mclamping_offset_clampingFunction;
static CB_Offset drill__mclamping_offset_leftJack;
static CB_Offset drill__mclamping_offset_rightJack;
static CB_Offset drill__mclamping_offset__end = {0, 0, 0, 0};


/********************* Initialization function **********************/

int _drill__mclamping_init(void)
{
	CB_Object __start = self;
	self.Bool+=8;
	self.Float+=6;

	/*initialize child clampingFunction (drill.clamping):*/
	self_num++;
	drill__mclamping_offset_clampingFunction.Bool = self.Bool - __start.Bool;
	drill__mclamping_offset_clampingFunction.Int = self.Int - __start.Int;
	drill__mclamping_offset_clampingFunction.Float = self.Float - __start.Float;
	drill__mclamping_offset_clampingFunction.Char = self.Char - __start.Char;
	clamping_acknowledgePB = mclamping_acknowledgePB;
	clamping_releasing = mclamping_releasing;
	clamping_clamping = mclamping_clamping;
	clamping_rightUnlocked = __start.Bool+0; /*mclamping__cn_8*/
	clamping_rightLocked = __start.Bool+1; /*mclamping__cn_7*/
	clamping_leftUnlocked = __start.Bool+2; /*mclamping__cn_6*/
	clamping_leftLocked = __start.Bool+3; /*mclamping__cn_5*/
	clamping_rightFault = __start.Bool+4; /*mclamping__cn_4*/
	clamping_leftFault = __start.Bool+5; /*mclamping__cn_3*/
	clamping_clampingOK = mclamping_clampingOK;
	clamping_releasingOK = mclamping_releasingOK;
	clamping_clampingFault = mclamping_clampingFault;
	clamping_rightLocking = __start.Bool+7; /*mclamping__cn_1*/
	clamping_leftLocking = __start.Bool+6; /*mclamping__cn_2*/
	_drill__clamping_init();

	/*initialize child leftJack (io_library.io_single_acting_jack):*/
	self_num++;
	drill__mclamping_offset_leftJack.Bool = self.Bool - __start.Bool;
	drill__mclamping_offset_leftJack.Int = self.Int - __start.Int;
	drill__mclamping_offset_leftJack.Float = self.Float - __start.Float;
	drill__mclamping_offset_leftJack.Char = self.Char - __start.Char;
	io_single_acting_jack_acknowledgePB = mclamping_acknowledgePB;
	io_single_acting_jack_autoMode = mclamping_autoMode;
	io_single_acting_jack_manualMode = mclamping_manualMode;
	io_single_acting_jack_autoWorkCmd = __start.Bool+6; /*mclamping__cn_2*/
	io_single_acting_jack_generalFault = __start.Bool+5; /*mclamping__cn_3*/
	io_single_acting_jack_inletSensor = __start.Bool+2; /*mclamping__cn_6*/
	io_single_acting_jack_outletSensor = __start.Bool+3; /*mclamping__cn_5*/
	io_single_acting_jack_rodPosition = __start.Float+5; /*mclamping__cn_9*/
	io_single_acting_jack_rodPercent = __start.Float+4; /*mclamping__cn_10*/
	io_single_acting_jack_incrementValue = __start.Float+3; /*mclamping__cn_11*/
	_io_library__io_single_acting_jack_init();

	/*initialize child rightJack (io_library.io_single_acting_jack):*/
	self_num++;
	drill__mclamping_offset_rightJack.Bool = self.Bool - __start.Bool;
	drill__mclamping_offset_rightJack.Int = self.Int - __start.Int;
	drill__mclamping_offset_rightJack.Float = self.Float - __start.Float;
	drill__mclamping_offset_rightJack.Char = self.Char - __start.Char;
	io_single_acting_jack_acknowledgePB = mclamping_acknowledgePB;
	io_single_acting_jack_autoMode = mclamping_autoMode;
	io_single_acting_jack_manualMode = mclamping_manualMode;
	io_single_acting_jack_autoWorkCmd = __start.Bool+7; /*mclamping__cn_1*/
	io_single_acting_jack_generalFault = __start.Bool+4; /*mclamping__cn_4*/
	io_single_acting_jack_inletSensor = __start.Bool+0; /*mclamping__cn_8*/
	io_single_acting_jack_outletSensor = __start.Bool+1; /*mclamping__cn_7*/
	io_single_acting_jack_rodPosition = __start.Float+2; /*mclamping__cn_12*/
	io_single_acting_jack_rodPercent = __start.Float+1; /*mclamping__cn_13*/
	io_single_acting_jack_incrementValue = __start.Float+0; /*mclamping__cn_14*/
	_io_library__io_single_acting_jack_init();

	drill__mclamping_offset__end.Bool = self.Bool - __start.Bool;
	drill__mclamping_offset__end.Int = self.Int - __start.Int;
	drill__mclamping_offset__end.Float = self.Float - __start.Float;
	drill__mclamping_offset__end.Char = self.Char - __start.Char;

	return 0;
}


/************************ Behavior function *************************/

int drill__mclamping(void)
{
	CB_Object __start = self;
	int __ret;
	if (exec_mac_node(self_num)) {

		/*********************** Internals variables ************************/

																												
		/********************* Pre-conditions execution *********************/

		/*no Pre-conditions*/

		/************************ Behavior execution ************************/

		{
			self.Bool = __start.Bool + drill__mclamping_offset_clampingFunction.Bool;
			self.Int = __start.Int + drill__mclamping_offset_clampingFunction.Int;
			self.Float = __start.Float + drill__mclamping_offset_clampingFunction.Float;
			self.Char = __start.Char + drill__mclamping_offset_clampingFunction.Char;

			/******************** clampingFunction execution ********************/

			self_num++;
			if (clamping__num != self_num) {
				clamping__num = self_num;
				clamping_acknowledgePB = mclamping_acknowledgePB;
				clamping_releasing = mclamping_releasing;
				clamping_clamping = mclamping_clamping;
				clamping_rightUnlocked = __start.Bool+0; /*mclamping__cn_8*/
				clamping_rightLocked = __start.Bool+1; /*mclamping__cn_7*/
				clamping_leftUnlocked = __start.Bool+2; /*mclamping__cn_6*/
				clamping_leftLocked = __start.Bool+3; /*mclamping__cn_5*/
				clamping_rightFault = __start.Bool+4; /*mclamping__cn_4*/
				clamping_leftFault = __start.Bool+5; /*mclamping__cn_3*/
				clamping_clampingOK = mclamping_clampingOK;
				clamping_releasingOK = mclamping_releasingOK;
				clamping_clampingFault = mclamping_clampingFault;
				clamping_rightLocking = __start.Bool+7; /*mclamping__cn_1*/
				clamping_leftLocking = __start.Bool+6; /*mclamping__cn_2*/
			}
			__ret = drill__clamping();
			if (__ret != 0) {
				return __ret; /*child execution failure*/
			}

			/************************ leftJack execution ************************/

			self_num++;
			if (io_single_acting_jack__num != self_num) {
				io_single_acting_jack__num = self_num;
				io_single_acting_jack_acknowledgePB = mclamping_acknowledgePB;
				io_single_acting_jack_autoMode = mclamping_autoMode;
				io_single_acting_jack_manualMode = mclamping_manualMode;
				io_single_acting_jack_autoWorkCmd = __start.Bool+6; /*mclamping__cn_2*/
				io_single_acting_jack_generalFault = __start.Bool+5; /*mclamping__cn_3*/
				io_single_acting_jack_inletSensor = __start.Bool+2; /*mclamping__cn_6*/
				io_single_acting_jack_outletSensor = __start.Bool+3; /*mclamping__cn_5*/
				io_single_acting_jack_rodPosition = __start.Float+5; /*mclamping__cn_9*/
				io_single_acting_jack_rodPercent = __start.Float+4; /*mclamping__cn_10*/
				io_single_acting_jack_incrementValue = __start.Float+3; /*mclamping__cn_11*/
			}
			__ret = io_library__io_single_acting_jack();
			if (__ret != 0) {
				return __ret; /*child execution failure*/
			}

			/*********************** rightJack execution ************************/

			self_num++;
			if (io_single_acting_jack__num != self_num) {
				io_single_acting_jack__num = self_num;
				io_single_acting_jack_acknowledgePB = mclamping_acknowledgePB;
				io_single_acting_jack_autoMode = mclamping_autoMode;
				io_single_acting_jack_manualMode = mclamping_manualMode;
				io_single_acting_jack_autoWorkCmd = __start.Bool+7; /*mclamping__cn_1*/
				io_single_acting_jack_generalFault = __start.Bool+4; /*mclamping__cn_4*/
				io_single_acting_jack_inletSensor = __start.Bool+0; /*mclamping__cn_8*/
				io_single_acting_jack_outletSensor = __start.Bool+1; /*mclamping__cn_7*/
				io_single_acting_jack_rodPosition = __start.Float+2; /*mclamping__cn_12*/
				io_single_acting_jack_rodPercent = __start.Float+1; /*mclamping__cn_13*/
				io_single_acting_jack_incrementValue = __start.Float+0; /*mclamping__cn_14*/
			}
			__ret = io_library__io_single_acting_jack();
			if (__ret != 0) {
				return __ret; /*child execution failure*/
			}

		}


		/******************** Post-conditions execution *********************/

		/*no Post-conditions*/
	}

	/*************************** self update ****************************/

	self.Bool = __start.Bool + drill__mclamping_offset__end.Bool;
	self.Int = __start.Int + drill__mclamping_offset__end.Int;
	self.Float = __start.Float + drill__mclamping_offset__end.Float;
	self.Char = __start.Char + drill__mclamping_offset__end.Char;

	return 0;
}

