/*2023-10-03T11:13:47-01:00*/

/********************************************************************
 * lightclock.h
 * 
 * generated by: plcgen 3.1.391
 ********************************************************************/

#ifndef _TNI_CLOCK__LIGHTCLOCK_H
#define _TNI_CLOCK__LIGHTCLOCK_H


/********************** Variable declarations ***********************/

extern CB_Index lightclock__num;
extern CB_Mem_Bool *lightclock_switchOnLight;

/********************** Function declarations ***********************/

extern int _tni_clock__lightclock_init(void);
extern int tni_clock__lightclock(void);

#endif /*_TNI_CLOCK__LIGHTCLOCK_H*/
