/*2023-10-03T11:13:29-01:00*/

/********************************************************************
 * logical_and.h
 * 
 * generated by: plcgen 3.1.391
 ********************************************************************/

#ifndef _EQUIPMENT_LIBRARY__LOGICAL_AND_H
#define _EQUIPMENT_LIBRARY__LOGICAL_AND_H


/********************** Variable declarations ***********************/

extern CB_Index logical_and__num;
extern CB_Mem_Bool *logical_and_inputBit1;
extern CB_Mem_Bool *logical_and_inputBit2;
extern CB_Mem_Bool *logical_and_ouputBit;
extern CB_Mem_Bool *logical_and_input1Logic;
extern CB_Mem_Bool *logical_and_input2Logic;
extern CB_Mem_Bool *logical_and_outputLogic;
extern CB_Mem_Bool *logical_and_d_output;
extern CB_Mem_Bool *logical_and_v_d_output;

/********************** Function declarations ***********************/

extern int _equipment_library__logical_and_init(void);
extern int equipment_library__logical_and(void);

#endif /*_EQUIPMENT_LIBRARY__LOGICAL_AND_H*/
