/*2023-10-03T11:13:26-01:00*/

/********************************************************************
 * real2int_conversion.h
 * 
 * generated by: plcgen 3.1.391
 ********************************************************************/

#ifndef _EQUIPMENT_LIBRARY__REAL2INT_CONVERSION_H
#define _EQUIPMENT_LIBRARY__REAL2INT_CONVERSION_H


/********************** Variable declarations ***********************/

extern CB_Index real2int_conversion__num;
extern CB_Mem_Float *real2int_conversion_input;
extern CB_Mem_Int *real2int_conversion_dintOutput;
extern CB_Mem_Int *real2int_conversion_intOutput;

/********************** Function declarations ***********************/

extern int _equipment_library__real2int_conversion_init(void);
extern int equipment_library__real2int_conversion(void);

#endif /*_EQUIPMENT_LIBRARY__REAL2INT_CONVERSION_H*/
