/*2023-10-03T11:13:47-01:00*/

/********************************************************************
 * mspindle.h
 * 
 * generated by: plcgen 3.1.391
 ********************************************************************/

#ifndef _DRILL__MSPINDLE_H
#define _DRILL__MSPINDLE_H


/********************** Variable declarations ***********************/

extern CB_Index mspindle__num;
extern CB_Mem_Bool *mspindle_rotationFunction;
extern CB_Mem_Bool *mspindle_acknowledgePB;
extern CB_Mem_Bool *mspindle_autoMode;
extern CB_Mem_Bool *mspindle_manualMode;
extern CB_Mem_Int *mspindle_rotationFault;

/********************** Function declarations ***********************/

extern int _drill__mspindle_init(void);
extern int drill__mspindle(void);

#endif /*_DRILL__MSPINDLE_H*/
