/*2023-10-03T11:13:36-01:00*/

/********************************************************************
 * cmd_on_off_pump.h
 * 
 * generated by: plcgen 3.1.391
 ********************************************************************/

#ifndef _CMD_EQUIPMENT_LIBRARY__CMD_ON_OFF_PUMP_H
#define _CMD_EQUIPMENT_LIBRARY__CMD_ON_OFF_PUMP_H


/********************** Variable declarations ***********************/

extern CB_Index cmd_on_off_pump__num;
extern CB_Mem_Bool *cmd_on_off_pump_autoMode;
extern CB_Mem_Bool *cmd_on_off_pump_manualMode;
extern CB_Mem_Bool *cmd_on_off_pump_autoCmd;
extern CB_Mem_Bool *cmd_on_off_pump_thermalFB;
extern CB_Mem_Bool *cmd_on_off_pump_onFB;
extern CB_Mem_Bool *cmd_on_off_pump_onPB;
extern CB_Mem_Bool *cmd_on_off_pump_offPB;
extern CB_Mem_Bool *cmd_on_off_pump_acknowledgePB;
extern CB_Mem_Bool *cmd_on_off_pump_cmd;
extern CB_Mem_Bool *cmd_on_off_pump_generalFault;

/********************** Function declarations ***********************/

extern int _cmd_equipment_library__cmd_on_off_pump_init(void);
extern int cmd_equipment_library__cmd_on_off_pump(void);

#endif /*_CMD_EQUIPMENT_LIBRARY__CMD_ON_OFF_PUMP_H*/
