/*2023-10-03T11:12:54-01:00*/

/********************************************************************
 * sensor_fault.h
 * 
 * generated by: plcgen 3.1.391
 ********************************************************************/

#ifndef _EQUIPMENT_LIBRARY__SENSOR_FAULT_H
#define _EQUIPMENT_LIBRARY__SENSOR_FAULT_H


/********************** Variable declarations ***********************/

extern CB_Index sensor_fault__num;
extern CB_Mem_Bool *sensor_fault_sensorVal;
extern CB_Mem_Bool *sensor_fault_val;
extern CB_Mem_Bool *sensor_fault_d_sensor;
extern CB_Mem_Bool *sensor_fault_v_d_sensor;

/********************** Function declarations ***********************/

extern int _equipment_library__sensor_fault_init(void);
extern int equipment_library__sensor_fault(void);

#endif /*_EQUIPMENT_LIBRARY__SENSOR_FAULT_H*/
