<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- Generator: ControlBuild -->

<CB_COMPONENT NAME="sensor_fault" COMMENTS="This module makes it possible to generate faults on sensors (actors/products) thanks to graphical interface.
It is not an actor." COMMENTS_PATTERN="&lt;CLASS_PATTERN&gt;" PICTURE_PATH="" INSTANCE_NAMIMG_PATTERN="&lt;CLASS_PATTERN&gt;" COMPONENT_CLASS="SIMULATION" SAFE_MODE="False" BREAKPOINT="False" GEN_STATUS="good">
	<MODEL_REQUIREMENTS>
		<FUNCTIONAL_TREE TYPE="c" />
	</MODEL_REQUIREMENTS>
	<externalSrcs />
</CB_COMPONENT>