/*2023-10-03T11:13:04-01:00*/

/********************************************************************
 * single_acting_valve.h
 * 
 * generated by: plcgen 3.1.391
 ********************************************************************/

#ifndef _EQUIPMENT_LIBRARY__SINGLE_ACTING_VALVE_H
#define _EQUIPMENT_LIBRARY__SINGLE_ACTING_VALVE_H


/********************** Variable declarations ***********************/

extern CB_Index single_acting_valve__num;
extern CB_Mem_Bool *single_acting_valve_voltage380;
extern CB_Mem_Bool *single_acting_valve_cmdSupply;
extern CB_Mem_Bool *single_acting_valve_sensorSupply;
extern CB_Mem_Bool *single_acting_valve_openCmd;
extern CB_Mem_Float *single_acting_valve_inputFlow;
extern CB_Mem_Bool *single_acting_valve_openedSensor;
extern CB_Mem_Bool *single_acting_valve_closedSensor;
extern CB_Mem_Float *single_acting_valve_outputFlow;
extern CB_Mem_Float *single_acting_valve_percentOpening;
extern CB_Mem_Float *single_acting_valve_increment;
extern CB_Mem_Bool *single_acting_valve_openState;
extern CB_Mem_Bool *single_acting_valve_closeState;
extern CB_Mem_Float *single_acting_valve_openingVal;
extern CB_Mem_Float *single_acting_valve_unit;
extern CB_Mem_Float *single_acting_valve_openingTime;
extern CB_Mem_Bool *single_acting_valve_openedSensorLogic;
extern CB_Mem_Bool *single_acting_valve_closedSensorLogic;
extern CB_Mem_Float *single_acting_valve_flowMax;
extern CB_Mem_Bool *single_acting_valve_flowPerHour;
extern CB_Mem_Bool *single_acting_valve_flowPerMinute;
extern CB_Mem_Bool *single_acting_valve_d_locking;
extern CB_Mem_Float *single_acting_valve_v_d_locking;
extern CB_Mem_Bool *single_acting_valve_d_flow;
extern CB_Mem_Float *single_acting_valve_v_d_flow;
extern CB_Mem_Bool *single_acting_valve_d_electrical;
extern CB_Mem_Bool *single_acting_valve_v_d_electrical;
extern CB_Mem_Bool *single_acting_valve_d_openedSensor;
extern CB_Mem_Bool *single_acting_valve_v_d_openedSensor;
extern CB_Mem_Bool *single_acting_valve_d_closedSensor;
extern CB_Mem_Bool *single_acting_valve_v_d_closedSensor;

/********************** Function declarations ***********************/

extern int _equipment_library__single_acting_valve_init(void);
extern int equipment_library__single_acting_valve(void);

#endif /*_EQUIPMENT_LIBRARY__SINGLE_ACTING_VALVE_H*/
