/*2023-10-03T11:13:42-01:00*/

/********************************************************************
 * process.c
 * 
 * generated by: plcgen 3.1.391
 ********************************************************************/

#include "cb_comp.h"
#include "iec_1131.h"

#include "process.h"
#include "bottling_line/functional/master/master.h"
#include "bottling_line/functional/tanks_management/tanks_management.h"
#include "bottling_line/functional/preparation/preparation.h"
#include "bottling_line/functional/conveyor_management/conveyor_management.h"
#include "bottling_line/functional/requests_management/requests_management.h"


/**************************** Variables *****************************/

CB_Index process__num = 0;
CB_Mem_Bool *process_highLevel1;
CB_Mem_Bool *process_lowLevel1;
CB_Mem_Bool *process_highLevel2;
CB_Mem_Bool *process_lowLevel2;
CB_Mem_Bool *process_highLevel3;
CB_Mem_Bool *process_lowLevel3;
CB_Mem_Bool *process_startCyclePB;
CB_Mem_Bool *process_initPB;
CB_Mem_Bool *process_preparationPB;
CB_Mem_Bool *process_productionPB;
CB_Mem_Bool *process_closingPB;
CB_Mem_Bool *process_pulseGenerator;
CB_Mem_Bool *process_bottleFilled;
CB_Mem_Bool *process_bottlePresent;
CB_Mem_Bool *process_load;
CB_Mem_Bool *process_evacuate;
CB_Mem_Bool *process_convoy;
CB_Mem_Bool *process_pump1;
CB_Mem_Bool *process_pump2;
CB_Mem_Bool *process_valve1;
CB_Mem_Bool *process_valve2;
CB_Mem_Bool *process_valve3;
CB_Mem_Bool *process_valve4;
CB_Mem_Bool *process_loSpeedAgitator;
CB_Mem_Bool *process_hiSpeedAgitator;
CB_Mem_Bool *process_valve5;

/**************************** Variables *****************************/



/************************ Components offsets ************************/

static CB_Offset bottling_line__process_offset_master;
static CB_Offset bottling_line__process_offset_tanks;
static CB_Offset bottling_line__process_offset_preparation;
static CB_Offset bottling_line__process_offset_conveyor;
static CB_Offset bottling_line__process_offset_manageFunctionalRq;
static CB_Offset bottling_line__process_offset__end = {0, 0, 0, 0};


/********************* Initialization function **********************/

int _bottling_line__process_init(void)
{
	CB_Object __start = self;
	self.Bool+=24;

	/*initialize child master (bottling_line.master):*/
	self_num++;
	bottling_line__process_offset_master.Bool = self.Bool - __start.Bool;
	bottling_line__process_offset_master.Int = self.Int - __start.Int;
	bottling_line__process_offset_master.Float = self.Float - __start.Float;
	bottling_line__process_offset_master.Char = self.Char - __start.Char;
	master_startCyclePB = process_startCyclePB;
	master_initPB = process_initPB;
	master_preparationPB = process_preparationPB;
	master_productionPB = process_productionPB;
	master_closingPB = process_closingPB;
	master_initEnd = __start.Bool+1; /*process__cn_23*/
	master_preparationEnd = __start.Bool+2; /*process__cn_22*/
	master_closingEnd = __start.Bool+3; /*process__cn_21*/
	master_lowLevel3 = process_lowLevel3;
	master_initializationRqst = __start.Bool+0; /*process__cn_24*/
	master_preparationRqst = __start.Bool+7; /*process__cn_17*/
	master_productionRqst = __start.Bool+4; /*process__cn_20*/
	master_closingRqst = __start.Bool+5; /*process__cn_19*/
	master_masterInStandBy = __start.Bool+6; /*process__cn_18*/
	master_productionWaiting = __start.Bool+8; /*process__cn_16*/
	_bottling_line__master_init();

	/*initialize child tanks (bottling_line.tanks_management):*/
	self_num++;
	bottling_line__process_offset_tanks.Bool = self.Bool - __start.Bool;
	bottling_line__process_offset_tanks.Int = self.Int - __start.Int;
	bottling_line__process_offset_tanks.Float = self.Float - __start.Float;
	bottling_line__process_offset_tanks.Char = self.Char - __start.Char;
	tanks_management_productionRequest = __start.Bool+4; /*process__cn_20*/
	tanks_management_closingRequest = __start.Bool+5; /*process__cn_19*/
	tanks_management_masterInStandBy = __start.Bool+6; /*process__cn_18*/
	tanks_management_highLevel1 = process_highLevel1;
	tanks_management_highLevel2 = process_highLevel2;
	tanks_management_highLevel3 = process_highLevel3;
	tanks_management_lowLevel1 = process_lowLevel1;
	tanks_management_lowLevel2 = process_lowLevel2;
	tanks_management_lowLevel3 = process_lowLevel3;
	tanks_management_pump1 = __start.Bool+16; /*process__cn_8*/
	tanks_management_pump2 = __start.Bool+17; /*process__cn_7*/
	tanks_management_valve1 = __start.Bool+18; /*process__cn_6*/
	tanks_management_valve2 = __start.Bool+19; /*process__cn_5*/
	tanks_management_valve3 = __start.Bool+20; /*process__cn_4*/
	tanks_management_valve4 = __start.Bool+21; /*process__cn_3*/
	tanks_management_lowSpeedAgitator = __start.Bool+22; /*process__cn_2*/
	tanks_management_highSpeedAgitator = __start.Bool+23; /*process__cn_1*/
	tanks_management_closingEnd = __start.Bool+3; /*process__cn_21*/
	_bottling_line__tanks_management_init();

	/*initialize child preparation (bottling_line.preparation):*/
	self_num++;
	bottling_line__process_offset_preparation.Bool = self.Bool - __start.Bool;
	bottling_line__process_offset_preparation.Int = self.Int - __start.Int;
	bottling_line__process_offset_preparation.Float = self.Float - __start.Float;
	bottling_line__process_offset_preparation.Char = self.Char - __start.Char;
	preparation_preparationRequest = __start.Bool+7; /*process__cn_17*/
	preparation_productionWaiting = __start.Bool+8; /*process__cn_16*/
	preparation_highLevel1 = process_highLevel1;
	preparation_highLevel2 = process_highLevel2;
	preparation_highLevel3 = process_highLevel3;
	preparation_preparationValve1 = __start.Bool+9; /*process__cn_15*/
	preparation_preparationValve2 = __start.Bool+10; /*process__cn_14*/
	preparation_preparationValve3 = __start.Bool+11; /*process__cn_13*/
	preparation_preparationValve4 = __start.Bool+12; /*process__cn_12*/
	preparation_preparationPump1 = __start.Bool+13; /*process__cn_11*/
	preparation_preparationPump2 = __start.Bool+14; /*process__cn_10*/
	preparation_preparationAgit = __start.Bool+15; /*process__cn_9*/
	preparation_preparationEnd = __start.Bool+2; /*process__cn_22*/
	_bottling_line__preparation_init();

	/*initialize child conveyor (bottling_line.conveyor_management):*/
	self_num++;
	bottling_line__process_offset_conveyor.Bool = self.Bool - __start.Bool;
	bottling_line__process_offset_conveyor.Int = self.Int - __start.Int;
	bottling_line__process_offset_conveyor.Float = self.Float - __start.Float;
	bottling_line__process_offset_conveyor.Char = self.Char - __start.Char;
	conveyor_management_productionRequest = __start.Bool+4; /*process__cn_20*/
	conveyor_management_pulseGenerator = process_pulseGenerator;
	conveyor_management_bottleFilled = process_bottleFilled;
	conveyor_management_bottlePresent = process_bottlePresent;
	conveyor_management_load = process_load;
	conveyor_management_evacuate = process_evacuate;
	conveyor_management_convoy = process_convoy;
	conveyor_management_valve5 = process_valve5;
	_bottling_line__conveyor_management_init();

	/*initialize child manageFunctionalRq (bottling_line.requests_management):*/
	self_num++;
	bottling_line__process_offset_manageFunctionalRq.Bool = self.Bool - __start.Bool;
	bottling_line__process_offset_manageFunctionalRq.Int = self.Int - __start.Int;
	bottling_line__process_offset_manageFunctionalRq.Float = self.Float - __start.Float;
	bottling_line__process_offset_manageFunctionalRq.Char = self.Char - __start.Char;
	requests_management_preparationValve1 = __start.Bool+9; /*process__cn_15*/
	requests_management_preparationValve2 = __start.Bool+10; /*process__cn_14*/
	requests_management_preparationValve3 = __start.Bool+11; /*process__cn_13*/
	requests_management_preparationValve4 = __start.Bool+12; /*process__cn_12*/
	requests_management_preparationPump1 = __start.Bool+13; /*process__cn_11*/
	requests_management_preparationPump2 = __start.Bool+14; /*process__cn_10*/
	requests_management_preparationAgitator = __start.Bool+15; /*process__cn_9*/
	requests_management_productionPump1 = __start.Bool+16; /*process__cn_8*/
	requests_management_productionPump2 = __start.Bool+17; /*process__cn_7*/
	requests_management_productionValve1 = __start.Bool+18; /*process__cn_6*/
	requests_management_productionValve2 = __start.Bool+19; /*process__cn_5*/
	requests_management_productionValve3 = __start.Bool+20; /*process__cn_4*/
	requests_management_productionValve4 = __start.Bool+21; /*process__cn_3*/
	requests_management_productionLSAgitator = __start.Bool+22; /*process__cn_2*/
	requests_management_productionHSAgitator = __start.Bool+23; /*process__cn_1*/
	requests_management_pump1 = process_pump1;
	requests_management_pump2 = process_pump2;
	requests_management_valve1 = process_valve1;
	requests_management_valve2 = process_valve2;
	requests_management_valve3 = process_valve3;
	requests_management_valve4 = process_valve4;
	requests_management_loSpeedAgit = process_loSpeedAgitator;
	requests_management_hiSpeedAgit = process_hiSpeedAgitator;
	_bottling_line__requests_management_init();

	bottling_line__process_offset__end.Bool = self.Bool - __start.Bool;
	bottling_line__process_offset__end.Int = self.Int - __start.Int;
	bottling_line__process_offset__end.Float = self.Float - __start.Float;
	bottling_line__process_offset__end.Char = self.Char - __start.Char;

	return 0;
}


/************************ Behavior function *************************/

int bottling_line__process(void)
{
	CB_Object __start = self;
	int __ret;
	if (exec_mac_node(self_num)) {

		/*********************** Internals variables ************************/

																																																
		/********************* Pre-conditions execution *********************/

		/*no Pre-conditions*/

		/************************ Behavior execution ************************/

		{
			self.Bool = __start.Bool + bottling_line__process_offset_master.Bool;
			self.Int = __start.Int + bottling_line__process_offset_master.Int;
			self.Float = __start.Float + bottling_line__process_offset_master.Float;
			self.Char = __start.Char + bottling_line__process_offset_master.Char;

			/************************* master execution *************************/

			self_num++;
			if (master__num != self_num) {
				master__num = self_num;
				master_startCyclePB = process_startCyclePB;
				master_initPB = process_initPB;
				master_preparationPB = process_preparationPB;
				master_productionPB = process_productionPB;
				master_closingPB = process_closingPB;
				master_initEnd = __start.Bool+1; /*process__cn_23*/
				master_preparationEnd = __start.Bool+2; /*process__cn_22*/
				master_closingEnd = __start.Bool+3; /*process__cn_21*/
				master_lowLevel3 = process_lowLevel3;
				master_initializationRqst = __start.Bool+0; /*process__cn_24*/
				master_preparationRqst = __start.Bool+7; /*process__cn_17*/
				master_productionRqst = __start.Bool+4; /*process__cn_20*/
				master_closingRqst = __start.Bool+5; /*process__cn_19*/
				master_masterInStandBy = __start.Bool+6; /*process__cn_18*/
				master_productionWaiting = __start.Bool+8; /*process__cn_16*/
			}
			__ret = bottling_line__master();
			if (__ret != 0) {
				return __ret; /*child execution failure*/
			}

			/************************* tanks execution **************************/

			self_num++;
			if (tanks_management__num != self_num) {
				tanks_management__num = self_num;
				tanks_management_productionRequest = __start.Bool+4; /*process__cn_20*/
				tanks_management_closingRequest = __start.Bool+5; /*process__cn_19*/
				tanks_management_masterInStandBy = __start.Bool+6; /*process__cn_18*/
				tanks_management_highLevel1 = process_highLevel1;
				tanks_management_highLevel2 = process_highLevel2;
				tanks_management_highLevel3 = process_highLevel3;
				tanks_management_lowLevel1 = process_lowLevel1;
				tanks_management_lowLevel2 = process_lowLevel2;
				tanks_management_lowLevel3 = process_lowLevel3;
				tanks_management_pump1 = __start.Bool+16; /*process__cn_8*/
				tanks_management_pump2 = __start.Bool+17; /*process__cn_7*/
				tanks_management_valve1 = __start.Bool+18; /*process__cn_6*/
				tanks_management_valve2 = __start.Bool+19; /*process__cn_5*/
				tanks_management_valve3 = __start.Bool+20; /*process__cn_4*/
				tanks_management_valve4 = __start.Bool+21; /*process__cn_3*/
				tanks_management_lowSpeedAgitator = __start.Bool+22; /*process__cn_2*/
				tanks_management_highSpeedAgitator = __start.Bool+23; /*process__cn_1*/
				tanks_management_closingEnd = __start.Bool+3; /*process__cn_21*/
			}
			__ret = bottling_line__tanks_management();
			if (__ret != 0) {
				return __ret; /*child execution failure*/
			}

			/********************** preparation execution ***********************/

			self_num++;
			if (preparation__num != self_num) {
				preparation__num = self_num;
				preparation_preparationRequest = __start.Bool+7; /*process__cn_17*/
				preparation_productionWaiting = __start.Bool+8; /*process__cn_16*/
				preparation_highLevel1 = process_highLevel1;
				preparation_highLevel2 = process_highLevel2;
				preparation_highLevel3 = process_highLevel3;
				preparation_preparationValve1 = __start.Bool+9; /*process__cn_15*/
				preparation_preparationValve2 = __start.Bool+10; /*process__cn_14*/
				preparation_preparationValve3 = __start.Bool+11; /*process__cn_13*/
				preparation_preparationValve4 = __start.Bool+12; /*process__cn_12*/
				preparation_preparationPump1 = __start.Bool+13; /*process__cn_11*/
				preparation_preparationPump2 = __start.Bool+14; /*process__cn_10*/
				preparation_preparationAgit = __start.Bool+15; /*process__cn_9*/
				preparation_preparationEnd = __start.Bool+2; /*process__cn_22*/
			}
			__ret = bottling_line__preparation();
			if (__ret != 0) {
				return __ret; /*child execution failure*/
			}

			/************************ conveyor execution ************************/

			self_num++;
			if (conveyor_management__num != self_num) {
				conveyor_management__num = self_num;
				conveyor_management_productionRequest = __start.Bool+4; /*process__cn_20*/
				conveyor_management_pulseGenerator = process_pulseGenerator;
				conveyor_management_bottleFilled = process_bottleFilled;
				conveyor_management_bottlePresent = process_bottlePresent;
				conveyor_management_load = process_load;
				conveyor_management_evacuate = process_evacuate;
				conveyor_management_convoy = process_convoy;
				conveyor_management_valve5 = process_valve5;
			}
			__ret = bottling_line__conveyor_management();
			if (__ret != 0) {
				return __ret; /*child execution failure*/
			}

			/******************* manageFunctionalRq execution *******************/

			self_num++;
			if (requests_management__num != self_num) {
				requests_management__num = self_num;
				requests_management_preparationValve1 = __start.Bool+9; /*process__cn_15*/
				requests_management_preparationValve2 = __start.Bool+10; /*process__cn_14*/
				requests_management_preparationValve3 = __start.Bool+11; /*process__cn_13*/
				requests_management_preparationValve4 = __start.Bool+12; /*process__cn_12*/
				requests_management_preparationPump1 = __start.Bool+13; /*process__cn_11*/
				requests_management_preparationPump2 = __start.Bool+14; /*process__cn_10*/
				requests_management_preparationAgitator = __start.Bool+15; /*process__cn_9*/
				requests_management_productionPump1 = __start.Bool+16; /*process__cn_8*/
				requests_management_productionPump2 = __start.Bool+17; /*process__cn_7*/
				requests_management_productionValve1 = __start.Bool+18; /*process__cn_6*/
				requests_management_productionValve2 = __start.Bool+19; /*process__cn_5*/
				requests_management_productionValve3 = __start.Bool+20; /*process__cn_4*/
				requests_management_productionValve4 = __start.Bool+21; /*process__cn_3*/
				requests_management_productionLSAgitator = __start.Bool+22; /*process__cn_2*/
				requests_management_productionHSAgitator = __start.Bool+23; /*process__cn_1*/
				requests_management_pump1 = process_pump1;
				requests_management_pump2 = process_pump2;
				requests_management_valve1 = process_valve1;
				requests_management_valve2 = process_valve2;
				requests_management_valve3 = process_valve3;
				requests_management_valve4 = process_valve4;
				requests_management_loSpeedAgit = process_loSpeedAgitator;
				requests_management_hiSpeedAgit = process_hiSpeedAgitator;
			}
			__ret = bottling_line__requests_management();
			if (__ret != 0) {
				return __ret; /*child execution failure*/
			}

		}


		/******************** Post-conditions execution *********************/

		/*no Post-conditions*/
	}

	/*************************** self update ****************************/

	self.Bool = __start.Bool + bottling_line__process_offset__end.Bool;
	self.Int = __start.Int + bottling_line__process_offset__end.Int;
	self.Float = __start.Float + bottling_line__process_offset__end.Float;
	self.Char = __start.Char + bottling_line__process_offset__end.Char;

	return 0;
}

