/*2023-10-03T11:13:21-01:00*/

/********************************************************************
 * axle.h
 * 
 * generated by: plcgen 3.1.391
 ********************************************************************/

#ifndef _EQUIPMENT_LIBRARY__AXLE_H
#define _EQUIPMENT_LIBRARY__AXLE_H


/********************** Variable declarations ***********************/

extern CB_Index axle__num;
extern CB_Mem_Float *axle_speed;
extern CB_Mem_Float *axle_positionTranslat;
extern CB_Mem_Float *axle_percentTranslat;
extern CB_Mem_Float *axle_incTranslat;
extern CB_Mem_Bool *axle_firstCycle;
extern CB_Mem_Float *axle_nbCyclePerSec;
extern CB_Mem_Float *axle_initTranslat;
extern CB_Mem_Float *axle_maxTranslat;
extern CB_Mem_Float *axle_minTranslat;
extern CB_Mem_Bool *axle_d_locking;
extern CB_Mem_Bool *axle_v_d_locking;

/********************** Function declarations ***********************/

extern int _equipment_library__axle_init(void);
extern int equipment_library__axle(void);

#endif /*_EQUIPMENT_LIBRARY__AXLE_H*/
