/*2023-10-03T11:13:56-01:00*/

/********************************************************************
 * shuttle.h
 * 
 * generated by: plcgen 3.1.391
 ********************************************************************/

#ifndef _TRI_CHAIN__SHUTTLE_H
#define _TRI_CHAIN__SHUTTLE_H


/********************** Variable declarations ***********************/

extern CB_Index shuttle__num;
extern CB_Mem_Float *shuttle_speedX;
extern CB_Mem_Float *shuttle_speedY;
extern CB_Mem_Int *shuttle_status_act_prod;
extern CB_Mem_Float *shuttle_m11;
extern CB_Mem_Float *shuttle_m12;
extern CB_Mem_Float *shuttle_m13;
extern CB_Mem_Float *shuttle_m14;
extern CB_Mem_Float *shuttle_m21;
extern CB_Mem_Float *shuttle_m22;
extern CB_Mem_Float *shuttle_m23;
extern CB_Mem_Float *shuttle_m24;
extern CB_Mem_Float *shuttle_m31;
extern CB_Mem_Float *shuttle_m32;
extern CB_Mem_Float *shuttle_m33;
extern CB_Mem_Float *shuttle_m34;
extern CB_Mem_Float *shuttle_m41;
extern CB_Mem_Float *shuttle_m42;
extern CB_Mem_Float *shuttle_m43;
extern CB_Mem_Float *shuttle_m44;
extern CB_Mem_Float *shuttle_px;
extern CB_Mem_Float *shuttle_py;
extern CB_Mem_Float *shuttle_pz;
extern CB_Mem_Float *shuttle_dx;
extern CB_Mem_Float *shuttle_dy;
extern CB_Mem_Float *shuttle_dz;
extern CB_Mem_Float *shuttle_sProdX;
extern CB_Mem_Float *shuttle_sProdY;
extern CB_Mem_Bool *shuttle_d_locking;
extern CB_Mem_Bool *shuttle_v_d_locking;

/********************** Function declarations ***********************/

extern int _tri_chain__shuttle_init(void);
extern int tri_chain__shuttle(void);

/************************** Access macros ***************************/

#define mx_acces_tri_chain__shuttle__status_act_prod Int[0].CB_current_value
#define mx_acces_tri_chain__shuttle__m11 Float[0].CB_current_value
#define mx_acces_tri_chain__shuttle__m12 Float[1].CB_current_value
#define mx_acces_tri_chain__shuttle__m13 Float[2].CB_current_value
#define mx_acces_tri_chain__shuttle__m14 Float[3].CB_current_value
#define mx_acces_tri_chain__shuttle__m21 Float[4].CB_current_value
#define mx_acces_tri_chain__shuttle__m22 Float[5].CB_current_value
#define mx_acces_tri_chain__shuttle__m23 Float[6].CB_current_value
#define mx_acces_tri_chain__shuttle__m24 Float[7].CB_current_value
#define mx_acces_tri_chain__shuttle__m31 Float[8].CB_current_value
#define mx_acces_tri_chain__shuttle__m32 Float[9].CB_current_value
#define mx_acces_tri_chain__shuttle__m33 Float[10].CB_current_value
#define mx_acces_tri_chain__shuttle__m34 Float[11].CB_current_value
#define mx_acces_tri_chain__shuttle__m41 Float[12].CB_current_value
#define mx_acces_tri_chain__shuttle__m42 Float[13].CB_current_value
#define mx_acces_tri_chain__shuttle__m43 Float[14].CB_current_value
#define mx_acces_tri_chain__shuttle__m44 Float[15].CB_current_value
#define mx_acces_tri_chain__shuttle__px Float[16].CB_current_value
#define mx_acces_tri_chain__shuttle__py Float[17].CB_current_value
#define mx_acces_tri_chain__shuttle__pz Float[18].CB_current_value
#define mx_acces_tri_chain__shuttle__dx Float[19].CB_current_value
#define mx_acces_tri_chain__shuttle__dy Float[20].CB_current_value
#define mx_acces_tri_chain__shuttle__dz Float[21].CB_current_value
#define mx_acces_tri_chain__shuttle__sProdX Float[22].CB_current_value
#define mx_acces_tri_chain__shuttle__sProdY Float[23].CB_current_value
#define mx_acces_tri_chain__shuttle__d_locking Bool[0].CB_current_value
#define mx_acces_tri_chain__shuttle__v_d_locking Bool[1].CB_current_value

#endif /*_TRI_CHAIN__SHUTTLE_H*/
