/*2023-10-03T11:13:21-01:00*/

/********************************************************************
 * maintained_button.c
 * 
 * generated by: plcgen 3.1.391
 ********************************************************************/

#include "cb_comp.h"
#include "iec_1131.h"

#include "maintained_button.h"


/**************************** Variables *****************************/

CB_Index maintained_button__num = 0;
CB_Mem_Bool *maintained_button_pb;
CB_Mem_Bool *maintained_button_action;
CB_Mem_Bool *maintained_button_PBLogic;

/**************************** Variables *****************************/

#define pb (maintained_button_pb->CB_current_value)
#define action (maintained_button_action->CB_current_value)
#define PBLogic (maintained_button_PBLogic->CB_current_value)


/************************ Components offsets ************************/


/********************* Initialization function **********************/

int _equipment_library__maintained_button_init(void)
{
	(self.Bool+1)->CB_current_value = 1; /*PBLogic*/
	self.Bool+=2;


	return 0;
}


/************************ Behavior function *************************/

int equipment_library__maintained_button(void)
{
	if (exec_term_node(self_num)) {

		/*********************** Internals variables ************************/

		maintained_button_action = self.Bool+0;
		maintained_button_PBLogic = self.Bool+1;

		/********************* Pre-conditions execution *********************/

		/*no Pre-conditions*/

		/************************ Behavior execution ************************/

		{
			pb = action ^ !PBLogic;
		}

		CB_post_bool(maintained_button_pb);

		/******************** Post-conditions execution *********************/

		/*no Post-conditions*/
	}

	/*************************** self update ****************************/

	self.Bool += 2;

	return 0;
}

