/*2023-10-03T11:12:44-01:00*/

/********************************************************************
 * cb_r_trig.h
 * 
 * generated by: plcgen 3.1.391
 ********************************************************************/

#ifndef _TIMERS_COUNTERS__CB_R_TRIG_H
#define _TIMERS_COUNTERS__CB_R_TRIG_H


/********************** Variable declarations ***********************/

extern CB_Index cb_r_trig__num;
extern CB_Mem_Bool *cb_r_trig_IN;
extern CB_Mem_Bool *cb_r_trig_Q0;
extern CB_Mem_Bool *cb_r_trig_Mem;

/********************** Function declarations ***********************/

extern int _timers_counters__cb_r_trig_init(void);
extern int timers_counters__cb_r_trig(void);

#endif /*_TIMERS_COUNTERS__CB_R_TRIG_H*/
