/*2023-10-03T11:13:50-01:00*/

/********************************************************************
 * service_side.h
 * 
 * generated by: plcgen 3.1.391
 ********************************************************************/

#ifndef _TNI_TRAIN__SERVICE_SIDE_H
#define _TNI_TRAIN__SERVICE_SIDE_H


/********************** Variable declarations ***********************/

extern CB_Index service_side__num;
extern CB_Mem_Bool *service_side_rightServiceSide;
extern CB_Mem_Bool *service_side_leftServiceSide;
extern CB_Mem_Bool *service_side_button;

/********************** Function declarations ***********************/

extern int _tni_train__service_side_init(void);
extern int tni_train__service_side(void);

#endif /*_TNI_TRAIN__SERVICE_SIDE_H*/
