/*2024-04-12T14:05:56-01:00*/

/********************************************************************
 * mode.h
 * 
 * generated by: plcgen 3.1.391
 ********************************************************************/

#ifndef _COPIE_BATCH__MODE_H
#define _COPIE_BATCH__MODE_H


/********************** Variable declarations ***********************/

extern CB_Index mode__num;
extern CB_Mem_Bool *mode_powerUp;
extern CB_Mem_Bool *mode_emergencyStop;
extern CB_Mem_Bool *mode_manualSwitch;
extern CB_Mem_Bool *mode_autoSwitch;
extern CB_Mem_Bool *mode_startCyclePB;
extern CB_Mem_Bool *mode_endCyclePB;
extern CB_Mem_Bool *mode_acknowledgePB;
extern CB_Mem_Bool *mode_cycleEnd;
extern CB_Mem_Bool *mode_generalFault;
extern CB_Mem_Bool *mode_live;
extern CB_Mem_Bool *mode_autoMode;
extern CB_Mem_Bool *mode_manualMode;
extern CB_Mem_Bool *mode_cycleInProgress;
extern CB_Mem_Bool *mode_endCycleRequest;
extern CB_Mem_Bool *mode_emergencyStopState;

/********************** Function declarations ***********************/

extern int _copie_batch__mode_init(void);
extern int copie_batch__mode(void);

#endif /*_COPIE_BATCH__MODE_H*/
