/*2023-10-03T11:13:37-01:00*/

/********************************************************************
 * cmd_agitator_2speed.c
 * 
 * generated by: plcgen 3.1.391
 ********************************************************************/

#include "cb_comp.h"
#include "iec_1131.h"


/********************************************************************
 *                  Inner 'actuator' declarations                   *
 ********************************************************************/


/********************** Variable declarations ***********************/

static CB_Index actuator__num;
extern CB_Mem_Bool *_i_cmd_agitator_2speed__actuator_autoMode;
extern CB_Mem_Bool *_i_cmd_agitator_2speed__actuator_manualMode;
extern CB_Mem_Bool *_i_cmd_agitator_2speed__actuator_autoHSCmd;
extern CB_Mem_Bool *_i_cmd_agitator_2speed__actuator_autoLSCmd;
extern CB_Mem_Bool *_i_cmd_agitator_2speed__actuator_highSpeedPB;
extern CB_Mem_Bool *_i_cmd_agitator_2speed__actuator_lowSpeedPB;
extern CB_Mem_Bool *_i_cmd_agitator_2speed__actuator_stopPB;
extern CB_Mem_Bool *_i_cmd_agitator_2speed__actuator_generalFault;
extern CB_Mem_Bool *_i_cmd_agitator_2speed__actuator_highSpeedCmd;
extern CB_Mem_Bool *_i_cmd_agitator_2speed__actuator_lowSpeedCmd;

/********************** Function declarations ***********************/

static int _cmd_equipment_library__actuator_init(void);
static int cmd_equipment_library__actuator(void);

/********************************************************************
 *                   Inner 'faults' declarations                    *
 ********************************************************************/


/********************** Variable declarations ***********************/

static CB_Index faults__num;
extern CB_Mem_Bool *_i_cmd_agitator_2speed__faults_highSpeedCmd;
extern CB_Mem_Bool *_i_cmd_agitator_2speed__faults_lowSpeedCmd;
extern CB_Mem_Bool *_i_cmd_agitator_2speed__faults_highSpeedFB;
extern CB_Mem_Bool *_i_cmd_agitator_2speed__faults_lowSpeedFB;
extern CB_Mem_Bool *_i_cmd_agitator_2speed__faults_thermalFB;
extern CB_Mem_Bool *_i_cmd_agitator_2speed__faults_acknowledgePB;
extern CB_Mem_Bool *_i_cmd_agitator_2speed__faults_generalFault;
extern CB_Mem_Bool *_i_cmd_agitator_2speed__faults_thermalFault;
extern CB_Mem_Bool *_i_cmd_agitator_2speed__faults_highSpeedFBFault;
extern CB_Mem_Bool *_i_cmd_agitator_2speed__faults_lowSpeedFBFault;

/********************** Function declarations ***********************/

static int _cmd_equipment_library__faults_init(void);
static int cmd_equipment_library__faults(void);

/********************************************************************
 *                 Inner 'actuator' implementation                  *
 ********************************************************************/



/**************************** Variables *****************************/

static CB_Index actuator__num = 0;
CB_Mem_Bool *_i_cmd_agitator_2speed__actuator_autoMode;
CB_Mem_Bool *_i_cmd_agitator_2speed__actuator_manualMode;
CB_Mem_Bool *_i_cmd_agitator_2speed__actuator_autoHSCmd;
CB_Mem_Bool *_i_cmd_agitator_2speed__actuator_autoLSCmd;
CB_Mem_Bool *_i_cmd_agitator_2speed__actuator_highSpeedPB;
CB_Mem_Bool *_i_cmd_agitator_2speed__actuator_lowSpeedPB;
CB_Mem_Bool *_i_cmd_agitator_2speed__actuator_stopPB;
CB_Mem_Bool *_i_cmd_agitator_2speed__actuator_generalFault;
CB_Mem_Bool *_i_cmd_agitator_2speed__actuator_highSpeedCmd;
CB_Mem_Bool *_i_cmd_agitator_2speed__actuator_lowSpeedCmd;

/**************************** Variables *****************************/

#define autoMode (_i_cmd_agitator_2speed__actuator_autoMode->CB_current_value)
#define manualMode (_i_cmd_agitator_2speed__actuator_manualMode->CB_current_value)
#define autoHSCmd (_i_cmd_agitator_2speed__actuator_autoHSCmd->CB_current_value)
#define autoLSCmd (_i_cmd_agitator_2speed__actuator_autoLSCmd->CB_current_value)
#define highSpeedPB (_i_cmd_agitator_2speed__actuator_highSpeedPB->CB_current_value)
#define lowSpeedPB (_i_cmd_agitator_2speed__actuator_lowSpeedPB->CB_current_value)
#define stopPB (_i_cmd_agitator_2speed__actuator_stopPB->CB_current_value)
#define generalFault (_i_cmd_agitator_2speed__actuator_generalFault->CB_current_value)
#define highSpeedCmd (_i_cmd_agitator_2speed__actuator_highSpeedCmd->CB_current_value)
#define lowSpeedCmd (_i_cmd_agitator_2speed__actuator_lowSpeedCmd->CB_current_value)


/************************ Components offsets ************************/


/********************* Initialization function **********************/

static int _cmd_equipment_library__actuator_init(void)
{


	return 0;
}


/************************ Behavior function *************************/

static int cmd_equipment_library__actuator(void)
{
	if (exec_term_node(self_num)) {

		/*********************** Internals variables ************************/


		/********************* Pre-conditions execution *********************/

		/*no Pre-conditions*/

		/************************ Behavior execution ************************/

		{
			unsigned char _2;
			unsigned char _9;
			_2 = manualMode;
			highSpeedCmd = ((autoMode && autoHSCmd) || ((((_2 && highSpeedPB) || (_2 && highSpeedCmd)) && !lowSpeedPB) && !stopPB)) && !generalFault;
			_9 = manualMode;
			lowSpeedCmd = ((autoMode && autoLSCmd) || ((((_9 && lowSpeedPB) || (_9 && lowSpeedCmd)) && !highSpeedPB) && !stopPB)) && !generalFault;
		}

		CB_post_bool(_i_cmd_agitator_2speed__actuator_highSpeedCmd);
		CB_post_bool(_i_cmd_agitator_2speed__actuator_lowSpeedCmd);

		/******************** Post-conditions execution *********************/

		/*no Post-conditions*/
	}

	/*************************** self update ****************************/


	return 0;
}

#undef autoMode
#undef manualMode
#undef autoHSCmd
#undef autoLSCmd
#undef highSpeedPB
#undef lowSpeedPB
#undef stopPB
#undef generalFault
#undef highSpeedCmd
#undef lowSpeedCmd

/********************************************************************
 *                  Inner 'faults' implementation                   *
 ********************************************************************/

#include "timers_counters/functional/cb_ton/cb_ton.h"


/**************************** Variables *****************************/

static CB_Index faults__num = 0;
CB_Mem_Bool *_i_cmd_agitator_2speed__faults_highSpeedCmd;
CB_Mem_Bool *_i_cmd_agitator_2speed__faults_lowSpeedCmd;
CB_Mem_Bool *_i_cmd_agitator_2speed__faults_highSpeedFB;
CB_Mem_Bool *_i_cmd_agitator_2speed__faults_lowSpeedFB;
CB_Mem_Bool *_i_cmd_agitator_2speed__faults_thermalFB;
CB_Mem_Bool *_i_cmd_agitator_2speed__faults_acknowledgePB;
CB_Mem_Bool *_i_cmd_agitator_2speed__faults_generalFault;
CB_Mem_Bool *_i_cmd_agitator_2speed__faults_thermalFault;
CB_Mem_Bool *_i_cmd_agitator_2speed__faults_highSpeedFBFault;
CB_Mem_Bool *_i_cmd_agitator_2speed__faults_lowSpeedFBFault;
CB_Mem_Bool *_i_cmd_agitator_2speed__faults_TON_HI_IN;
CB_Mem_Int *_i_cmd_agitator_2speed__faults_TON_HI_PT;
CB_Mem_Bool *_i_cmd_agitator_2speed__faults_TON_HI_Q0;
CB_Mem_Int *_i_cmd_agitator_2speed__faults_TON_HI_CV;
CB_Mem_Bool *_i_cmd_agitator_2speed__faults_TON_LO_IN;
CB_Mem_Int *_i_cmd_agitator_2speed__faults_TON_LO_PT;
CB_Mem_Bool *_i_cmd_agitator_2speed__faults_TON_LO_Q0;
CB_Mem_Int *_i_cmd_agitator_2speed__faults_TON_LO_CV;

/**************************** Variables *****************************/

#define highSpeedCmd (_i_cmd_agitator_2speed__faults_highSpeedCmd->CB_current_value)
#define lowSpeedCmd (_i_cmd_agitator_2speed__faults_lowSpeedCmd->CB_current_value)
#define highSpeedFB (_i_cmd_agitator_2speed__faults_highSpeedFB->CB_current_value)
#define lowSpeedFB (_i_cmd_agitator_2speed__faults_lowSpeedFB->CB_current_value)
#define thermalFB (_i_cmd_agitator_2speed__faults_thermalFB->CB_current_value)
#define acknowledgePB (_i_cmd_agitator_2speed__faults_acknowledgePB->CB_current_value)
#define generalFault (_i_cmd_agitator_2speed__faults_generalFault->CB_current_value)
#define thermalFault (_i_cmd_agitator_2speed__faults_thermalFault->CB_current_value)
#define highSpeedFBFault (_i_cmd_agitator_2speed__faults_highSpeedFBFault->CB_current_value)
#define lowSpeedFBFault (_i_cmd_agitator_2speed__faults_lowSpeedFBFault->CB_current_value)
#define TON_HI_IN (_i_cmd_agitator_2speed__faults_TON_HI_IN->CB_current_value)
#define TON_HI_PT(i) (_i_cmd_agitator_2speed__faults_TON_HI_PT[i+1].CB_current_value)
#define TON_HI_Q0 (_i_cmd_agitator_2speed__faults_TON_HI_Q0->CB_current_value)
#define TON_HI_CV(i) (_i_cmd_agitator_2speed__faults_TON_HI_CV[i+1].CB_current_value)
#define TON_LO_IN (_i_cmd_agitator_2speed__faults_TON_LO_IN->CB_current_value)
#define TON_LO_PT(i) (_i_cmd_agitator_2speed__faults_TON_LO_PT[i+1].CB_current_value)
#define TON_LO_Q0 (_i_cmd_agitator_2speed__faults_TON_LO_Q0->CB_current_value)
#define TON_LO_CV(i) (_i_cmd_agitator_2speed__faults_TON_LO_CV[i+1].CB_current_value)


/************************ Components offsets ************************/

static CB_Index cmd_equipment_library__faults_dnum_TON_HI;
static CB_Index cmd_equipment_library__faults_dnum_TON_LO;
static CB_Index cmd_equipment_library__faults_dnum__end;

static CB_Offset cmd_equipment_library__faults_offset_TON_HI;
static CB_Offset cmd_equipment_library__faults_offset_TON_LO;
static CB_Offset cmd_equipment_library__faults_offset__end = {0, 0, 0, 0};


/********************* Initialization function **********************/

static int _cmd_equipment_library__faults_init(void)
{
	CB_Index __my_num = self_num;
	CB_Object __start = self;
	self.Bool+=7;
	self.Int+=16;

	/*initialize child TON_HI (timers_counters.cb_ton):*/
	self_num++;
	cmd_equipment_library__faults_dnum_TON_HI = self_num - __my_num;
	cmd_equipment_library__faults_offset_TON_HI.Bool = self.Bool - __start.Bool;
	cmd_equipment_library__faults_offset_TON_HI.Int = self.Int - __start.Int;
	cmd_equipment_library__faults_offset_TON_HI.Float = self.Float - __start.Float;
	cmd_equipment_library__faults_offset_TON_HI.Char = self.Char - __start.Char;
	cb_ton_IN = __start.Bool+3; /*TON_HI_IN*/
	cb_ton_PT = __start.Int+0; /*TON_HI_PT*/
	cb_ton_Q0 = __start.Bool+4; /*TON_HI_Q0*/
	cb_ton_CV = __start.Int+4; /*TON_HI_CV*/
	_timers_counters__cb_ton_init();

	/*initialize child TON_LO (timers_counters.cb_ton):*/
	self_num++;
	cmd_equipment_library__faults_dnum_TON_LO = self_num - __my_num;
	cmd_equipment_library__faults_offset_TON_LO.Bool = self.Bool - __start.Bool;
	cmd_equipment_library__faults_offset_TON_LO.Int = self.Int - __start.Int;
	cmd_equipment_library__faults_offset_TON_LO.Float = self.Float - __start.Float;
	cmd_equipment_library__faults_offset_TON_LO.Char = self.Char - __start.Char;
	cb_ton_IN = __start.Bool+5; /*TON_LO_IN*/
	cb_ton_PT = __start.Int+8; /*TON_LO_PT*/
	cb_ton_Q0 = __start.Bool+6; /*TON_LO_Q0*/
	cb_ton_CV = __start.Int+12; /*TON_LO_CV*/
	_timers_counters__cb_ton_init();

	cmd_equipment_library__faults_dnum__end = self_num - __my_num;
	cmd_equipment_library__faults_offset__end.Bool = self.Bool - __start.Bool;
	cmd_equipment_library__faults_offset__end.Int = self.Int - __start.Int;
	cmd_equipment_library__faults_offset__end.Float = self.Float - __start.Float;
	cmd_equipment_library__faults_offset__end.Char = self.Char - __start.Char;

	return 0;
}


/************************ Behavior function *************************/

static int cmd_equipment_library__faults(void)
{
	CB_Object __start = self;
	CB_Index __my_num = self_num;
	int __ret;
	if (exec_term_node(self_num)) {

		/*********************** Internals variables ************************/

		_i_cmd_agitator_2speed__faults_thermalFault = self.Bool+0;
		_i_cmd_agitator_2speed__faults_highSpeedFBFault = self.Bool+1;
		_i_cmd_agitator_2speed__faults_lowSpeedFBFault = self.Bool+2;
		_i_cmd_agitator_2speed__faults_TON_HI_IN = self.Bool+3;
		_i_cmd_agitator_2speed__faults_TON_HI_PT = self.Int+0;
		_i_cmd_agitator_2speed__faults_TON_HI_Q0 = self.Bool+4;
		_i_cmd_agitator_2speed__faults_TON_HI_CV = self.Int+4;
		_i_cmd_agitator_2speed__faults_TON_LO_IN = self.Bool+5;
		_i_cmd_agitator_2speed__faults_TON_LO_PT = self.Int+8;
		_i_cmd_agitator_2speed__faults_TON_LO_Q0 = self.Bool+6;
		_i_cmd_agitator_2speed__faults_TON_LO_CV = self.Int+12;

		/********************* Pre-conditions execution *********************/

		/*no Pre-conditions*/

		/************************ Behavior execution ************************/

		{
			static CB_Mem_Int __literal_0[4] = {
				cb_int_header(2),
				cb_int(0),
				cb_int(20000)
			};
			static CB_Mem_Int __literal_1[4] = {
				cb_int_header(2),
				cb_int(0),
				cb_int(20000)
			};
			unsigned char _1;
			unsigned char _13_Q0;
			CB_Mem_Int _13_CV[4] =  { cb_int_header(2) };
			unsigned char _14_Q0;
			CB_Mem_Int _14_CV[4] =  { cb_int_header(2) };
			_1 = acknowledgePB;
			if (_1) {
				thermalFault = 0;
			}
			if (_1) {
				highSpeedFBFault = 0;
			}
			if (_1) {
				lowSpeedFBFault = 0;
			}
			if (_1) {
				generalFault = 0;
			}
			/*call user FB TON_HI():*/
			TON_HI_IN = highSpeedCmd;
			copy_int_array(_i_cmd_agitator_2speed__faults_TON_HI_PT, __literal_0, 2);
			self.Bool = __start.Bool + cmd_equipment_library__faults_offset_TON_HI.Bool;
			self.Int = __start.Int + cmd_equipment_library__faults_offset_TON_HI.Int;
			self.Float = __start.Float + cmd_equipment_library__faults_offset_TON_HI.Float;
			self.Char = __start.Char + cmd_equipment_library__faults_offset_TON_HI.Char;
			self_num = __my_num + cmd_equipment_library__faults_dnum_TON_HI;
			if (cb_ton__num != self_num) {
				cb_ton__num = self_num;
				cb_ton_IN = _i_cmd_agitator_2speed__faults_TON_HI_IN;
				cb_ton_PT = _i_cmd_agitator_2speed__faults_TON_HI_PT;
				cb_ton_Q0 = _i_cmd_agitator_2speed__faults_TON_HI_Q0;
				cb_ton_CV = _i_cmd_agitator_2speed__faults_TON_HI_CV;
			}
			__ret = timers_counters__cb_ton();
			if (__ret != 0) {
				return __ret; /*user FB failure*/
			}
			self_num = __my_num;
			_13_Q0 = TON_HI_Q0;
			copy_int_array(_13_CV, _i_cmd_agitator_2speed__faults_TON_HI_CV, 2);
			/*end TON_HI()*/
			if (_13_Q0 && !highSpeedFB) {
				highSpeedFBFault = 1;
			}
			/*call user FB TON_LO():*/
			TON_LO_IN = lowSpeedCmd;
			copy_int_array(_i_cmd_agitator_2speed__faults_TON_LO_PT, __literal_1, 2);
			self.Bool = __start.Bool + cmd_equipment_library__faults_offset_TON_LO.Bool;
			self.Int = __start.Int + cmd_equipment_library__faults_offset_TON_LO.Int;
			self.Float = __start.Float + cmd_equipment_library__faults_offset_TON_LO.Float;
			self.Char = __start.Char + cmd_equipment_library__faults_offset_TON_LO.Char;
			self_num = __my_num + cmd_equipment_library__faults_dnum_TON_LO;
			if (cb_ton__num != self_num) {
				cb_ton__num = self_num;
				cb_ton_IN = _i_cmd_agitator_2speed__faults_TON_LO_IN;
				cb_ton_PT = _i_cmd_agitator_2speed__faults_TON_LO_PT;
				cb_ton_Q0 = _i_cmd_agitator_2speed__faults_TON_LO_Q0;
				cb_ton_CV = _i_cmd_agitator_2speed__faults_TON_LO_CV;
			}
			__ret = timers_counters__cb_ton();
			if (__ret != 0) {
				return __ret; /*user FB failure*/
			}
			self_num = __my_num;
			_14_Q0 = TON_LO_Q0;
			copy_int_array(_14_CV, _i_cmd_agitator_2speed__faults_TON_LO_CV, 2);
			/*end TON_LO()*/
			if (_14_Q0 && !lowSpeedFB) {
				lowSpeedFBFault = 1;
			}
			if (!thermalFB) {
				thermalFault = 1;
			}
			if ((thermalFault || highSpeedFBFault) || lowSpeedFBFault) {
				generalFault = 1;
			}
		}

		if(nb_alloc > 0) {
			free_all_alloc();
		}

		CB_post_bool(_i_cmd_agitator_2speed__faults_generalFault);

		/******************** Post-conditions execution *********************/

		/*no Post-conditions*/
	}

	/*************************** self update ****************************/

	self_num = __my_num + cmd_equipment_library__faults_dnum__end;
	self.Bool = __start.Bool + cmd_equipment_library__faults_offset__end.Bool;
	self.Int = __start.Int + cmd_equipment_library__faults_offset__end.Int;
	self.Float = __start.Float + cmd_equipment_library__faults_offset__end.Float;
	self.Char = __start.Char + cmd_equipment_library__faults_offset__end.Char;

	return 0;
}

#undef highSpeedCmd
#undef lowSpeedCmd
#undef highSpeedFB
#undef lowSpeedFB
#undef thermalFB
#undef acknowledgePB
#undef generalFault
#undef thermalFault
#undef highSpeedFBFault
#undef lowSpeedFBFault
#undef TON_HI_IN
#undef TON_HI_PT
#undef TON_HI_Q0
#undef TON_HI_CV
#undef TON_LO_IN
#undef TON_LO_PT
#undef TON_LO_Q0
#undef TON_LO_CV

/********************************************************************
 * Public 'cmd_equipment_library.cmd_agitator_2speed' implementation *
 ********************************************************************/

#include "cmd_agitator_2speed.h"


/**************************** Variables *****************************/

CB_Index cmd_agitator_2speed__num = 0;
CB_Mem_Bool *cmd_agitator_2speed_autoMode;
CB_Mem_Bool *cmd_agitator_2speed_manualMode;
CB_Mem_Bool *cmd_agitator_2speed_autoHSCmd;
CB_Mem_Bool *cmd_agitator_2speed_autoLSCmd;
CB_Mem_Bool *cmd_agitator_2speed_highSpeedPB;
CB_Mem_Bool *cmd_agitator_2speed_lowSpeedPB;
CB_Mem_Bool *cmd_agitator_2speed_stopPB;
CB_Mem_Bool *cmd_agitator_2speed_highSpeedFB;
CB_Mem_Bool *cmd_agitator_2speed_lowSpeedFB;
CB_Mem_Bool *cmd_agitator_2speed_thermalFB;
CB_Mem_Bool *cmd_agitator_2speed_acknowledgePB;
CB_Mem_Bool *cmd_agitator_2speed_highSpeedCmd;
CB_Mem_Bool *cmd_agitator_2speed_lowSpeedCmd;
CB_Mem_Bool *cmd_agitator_2speed_generalFault;

/**************************** Variables *****************************/



/************************ Components offsets ************************/

static CB_Offset cmd_equipment_library__cmd_agitator_2speed_offset_actions;
static CB_Offset cmd_equipment_library__cmd_agitator_2speed_offset_faults1;
static CB_Offset cmd_equipment_library__cmd_agitator_2speed_offset__end = {0, 0, 0, 0};


/********************* Initialization function **********************/

int _cmd_equipment_library__cmd_agitator_2speed_init(void)
{
	CB_Object __start = self;

	/*initialize child actions (cmd_equipment_library.actuator):*/
	self_num++;
	cmd_equipment_library__cmd_agitator_2speed_offset_actions.Bool = self.Bool - __start.Bool;
	cmd_equipment_library__cmd_agitator_2speed_offset_actions.Int = self.Int - __start.Int;
	cmd_equipment_library__cmd_agitator_2speed_offset_actions.Float = self.Float - __start.Float;
	cmd_equipment_library__cmd_agitator_2speed_offset_actions.Char = self.Char - __start.Char;
	_i_cmd_agitator_2speed__actuator_autoMode = cmd_agitator_2speed_autoMode;
	_i_cmd_agitator_2speed__actuator_manualMode = cmd_agitator_2speed_manualMode;
	_i_cmd_agitator_2speed__actuator_autoHSCmd = cmd_agitator_2speed_autoHSCmd;
	_i_cmd_agitator_2speed__actuator_autoLSCmd = cmd_agitator_2speed_autoLSCmd;
	_i_cmd_agitator_2speed__actuator_highSpeedPB = cmd_agitator_2speed_highSpeedPB;
	_i_cmd_agitator_2speed__actuator_lowSpeedPB = cmd_agitator_2speed_lowSpeedPB;
	_i_cmd_agitator_2speed__actuator_stopPB = cmd_agitator_2speed_stopPB;
	_i_cmd_agitator_2speed__actuator_generalFault = cmd_agitator_2speed_generalFault;
	_i_cmd_agitator_2speed__actuator_highSpeedCmd = cmd_agitator_2speed_highSpeedCmd;
	_i_cmd_agitator_2speed__actuator_lowSpeedCmd = cmd_agitator_2speed_lowSpeedCmd;
	_cmd_equipment_library__actuator_init();

	/*initialize child faults1 (cmd_equipment_library.faults):*/
	self_num++;
	cmd_equipment_library__cmd_agitator_2speed_offset_faults1.Bool = self.Bool - __start.Bool;
	cmd_equipment_library__cmd_agitator_2speed_offset_faults1.Int = self.Int - __start.Int;
	cmd_equipment_library__cmd_agitator_2speed_offset_faults1.Float = self.Float - __start.Float;
	cmd_equipment_library__cmd_agitator_2speed_offset_faults1.Char = self.Char - __start.Char;
	_i_cmd_agitator_2speed__faults_highSpeedCmd = cmd_agitator_2speed_highSpeedCmd;
	_i_cmd_agitator_2speed__faults_lowSpeedCmd = cmd_agitator_2speed_lowSpeedCmd;
	_i_cmd_agitator_2speed__faults_highSpeedFB = cmd_agitator_2speed_highSpeedFB;
	_i_cmd_agitator_2speed__faults_lowSpeedFB = cmd_agitator_2speed_lowSpeedFB;
	_i_cmd_agitator_2speed__faults_thermalFB = cmd_agitator_2speed_thermalFB;
	_i_cmd_agitator_2speed__faults_acknowledgePB = cmd_agitator_2speed_acknowledgePB;
	_i_cmd_agitator_2speed__faults_generalFault = cmd_agitator_2speed_generalFault;
	_cmd_equipment_library__faults_init();

	cmd_equipment_library__cmd_agitator_2speed_offset__end.Bool = self.Bool - __start.Bool;
	cmd_equipment_library__cmd_agitator_2speed_offset__end.Int = self.Int - __start.Int;
	cmd_equipment_library__cmd_agitator_2speed_offset__end.Float = self.Float - __start.Float;
	cmd_equipment_library__cmd_agitator_2speed_offset__end.Char = self.Char - __start.Char;

	return 0;
}


/************************ Behavior function *************************/

int cmd_equipment_library__cmd_agitator_2speed(void)
{
	CB_Object __start = self;
	int __ret;
	if (exec_mac_node(self_num)) {

		/*********************** Internals variables ************************/


		/********************* Pre-conditions execution *********************/

		/*no Pre-conditions*/

		/************************ Behavior execution ************************/

		{
			self.Bool = __start.Bool + cmd_equipment_library__cmd_agitator_2speed_offset_actions.Bool;
			self.Int = __start.Int + cmd_equipment_library__cmd_agitator_2speed_offset_actions.Int;
			self.Float = __start.Float + cmd_equipment_library__cmd_agitator_2speed_offset_actions.Float;
			self.Char = __start.Char + cmd_equipment_library__cmd_agitator_2speed_offset_actions.Char;

			/************************ actions execution *************************/

			self_num++;
			if (actuator__num != self_num) {
				actuator__num = self_num;
				_i_cmd_agitator_2speed__actuator_autoMode = cmd_agitator_2speed_autoMode;
				_i_cmd_agitator_2speed__actuator_manualMode = cmd_agitator_2speed_manualMode;
				_i_cmd_agitator_2speed__actuator_autoHSCmd = cmd_agitator_2speed_autoHSCmd;
				_i_cmd_agitator_2speed__actuator_autoLSCmd = cmd_agitator_2speed_autoLSCmd;
				_i_cmd_agitator_2speed__actuator_highSpeedPB = cmd_agitator_2speed_highSpeedPB;
				_i_cmd_agitator_2speed__actuator_lowSpeedPB = cmd_agitator_2speed_lowSpeedPB;
				_i_cmd_agitator_2speed__actuator_stopPB = cmd_agitator_2speed_stopPB;
				_i_cmd_agitator_2speed__actuator_generalFault = cmd_agitator_2speed_generalFault;
				_i_cmd_agitator_2speed__actuator_highSpeedCmd = cmd_agitator_2speed_highSpeedCmd;
				_i_cmd_agitator_2speed__actuator_lowSpeedCmd = cmd_agitator_2speed_lowSpeedCmd;
			}
			__ret = cmd_equipment_library__actuator();
			if (__ret != 0) {
				return __ret; /*child execution failure*/
			}

			/************************ faults1 execution *************************/

			self_num++;
			if (faults__num != self_num) {
				faults__num = self_num;
				_i_cmd_agitator_2speed__faults_highSpeedCmd = cmd_agitator_2speed_highSpeedCmd;
				_i_cmd_agitator_2speed__faults_lowSpeedCmd = cmd_agitator_2speed_lowSpeedCmd;
				_i_cmd_agitator_2speed__faults_highSpeedFB = cmd_agitator_2speed_highSpeedFB;
				_i_cmd_agitator_2speed__faults_lowSpeedFB = cmd_agitator_2speed_lowSpeedFB;
				_i_cmd_agitator_2speed__faults_thermalFB = cmd_agitator_2speed_thermalFB;
				_i_cmd_agitator_2speed__faults_acknowledgePB = cmd_agitator_2speed_acknowledgePB;
				_i_cmd_agitator_2speed__faults_generalFault = cmd_agitator_2speed_generalFault;
			}
			__ret = cmd_equipment_library__faults();
			if (__ret != 0) {
				return __ret; /*child execution failure*/
			}

		}


		/******************** Post-conditions execution *********************/

		/*no Post-conditions*/
	}

	/*************************** self update ****************************/

	self.Bool = __start.Bool + cmd_equipment_library__cmd_agitator_2speed_offset__end.Bool;
	self.Int = __start.Int + cmd_equipment_library__cmd_agitator_2speed_offset__end.Int;
	self.Float = __start.Float + cmd_equipment_library__cmd_agitator_2speed_offset__end.Float;
	self.Char = __start.Char + cmd_equipment_library__cmd_agitator_2speed_offset__end.Char;

	return 0;
}

