/*2023-10-03T11:13:14-01:00*/

/********************************************************************
 * contactor.h
 * 
 * generated by: plcgen 3.1.391
 ********************************************************************/

#ifndef _EQUIPMENT_LIBRARY__CONTACTOR_H
#define _EQUIPMENT_LIBRARY__CONTACTOR_H


/********************** Variable declarations ***********************/

extern CB_Index contactor__num;
extern CB_Mem_Bool *contactor_voltage380;
extern CB_Mem_Bool *contactor_cmdSupply;
extern CB_Mem_Bool *contactor_sensorSupply;
extern CB_Mem_Bool *contactor_forward;
extern CB_Mem_Bool *contactor_forwardState;
extern CB_Mem_Bool *contactor_contactorFB;
extern CB_Mem_Bool *contactor_thermal;
extern CB_Mem_Bool *contactor_memoForward;
extern CB_Mem_Bool *contactor_forwardLogic;
extern CB_Mem_Bool *contactor_thermalLogic;
extern CB_Mem_Bool *contactor_d_forward;
extern CB_Mem_Bool *contactor_v_d_forward;
extern CB_Mem_Bool *contactor_d_electrical;
extern CB_Mem_Bool *contactor_v_d_electrical;

/********************** Function declarations ***********************/

extern int _equipment_library__contactor_init(void);
extern int equipment_library__contactor(void);

#endif /*_EQUIPMENT_LIBRARY__CONTACTOR_H*/
