/*2023-10-03T11:13:35-01:00*/

/********************************************************************
 * cmd_double_acting_jack_lmp.h
 * 
 * generated by: plcgen 3.1.391
 ********************************************************************/

#ifndef _CMD_EQUIPMENT_LIBRARY__CMD_DOUBLE_ACTING_JACK_LMP_H
#define _CMD_EQUIPMENT_LIBRARY__CMD_DOUBLE_ACTING_JACK_LMP_H


/********************** Variable declarations ***********************/

extern CB_Index cmd_double_acting_jack_lmp__num;
extern CB_Mem_Bool *cmd_double_acting_jack_lmp_autoMode;
extern CB_Mem_Bool *cmd_double_acting_jack_lmp_manualMode;
extern CB_Mem_Bool *cmd_double_acting_jack_lmp_autoWorkCmd;
extern CB_Mem_Bool *cmd_double_acting_jack_lmp_autoRestCmd;
extern CB_Mem_Bool *cmd_double_acting_jack_lmp_valveWorkPB;
extern CB_Mem_Bool *cmd_double_acting_jack_lmp_valveRestPB;
extern CB_Mem_Bool *cmd_double_acting_jack_lmp_outletSensor;
extern CB_Mem_Bool *cmd_double_acting_jack_lmp_inletSensor;
extern CB_Mem_Bool *cmd_double_acting_jack_lmp_acknowledgePB;
extern CB_Mem_Bool *cmd_double_acting_jack_lmp_workCmd;
extern CB_Mem_Bool *cmd_double_acting_jack_lmp_restCmd;
extern CB_Mem_Bool *cmd_double_acting_jack_lmp_generalFault;

/********************** Function declarations ***********************/

extern int _cmd_equipment_library__cmd_double_acting_jack_lmp_init(void);
extern int cmd_equipment_library__cmd_double_acting_jack_lmp(void);

#endif /*_CMD_EQUIPMENT_LIBRARY__CMD_DOUBLE_ACTING_JACK_LMP_H*/
