<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- Generator: ControlBuild -->

<CB_COMPONENT NAME="flow_compute" COMMENTS="This module computes the flow in litre / min.
It should be set at the inlet of the circuit or at the outlet of a tank." COMMENTS_PATTERN="&lt;CLASS_PATTERN&gt;" PICTURE_PATH="" INSTANCE_NAMIMG_PATTERN="&lt;CLASS_PATTERN&gt;" COMPONENT_CLASS="SIMULATION" SAFE_MODE="False" BREAKPOINT="False" GEN_STATUS="good">
	<MODEL_REQUIREMENTS>
		<FUNCTIONAL_TREE TYPE="c" />
	</MODEL_REQUIREMENTS>
	<externalSrcs />
</CB_COMPONENT>