/********************************************************************
 * _init.h
 * 
 * generated by: plcgen 3.1.391
 ********************************************************************/

#define mx_use_tni_train__cab
#define mx_use_tni_train__key2position
#define mx_use_tni_train__service_side
#define mx_use_tni_train__pb
#define mx_use_tni_train__speed
#define mx_use_tni_train__cp_cab
#define mx_use_tni_train__car
#define mx_use_tni_train__authorizations
#define mx_use_tni_train__op_alarms
#define mx_use_tni_train__op_alarm
#define mx_use_tni_train__door
#define mx_use_tni_train__pb_door
#define mx_use_tni_train__op_door_locking
#define mx_use_tni_train__cp_door
#define mx_use_tni_train__op_door
#define mx_use_tni_train__tni_train


