/*2023-10-03T11:12:43-01:00*/

/********************************************************************
 * cb_ton.h
 * 
 * generated by: plcgen 3.1.391
 ********************************************************************/

#ifndef _TIMERS_COUNTERS__CB_TON_H
#define _TIMERS_COUNTERS__CB_TON_H


/********************** Variable declarations ***********************/

extern CB_Index cb_ton__num;
extern CB_Mem_Bool *cb_ton_IN;
extern CB_Mem_Int *cb_ton_PT;
extern CB_Mem_Bool *cb_ton_Q0;
extern CB_Mem_Int *cb_ton_CV;

/********************** Function declarations ***********************/

extern int _timers_counters__cb_ton_init(void);
extern int timers_counters__cb_ton(void);

#endif /*_TIMERS_COUNTERS__CB_TON_H*/
