/*2023-10-03T11:13:41-01:00*/

/********************************************************************
 * mode_cov.c
 * 
 * generated by: plcgen 3.1.391
 ********************************************************************/

#include "cb_comp.h"
#include "cb_covs.h"
#include "iec_1131.h"

#include "mode.h"


/**************************** Variables *****************************/

CB_Index mode__num = 0;
CB_Mem_Bool *mode_powerUpPB;
CB_Mem_Bool *mode_emergencyStopPB;
CB_Mem_Bool *mode_manual;
CB_Mem_Bool *mode_auto;
CB_Mem_Bool *mode_acknowledgePB;
CB_Mem_Bool *mode_powerUp;
CB_Mem_Bool *mode_autoMode;
CB_Mem_Bool *mode_manualMode;
CB_Mem_Bool *mode_emStp;
CB_Mem_Bool *mode_sr1_Q1;
CB_Mem_Int *mode_sr1_i_sr;
CB_Mem_Bool *mode_powerUpPB_PREV;
CB_Mem_Int *mode_powerUpPB_EDGE;
CB_Mem_Bool *mode_acknowledgePB_PREV;
CB_Mem_Int *mode_acknowledgePB_EDGE;

/**************************** Variables *****************************/

#define powerUpPB (mode_powerUpPB->CB_current_value)
#define emergencyStopPB (mode_emergencyStopPB->CB_current_value)
#define manual (mode_manual->CB_current_value)
#define auto (mode_auto->CB_current_value)
#define acknowledgePB (mode_acknowledgePB->CB_current_value)
#define powerUp (mode_powerUp->CB_current_value)
#define autoMode (mode_autoMode->CB_current_value)
#define manualMode (mode_manualMode->CB_current_value)
#define emStp (mode_emStp->CB_current_value)
#define sr1_Q1 (mode_sr1_Q1->CB_current_value)
#define sr1_i_sr (*((short *)&(mode_sr1_i_sr->CB_current_value) + ALIGN_OFFSET_SHORT))
#define powerUpPB_PREV (mode_powerUpPB_PREV->CB_current_value)
#define powerUpPB_EDGE (mode_powerUpPB_EDGE->CB_current_value)
#define acknowledgePB_PREV (mode_acknowledgePB_PREV->CB_current_value)
#define acknowledgePB_EDGE (mode_acknowledgePB_EDGE->CB_current_value)


/************************ Components offsets ************************/


/********************* Initialization function **********************/

int _bottling_line__mode_init(void)
{
	self.Bool+=4;
	self.Int+=3;


	return 0;
}


/************************ Behavior function *************************/

int bottling_line__mode(void)
{
	static char *__comp_name = "bottling_line.mode";
	if (exec_term_node(self_num)) {

		/*********************** Internals variables ************************/

		mode_emStp = self.Bool+0;
		mode_sr1_Q1 = self.Bool+1;
		mode_sr1_i_sr = self.Int+0;
		mode_powerUpPB_PREV = self.Bool+2;
		mode_powerUpPB_EDGE = self.Int+1;
		mode_acknowledgePB_PREV = self.Bool+3;
		mode_acknowledgePB_EDGE = self.Int+2;

		/********************* Pre-conditions execution *********************/

		/*no Pre-conditions*/

		/************************ Behavior execution ************************/

		{
			unsigned char _5;
			unsigned char _4;
			unsigned char _3;
			unsigned char _16;
			unsigned char _14;
			unsigned char _15;
			unsigned char _7;
			unsigned char _17;
			unsigned char _9;
			unsigned char _8;
			unsigned char _10;
			unsigned char _11;
			powerUpPB_EDGE = CB_edge_bool(powerUpPB, powerUpPB_PREV);
			acknowledgePB_EDGE = CB_edge_bool(acknowledgePB, acknowledgePB_PREV);
			_5 = powerUpPB_EDGE > 0;
			cov_output(__comp_name, self_num, 5, 0, _5);
			_4 = _5 && !powerUp;
			cov_output(__comp_name, self_num, 4, 0, _4);
			_3 = _5 && powerUp;
			cov_output(__comp_name, self_num, 3, 0, _3);
			sr1_Q1 = sr_Q1(_4, _3, &sr1_i_sr);
			cov_output(__comp_name, self_num, 2, 1, sr1_Q1);
			powerUp = sr1_Q1;
			cov_output(__comp_name, self_num, 1, 0, powerUp);
			_16 = !emergencyStopPB;
			cov_output(__comp_name, self_num, 16, 0, _16);
			if (_16) {
				emStp = 1;
			}
			cov_output(__comp_name, self_num, 18, 0, emStp);
			_14 = acknowledgePB_EDGE < 0;
			cov_output(__comp_name, self_num, 14, 0, _14);
			_15 = _14 && emergencyStopPB;
			cov_output(__comp_name, self_num, 15, 0, _15);
			if (_15) {
				emStp = 0;
			}
			cov_output(__comp_name, self_num, 19, 0, emStp);
			_7 = powerUp;
			cov_output(__comp_name, self_num, 7, 0, _7);
			_17 = _7 && !emStp;
			cov_output(__comp_name, self_num, 17, 0, _17);
			_9 = _17 && auto;
			cov_output(__comp_name, self_num, 9, 0, _9);
			_8 = _9 && !manual;
			cov_output(__comp_name, self_num, 8, 0, _8);
			autoMode = _8;
			cov_output(__comp_name, self_num, 12, 0, autoMode);
			_10 = _17 && !auto;
			cov_output(__comp_name, self_num, 10, 0, _10);
			_11 = _10 && manual;
			cov_output(__comp_name, self_num, 11, 0, _11);
			manualMode = _11;
			cov_output(__comp_name, self_num, 13, 0, manualMode);
			powerUpPB_PREV = powerUpPB;
			acknowledgePB_PREV = acknowledgePB;
		}

		if(nb_alloc > 0) {
			free_all_alloc();
		}

		CB_post_bool(mode_powerUp);
		CB_post_bool(mode_autoMode);
		CB_post_bool(mode_manualMode);

		/******************** Post-conditions execution *********************/

		/*no Post-conditions*/
	}

	/*************************** self update ****************************/

	self.Bool += 4;
	self.Int += 3;

	return 0;
}

