/*2023-10-03T11:13:41-01:00*/

/********************************************************************
 * mode.c
 * 
 * generated by: plcgen 3.1.391
 ********************************************************************/

#include "cb_comp.h"
#include "iec_1131.h"

#include "mode.h"


/**************************** Variables *****************************/

CB_Index mode__num = 0;
CB_Mem_Bool *mode_powerUpPB;
CB_Mem_Bool *mode_emergencyStopPB;
CB_Mem_Bool *mode_manual;
CB_Mem_Bool *mode_auto;
CB_Mem_Bool *mode_acknowledgePB;
CB_Mem_Bool *mode_powerUp;
CB_Mem_Bool *mode_autoMode;
CB_Mem_Bool *mode_manualMode;
CB_Mem_Bool *mode_emStp;
CB_Mem_Bool *mode_sr1_Q1;
CB_Mem_Int *mode_sr1_i_sr;
CB_Mem_Bool *mode_powerUpPB_PREV;
CB_Mem_Int *mode_powerUpPB_EDGE;
CB_Mem_Bool *mode_acknowledgePB_PREV;
CB_Mem_Int *mode_acknowledgePB_EDGE;

/**************************** Variables *****************************/

#define powerUpPB (mode_powerUpPB->CB_current_value)
#define emergencyStopPB (mode_emergencyStopPB->CB_current_value)
#define manual (mode_manual->CB_current_value)
#define auto (mode_auto->CB_current_value)
#define acknowledgePB (mode_acknowledgePB->CB_current_value)
#define powerUp (mode_powerUp->CB_current_value)
#define autoMode (mode_autoMode->CB_current_value)
#define manualMode (mode_manualMode->CB_current_value)
#define emStp (mode_emStp->CB_current_value)
#define sr1_Q1 (mode_sr1_Q1->CB_current_value)
#define sr1_i_sr (*((short *)&(mode_sr1_i_sr->CB_current_value) + ALIGN_OFFSET_SHORT))
#define powerUpPB_PREV (mode_powerUpPB_PREV->CB_current_value)
#define powerUpPB_EDGE (mode_powerUpPB_EDGE->CB_current_value)
#define acknowledgePB_PREV (mode_acknowledgePB_PREV->CB_current_value)
#define acknowledgePB_EDGE (mode_acknowledgePB_EDGE->CB_current_value)


/************************ Components offsets ************************/


/********************* Initialization function **********************/

int _bottling_line__mode_init(void)
{
	self.Bool+=4;
	self.Int+=3;


	return 0;
}


/************************ Behavior function *************************/

int bottling_line__mode(void)
{
	if (exec_term_node(self_num)) {

		/*********************** Internals variables ************************/

		mode_emStp = self.Bool+0;
		mode_sr1_Q1 = self.Bool+1;
		mode_sr1_i_sr = self.Int+0;
		mode_powerUpPB_PREV = self.Bool+2;
		mode_powerUpPB_EDGE = self.Int+1;
		mode_acknowledgePB_PREV = self.Bool+3;
		mode_acknowledgePB_EDGE = self.Int+2;

		/********************* Pre-conditions execution *********************/

		/*no Pre-conditions*/

		/************************ Behavior execution ************************/

		{
			unsigned char _5;
			unsigned char _17;
			powerUpPB_EDGE = CB_edge_bool(powerUpPB, powerUpPB_PREV);
			acknowledgePB_EDGE = CB_edge_bool(acknowledgePB, acknowledgePB_PREV);
			_5 = powerUpPB_EDGE > 0;
			sr1_Q1 = sr_Q1(_5 && !powerUp, _5 && powerUp, &sr1_i_sr);
			powerUp = sr1_Q1;
			if (!emergencyStopPB) {
				emStp = 1;
			}
			if ((acknowledgePB_EDGE < 0) && emergencyStopPB) {
				emStp = 0;
			}
			_17 = powerUp && !emStp;
			autoMode = (_17 && auto) && !manual;
			manualMode = (_17 && !auto) && manual;
			powerUpPB_PREV = powerUpPB;
			acknowledgePB_PREV = acknowledgePB;
		}

		if(nb_alloc > 0) {
			free_all_alloc();
		}

		CB_post_bool(mode_powerUp);
		CB_post_bool(mode_autoMode);
		CB_post_bool(mode_manualMode);

		/******************** Post-conditions execution *********************/

		/*no Post-conditions*/
	}

	/*************************** self update ****************************/

	self.Bool += 4;
	self.Int += 3;

	return 0;
}

