/*2023-10-03T11:12:49-01:00*/

/********************************************************************
 * io_single_acting_valve.h
 * 
 * generated by: plcgen 3.1.391
 ********************************************************************/

#ifndef _IO_LIBRARY__IO_SINGLE_ACTING_VALVE_H
#define _IO_LIBRARY__IO_SINGLE_ACTING_VALVE_H


/********************** Variable declarations ***********************/

extern CB_Index io_single_acting_valve__num;
extern CB_Mem_Bool *io_single_acting_valve_acknowledgePB;
extern CB_Mem_Bool *io_single_acting_valve_autoMode;
extern CB_Mem_Bool *io_single_acting_valve_manualMode;
extern CB_Mem_Bool *io_single_acting_valve_autoOpenCmd;
extern CB_Mem_Float *io_single_acting_valve_inputFlow;
extern CB_Mem_Bool *io_single_acting_valve_openedSensor;
extern CB_Mem_Bool *io_single_acting_valve_closedSensor;
extern CB_Mem_Bool *io_single_acting_valve_generalFault;
extern CB_Mem_Float *io_single_acting_valve_outputFlow;
extern CB_Mem_Float *io_single_acting_valve_percentOpening;

/********************** Function declarations ***********************/

extern int _io_library__io_single_acting_valve_init(void);
extern int io_library__io_single_acting_valve(void);

#endif /*_IO_LIBRARY__IO_SINGLE_ACTING_VALVE_H*/
