/*2024-04-12T15:10:27-01:00*/

/********************************************************************
 * ap_master.h
 * 
 * generated by: plcgen 3.1.391
 ********************************************************************/

#ifndef _AP_MASTER__AP_MASTER_H
#define _AP_MASTER__AP_MASTER_H


/********************** Variable declarations ***********************/

extern CB_Index ap_master__num;

/********************** Function declarations ***********************/

extern int _ap_master__ap_master_init(void);
extern int ap_master__ap_master(void);

#endif /*_AP_MASTER__AP_MASTER_H*/
