/*2023-10-03T11:13:44-01:00*/

/********************************************************************
 * drill_cov.c
 * 
 * generated by: plcgen 3.1.391
 ********************************************************************/

#include "cb_comp.h"
#include "cb_covs.h"
#include "iec_1131.h"


/********************************************************************
 *                  Inner 'gen_panel' declarations                  *
 ********************************************************************/


/********************** Variable declarations ***********************/

static CB_Index gen_panel__num;
extern CB_Mem_Bool *_i_drill__gen_panel_powerUpPB;
extern CB_Mem_Bool *_i_drill__gen_panel_startCyclePB;
extern CB_Mem_Bool *_i_drill__gen_panel_emergencyStop;
extern CB_Mem_Bool *_i_drill__gen_panel_batchCycle;
extern CB_Mem_Bool *_i_drill__gen_panel_pieceCycle;
extern CB_Mem_Bool *_i_drill__gen_panel_autoSwitch;
extern CB_Mem_Bool *_i_drill__gen_panel_manualSwitch;
extern CB_Mem_Bool *_i_drill__gen_panel_acknowledgePB;

/********************** Function declarations ***********************/

static int _drill__gen_panel_init(void);
static int drill__gen_panel(void);

/********************************************************************
 *                 Inner 'gen_panel' implementation                 *
 ********************************************************************/

#include "equipment_library/functional/momentary_button/momentary_button.h"
#include "equipment_library/functional/switch_2pos_2outputs/switch_2pos_2outputs.h"
#include "equipment_library/functional/maintained_button/maintained_button.h"


/**************************** Variables *****************************/

static CB_Index gen_panel__num = 0;
CB_Mem_Bool *_i_drill__gen_panel_powerUpPB;
CB_Mem_Bool *_i_drill__gen_panel_startCyclePB;
CB_Mem_Bool *_i_drill__gen_panel_emergencyStop;
CB_Mem_Bool *_i_drill__gen_panel_batchCycle;
CB_Mem_Bool *_i_drill__gen_panel_pieceCycle;
CB_Mem_Bool *_i_drill__gen_panel_autoSwitch;
CB_Mem_Bool *_i_drill__gen_panel_manualSwitch;
CB_Mem_Bool *_i_drill__gen_panel_acknowledgePB;

/**************************** Variables *****************************/



/************************ Components offsets ************************/

static CB_Offset drill__gen_panel_offset_powerUpPB;
static CB_Offset drill__gen_panel_offset_startCyclePB;
static CB_Offset drill__gen_panel_offset_cycleSwitch;
static CB_Offset drill__gen_panel_offset_modeSwitch;
static CB_Offset drill__gen_panel_offset_acknowledgePB;
static CB_Offset drill__gen_panel_offset_emergencyStop;
static CB_Offset drill__gen_panel_offset__end = {0, 0, 0, 0};


/********************* Initialization function **********************/

static int _drill__gen_panel_init(void)
{
	CB_Object __start = self;

	/*initialize child powerUpPB (equipment_library.momentary_button):*/
	self_num++;
	drill__gen_panel_offset_powerUpPB.Bool = self.Bool - __start.Bool;
	drill__gen_panel_offset_powerUpPB.Int = self.Int - __start.Int;
	drill__gen_panel_offset_powerUpPB.Float = self.Float - __start.Float;
	drill__gen_panel_offset_powerUpPB.Char = self.Char - __start.Char;
	momentary_button_PB = _i_drill__gen_panel_powerUpPB;
	_equipment_library__momentary_button_init();

	/*initialize child startCyclePB (equipment_library.momentary_button):*/
	self_num++;
	drill__gen_panel_offset_startCyclePB.Bool = self.Bool - __start.Bool;
	drill__gen_panel_offset_startCyclePB.Int = self.Int - __start.Int;
	drill__gen_panel_offset_startCyclePB.Float = self.Float - __start.Float;
	drill__gen_panel_offset_startCyclePB.Char = self.Char - __start.Char;
	momentary_button_PB = _i_drill__gen_panel_startCyclePB;
	_equipment_library__momentary_button_init();

	/*initialize child cycleSwitch (equipment_library.switch_2pos_2outputs):*/
	self_num++;
	drill__gen_panel_offset_cycleSwitch.Bool = self.Bool - __start.Bool;
	drill__gen_panel_offset_cycleSwitch.Int = self.Int - __start.Int;
	drill__gen_panel_offset_cycleSwitch.Float = self.Float - __start.Float;
	drill__gen_panel_offset_cycleSwitch.Char = self.Char - __start.Char;
	switch_2pos_2outputs_leftVariable = _i_drill__gen_panel_pieceCycle;
	switch_2pos_2outputs_rightVariable = _i_drill__gen_panel_batchCycle;
	_equipment_library__switch_2pos_2outputs_init();

	/*initialize child modeSwitch (equipment_library.switch_2pos_2outputs):*/
	self_num++;
	drill__gen_panel_offset_modeSwitch.Bool = self.Bool - __start.Bool;
	drill__gen_panel_offset_modeSwitch.Int = self.Int - __start.Int;
	drill__gen_panel_offset_modeSwitch.Float = self.Float - __start.Float;
	drill__gen_panel_offset_modeSwitch.Char = self.Char - __start.Char;
	switch_2pos_2outputs_leftVariable = _i_drill__gen_panel_autoSwitch;
	switch_2pos_2outputs_rightVariable = _i_drill__gen_panel_manualSwitch;
	_equipment_library__switch_2pos_2outputs_init();

	/*initialize child acknowledgePB (equipment_library.momentary_button):*/
	self_num++;
	drill__gen_panel_offset_acknowledgePB.Bool = self.Bool - __start.Bool;
	drill__gen_panel_offset_acknowledgePB.Int = self.Int - __start.Int;
	drill__gen_panel_offset_acknowledgePB.Float = self.Float - __start.Float;
	drill__gen_panel_offset_acknowledgePB.Char = self.Char - __start.Char;
	momentary_button_PB = _i_drill__gen_panel_acknowledgePB;
	_equipment_library__momentary_button_init();

	/*initialize child emergencyStop (equipment_library.maintained_button):*/
	self_num++;
	drill__gen_panel_offset_emergencyStop.Bool = self.Bool - __start.Bool;
	drill__gen_panel_offset_emergencyStop.Int = self.Int - __start.Int;
	drill__gen_panel_offset_emergencyStop.Float = self.Float - __start.Float;
	drill__gen_panel_offset_emergencyStop.Char = self.Char - __start.Char;
	maintained_button_pb = _i_drill__gen_panel_emergencyStop;
	_equipment_library__maintained_button_init();

	drill__gen_panel_offset__end.Bool = self.Bool - __start.Bool;
	drill__gen_panel_offset__end.Int = self.Int - __start.Int;
	drill__gen_panel_offset__end.Float = self.Float - __start.Float;
	drill__gen_panel_offset__end.Char = self.Char - __start.Char;

	return 0;
}


/************************ Behavior function *************************/

static int drill__gen_panel(void)
{
	CB_Object __start = self;
	int __ret;
	static char *__comp_name = "drill.gen_panel";
	if (exec_mac_node(self_num)) {

		/*********************** Internals variables ************************/


		/********************* Pre-conditions execution *********************/

		/*no Pre-conditions*/

		/************************ Behavior execution ************************/

		{
			self.Bool = __start.Bool + drill__gen_panel_offset_powerUpPB.Bool;
			self.Int = __start.Int + drill__gen_panel_offset_powerUpPB.Int;
			self.Float = __start.Float + drill__gen_panel_offset_powerUpPB.Float;
			self.Char = __start.Char + drill__gen_panel_offset_powerUpPB.Char;

			/*********************** powerUpPB execution ************************/

			self_num++;
			if (momentary_button__num != self_num) {
				momentary_button__num = self_num;
				momentary_button_PB = _i_drill__gen_panel_powerUpPB;
			}
			__ret = equipment_library__momentary_button();
			if (__ret != 0) {
				return __ret; /*child execution failure*/
			}

			/********************** startCyclePB execution **********************/

			self_num++;
			if (momentary_button__num != self_num) {
				momentary_button__num = self_num;
				momentary_button_PB = _i_drill__gen_panel_startCyclePB;
			}
			__ret = equipment_library__momentary_button();
			if (__ret != 0) {
				return __ret; /*child execution failure*/
			}

			/********************** cycleSwitch execution ***********************/

			self_num++;
			if (switch_2pos_2outputs__num != self_num) {
				switch_2pos_2outputs__num = self_num;
				switch_2pos_2outputs_leftVariable = _i_drill__gen_panel_pieceCycle;
				switch_2pos_2outputs_rightVariable = _i_drill__gen_panel_batchCycle;
			}
			__ret = equipment_library__switch_2pos_2outputs();
			if (__ret != 0) {
				return __ret; /*child execution failure*/
			}

			/*********************** modeSwitch execution ***********************/

			self_num++;
			if (switch_2pos_2outputs__num != self_num) {
				switch_2pos_2outputs__num = self_num;
				switch_2pos_2outputs_leftVariable = _i_drill__gen_panel_autoSwitch;
				switch_2pos_2outputs_rightVariable = _i_drill__gen_panel_manualSwitch;
			}
			__ret = equipment_library__switch_2pos_2outputs();
			if (__ret != 0) {
				return __ret; /*child execution failure*/
			}

			/********************* acknowledgePB execution **********************/

			self_num++;
			if (momentary_button__num != self_num) {
				momentary_button__num = self_num;
				momentary_button_PB = _i_drill__gen_panel_acknowledgePB;
			}
			__ret = equipment_library__momentary_button();
			if (__ret != 0) {
				return __ret; /*child execution failure*/
			}

			/********************* emergencyStop execution **********************/

			self_num++;
			if (maintained_button__num != self_num) {
				maintained_button__num = self_num;
				maintained_button_pb = _i_drill__gen_panel_emergencyStop;
			}
			__ret = equipment_library__maintained_button();
			if (__ret != 0) {
				return __ret; /*child execution failure*/
			}

		}


		/******************** Post-conditions execution *********************/

		/*no Post-conditions*/
	}

	/*************************** self update ****************************/

	self.Bool = __start.Bool + drill__gen_panel_offset__end.Bool;
	self.Int = __start.Int + drill__gen_panel_offset__end.Int;
	self.Float = __start.Float + drill__gen_panel_offset__end.Float;
	self.Char = __start.Char + drill__gen_panel_offset__end.Char;

	return 0;
}


/********************************************************************
 *               Public 'drill.drill' implementation                *
 ********************************************************************/

#include "drill.h"
#include "drill/functional/mode/mode.h"
#include "drill/functional/function/function.h"
#include "drill/functional/piece/piece.h"


/**************************** Variables *****************************/

CB_Index drill__num = 0;

/**************************** Variables *****************************/



/************************ Components offsets ************************/

static CB_Offset drill__drill_offset_generalPanel;
static CB_Offset drill__drill_offset_workingModes;
static CB_Offset drill__drill_offset_functional;
static CB_Offset drill__drill_offset_load;
static CB_Offset drill__drill_offset__end = {0, 0, 0, 0};


/********************* Initialization function **********************/

int _drill__drill_init(void)
{
	CB_Object __start = self;
	self.Bool+=19;

	/*initialize child generalPanel (drill.gen_panel):*/
	self_num++;
	drill__drill_offset_generalPanel.Bool = self.Bool - __start.Bool;
	drill__drill_offset_generalPanel.Int = self.Int - __start.Int;
	drill__drill_offset_generalPanel.Float = self.Float - __start.Float;
	drill__drill_offset_generalPanel.Char = self.Char - __start.Char;
	_i_drill__gen_panel_powerUpPB = __start.Bool+2; /*drill__cn_17*/
	_i_drill__gen_panel_startCyclePB = __start.Bool+3; /*drill__cn_16*/
	_i_drill__gen_panel_emergencyStop = __start.Bool+4; /*drill__cn_15*/
	_i_drill__gen_panel_batchCycle = __start.Bool+5; /*drill__cn_14*/
	_i_drill__gen_panel_pieceCycle = __start.Bool+6; /*drill__cn_13*/
	_i_drill__gen_panel_autoSwitch = __start.Bool+7; /*drill__cn_12*/
	_i_drill__gen_panel_manualSwitch = __start.Bool+8; /*drill__cn_11*/
	_i_drill__gen_panel_acknowledgePB = __start.Bool+10; /*drill__cn_9*/
	_drill__gen_panel_init();

	/*initialize child workingModes (drill.mode):*/
	self_num++;
	drill__drill_offset_workingModes.Bool = self.Bool - __start.Bool;
	drill__drill_offset_workingModes.Int = self.Int - __start.Int;
	drill__drill_offset_workingModes.Float = self.Float - __start.Float;
	drill__drill_offset_workingModes.Char = self.Char - __start.Char;
	mode_powerUpPB = __start.Bool+2; /*drill__cn_17*/
	mode_startCyclePB = __start.Bool+3; /*drill__cn_16*/
	mode_emergencyStop = __start.Bool+4; /*drill__cn_15*/
	mode_batchCycle = __start.Bool+5; /*drill__cn_14*/
	mode_pieceCycle = __start.Bool+6; /*drill__cn_13*/
	mode_autoSwitch = __start.Bool+7; /*drill__cn_12*/
	mode_manualSwitch = __start.Bool+8; /*drill__cn_11*/
	mode_cycleEnd = __start.Bool+9; /*drill__cn_10*/
	mode_acknowledgePB = __start.Bool+10; /*drill__cn_9*/
	mode_live = __start.Bool+1; /*drill__cn_18*/
	mode_autoMode = __start.Bool+15; /*drill__cn_4*/
	mode_manualMode = __start.Bool+16; /*drill__cn_3*/
	mode_emptyProd = __start.Bool+12; /*drill__cn_7*/
	mode_unitProd = __start.Bool+13; /*drill__cn_6*/
	mode_batchProd = __start.Bool+14; /*drill__cn_5*/
	_drill__mode_init();

	/*initialize child functional (drill.function):*/
	self_num++;
	drill__drill_offset_functional.Bool = self.Bool - __start.Bool;
	drill__drill_offset_functional.Int = self.Int - __start.Int;
	drill__drill_offset_functional.Float = self.Float - __start.Float;
	drill__drill_offset_functional.Char = self.Char - __start.Char;
	function_piece = __start.Bool+11; /*drill__cn_8*/
	function_emptyProd = __start.Bool+12; /*drill__cn_7*/
	function_unitProd = __start.Bool+13; /*drill__cn_6*/
	function_batchProd = __start.Bool+14; /*drill__cn_5*/
	function_acknowledgePB = __start.Bool+10; /*drill__cn_9*/
	function_autoMode = __start.Bool+15; /*drill__cn_4*/
	function_manualMode = __start.Bool+16; /*drill__cn_3*/
	function_faultyState = __start.Bool+0; /*drill__cn_19*/
	function_cycleEnd = __start.Bool+9; /*drill__cn_10*/
	function_loadingRequest = __start.Bool+17; /*drill__cn_2*/
	function_unloadingRequest = __start.Bool+18; /*drill__cn_1*/
	_drill__function_init();

	/*initialize child load (drill.piece):*/
	self_num++;
	drill__drill_offset_load.Bool = self.Bool - __start.Bool;
	drill__drill_offset_load.Int = self.Int - __start.Int;
	drill__drill_offset_load.Float = self.Float - __start.Float;
	drill__drill_offset_load.Char = self.Char - __start.Char;
	piece_loadingRequest = __start.Bool+17; /*drill__cn_2*/
	piece_unloadingRequest = __start.Bool+18; /*drill__cn_1*/
	piece_piece = __start.Bool+11; /*drill__cn_8*/
	_drill__piece_init();

	drill__drill_offset__end.Bool = self.Bool - __start.Bool;
	drill__drill_offset__end.Int = self.Int - __start.Int;
	drill__drill_offset__end.Float = self.Float - __start.Float;
	drill__drill_offset__end.Char = self.Char - __start.Char;

	return 0;
}


/************************ Behavior function *************************/

int drill__drill(void)
{
	CB_Object __start = self;
	int __ret;
	static char *__comp_name = "drill.drill";
	if (exec_mac_node(self_num)) {

		/*********************** Internals variables ************************/

																																						
		/********************* Pre-conditions execution *********************/

		/*no Pre-conditions*/

		/************************ Behavior execution ************************/

		{
			self.Bool = __start.Bool + drill__drill_offset_generalPanel.Bool;
			self.Int = __start.Int + drill__drill_offset_generalPanel.Int;
			self.Float = __start.Float + drill__drill_offset_generalPanel.Float;
			self.Char = __start.Char + drill__drill_offset_generalPanel.Char;

			/********************** generalPanel execution **********************/

			self_num++;
			if (gen_panel__num != self_num) {
				gen_panel__num = self_num;
				_i_drill__gen_panel_powerUpPB = __start.Bool+2; /*drill__cn_17*/
				_i_drill__gen_panel_startCyclePB = __start.Bool+3; /*drill__cn_16*/
				_i_drill__gen_panel_emergencyStop = __start.Bool+4; /*drill__cn_15*/
				_i_drill__gen_panel_batchCycle = __start.Bool+5; /*drill__cn_14*/
				_i_drill__gen_panel_pieceCycle = __start.Bool+6; /*drill__cn_13*/
				_i_drill__gen_panel_autoSwitch = __start.Bool+7; /*drill__cn_12*/
				_i_drill__gen_panel_manualSwitch = __start.Bool+8; /*drill__cn_11*/
				_i_drill__gen_panel_acknowledgePB = __start.Bool+10; /*drill__cn_9*/
			}
			__ret = drill__gen_panel();
			if (__ret != 0) {
				return __ret; /*child execution failure*/
			}

			/********************** workingModes execution **********************/

			self_num++;
			if (mode__num != self_num) {
				mode__num = self_num;
				mode_powerUpPB = __start.Bool+2; /*drill__cn_17*/
				mode_startCyclePB = __start.Bool+3; /*drill__cn_16*/
				mode_emergencyStop = __start.Bool+4; /*drill__cn_15*/
				mode_batchCycle = __start.Bool+5; /*drill__cn_14*/
				mode_pieceCycle = __start.Bool+6; /*drill__cn_13*/
				mode_autoSwitch = __start.Bool+7; /*drill__cn_12*/
				mode_manualSwitch = __start.Bool+8; /*drill__cn_11*/
				mode_cycleEnd = __start.Bool+9; /*drill__cn_10*/
				mode_acknowledgePB = __start.Bool+10; /*drill__cn_9*/
				mode_live = __start.Bool+1; /*drill__cn_18*/
				mode_autoMode = __start.Bool+15; /*drill__cn_4*/
				mode_manualMode = __start.Bool+16; /*drill__cn_3*/
				mode_emptyProd = __start.Bool+12; /*drill__cn_7*/
				mode_unitProd = __start.Bool+13; /*drill__cn_6*/
				mode_batchProd = __start.Bool+14; /*drill__cn_5*/
			}
			__ret = drill__mode();
			if (__ret != 0) {
				return __ret; /*child execution failure*/
			}

			/*********************** functional execution ***********************/

			self_num++;
			if (function__num != self_num) {
				function__num = self_num;
				function_piece = __start.Bool+11; /*drill__cn_8*/
				function_emptyProd = __start.Bool+12; /*drill__cn_7*/
				function_unitProd = __start.Bool+13; /*drill__cn_6*/
				function_batchProd = __start.Bool+14; /*drill__cn_5*/
				function_acknowledgePB = __start.Bool+10; /*drill__cn_9*/
				function_autoMode = __start.Bool+15; /*drill__cn_4*/
				function_manualMode = __start.Bool+16; /*drill__cn_3*/
				function_faultyState = __start.Bool+0; /*drill__cn_19*/
				function_cycleEnd = __start.Bool+9; /*drill__cn_10*/
				function_loadingRequest = __start.Bool+17; /*drill__cn_2*/
				function_unloadingRequest = __start.Bool+18; /*drill__cn_1*/
			}
			__ret = drill__function();
			if (__ret != 0) {
				return __ret; /*child execution failure*/
			}

			/************************** load execution **************************/

			self_num++;
			if (piece__num != self_num) {
				piece__num = self_num;
				piece_loadingRequest = __start.Bool+17; /*drill__cn_2*/
				piece_unloadingRequest = __start.Bool+18; /*drill__cn_1*/
				piece_piece = __start.Bool+11; /*drill__cn_8*/
			}
			__ret = drill__piece();
			if (__ret != 0) {
				return __ret; /*child execution failure*/
			}

		}


		/******************** Post-conditions execution *********************/

		/*no Post-conditions*/
	}

	/*************************** self update ****************************/

	self.Bool = __start.Bool + drill__drill_offset__end.Bool;
	self.Int = __start.Int + drill__drill_offset__end.Int;
	self.Float = __start.Float + drill__drill_offset__end.Float;
	self.Char = __start.Char + drill__drill_offset__end.Char;

	return 0;
}

