/*2023-10-03T11:13:44-01:00*/

/********************************************************************
 * descent.c
 * 
 * generated by: plcgen 3.1.391
 ********************************************************************/

#include "cb_comp.h"
#include "iec_1131.h"

#include "descent.h"


/**************************** Variables *****************************/

CB_Index descent__num = 0;
CB_Mem_Bool *descent_acknowledgePB;
CB_Mem_Bool *descent_slowAscent;
CB_Mem_Bool *descent_fastAscent;
CB_Mem_Bool *descent_slowDescent;
CB_Mem_Bool *descent_fastDescent;
CB_Mem_Bool *descent_equipmentFault;
CB_Mem_Int *descent_motorFault;
CB_Mem_Bool *descent_forward;
CB_Mem_Bool *descent_backward;
CB_Mem_Bool *descent_highSpeed;
CB_Mem_Bool *descent_lowSpeed;
CB_Mem_Bool *descent__X_10;
CB_Mem_Bool *descent__X_11;
CB_Mem_Bool *descent__X_20;
CB_Mem_Bool *descent__X_21;
CB_Mem_Bool *descent__X_30;
CB_Mem_Bool *descent__X_31;
CB_Mem_Bool *descent__X_40;
CB_Mem_Bool *descent__X_41;
CB_Mem_Bool *descent_acknowledgePB_PREV;
CB_Mem_Int *descent_acknowledgePB_EDGE;
CB_Mem_Bool *descent__X_11_PREV;
CB_Mem_Bool *descent__X_21_PREV;
CB_Mem_Bool *descent__X_31_PREV;
CB_Mem_Bool *descent__X_41_PREV;

/**************************** Variables *****************************/

#define acknowledgePB (descent_acknowledgePB->CB_current_value)
#define slowAscent (descent_slowAscent->CB_current_value)
#define fastAscent (descent_fastAscent->CB_current_value)
#define slowDescent (descent_slowDescent->CB_current_value)
#define fastDescent (descent_fastDescent->CB_current_value)
#define equipmentFault (descent_equipmentFault->CB_current_value)
#define motorFault (descent_motorFault->CB_current_value)
#define forward (descent_forward->CB_current_value)
#define backward (descent_backward->CB_current_value)
#define highSpeed (descent_highSpeed->CB_current_value)
#define lowSpeed (descent_lowSpeed->CB_current_value)
#define _X_10 (descent__X_10->CB_current_value)
#define _X_11 (descent__X_11->CB_current_value)
#define _X_20 (descent__X_20->CB_current_value)
#define _X_21 (descent__X_21->CB_current_value)
#define _X_30 (descent__X_30->CB_current_value)
#define _X_31 (descent__X_31->CB_current_value)
#define _X_40 (descent__X_40->CB_current_value)
#define _X_41 (descent__X_41->CB_current_value)
#define acknowledgePB_PREV (descent_acknowledgePB_PREV->CB_current_value)
#define acknowledgePB_EDGE (descent_acknowledgePB_EDGE->CB_current_value)
#define _X_11_PREV (descent__X_11_PREV->CB_current_value)
#define _X_21_PREV (descent__X_21_PREV->CB_current_value)
#define _X_31_PREV (descent__X_31_PREV->CB_current_value)
#define _X_41_PREV (descent__X_41_PREV->CB_current_value)


/************************ Components offsets ************************/


/********************* Initialization function **********************/

int _drill__descent_init(void)
{
	(self.Bool+0)->CB_current_value = 1; /*_X_10*/
	(self.Bool+2)->CB_current_value = 1; /*_X_20*/
	(self.Bool+4)->CB_current_value = 1; /*_X_30*/
	(self.Bool+6)->CB_current_value = 1; /*_X_40*/
	self.Bool+=13;
	self.Int+=1;


	return 0;
}


/************************ Behavior function *************************/

int drill__descent(void)
{
	if (exec_term_node(self_num)) {

		/*********************** Internals variables ************************/

		descent__X_10 = self.Bool+0;
		descent__X_11 = self.Bool+1;
		descent__X_20 = self.Bool+2;
		descent__X_21 = self.Bool+3;
		descent__X_30 = self.Bool+4;
		descent__X_31 = self.Bool+5;
		descent__X_40 = self.Bool+6;
		descent__X_41 = self.Bool+7;
		descent_acknowledgePB_PREV = self.Bool+8;
		descent_acknowledgePB_EDGE = self.Int+0;
		descent__X_11_PREV = self.Bool+9;
		descent__X_21_PREV = self.Bool+10;
		descent__X_31_PREV = self.Bool+11;
		descent__X_41_PREV = self.Bool+12;

		/********************* Pre-conditions execution *********************/

		/*no Pre-conditions*/

		/************************ Behavior execution ************************/

		{
			unsigned char _Y_4;
			unsigned char _Y_3;
			unsigned char _Y_11;
			unsigned char _Y_10;
			unsigned char _Y_18;
			unsigned char _Y_17;
			unsigned char _Y_25;
			unsigned char _Y_24;
			acknowledgePB_EDGE = CB_edge_bool(acknowledgePB, acknowledgePB_PREV);
			/*pre-SFC*/
			if (acknowledgePB_EDGE > 0) {
				motorFault = 0;
			}
			if ((_X_21 || _X_41) && equipmentFault) {
				motorFault = 1;
			}
			if ((_X_31 || _X_11) && equipmentFault) {
				motorFault = 2;
			}
			if ((_X_21 || _X_11) && equipmentFault) {
				motorFault = 3;
			}
			if ((_X_41 || _X_31) && equipmentFault) {
				motorFault = 4;
			}
			/*transitions G1*/
			_Y_4 = _X_10 && (fastAscent && (motorFault == 0));
			_Y_3 = _X_11 && (!fastAscent || (motorFault > 0));
			/*transitions G2*/
			_Y_11 = _X_20 && (fastDescent && (motorFault == 0));
			_Y_10 = _X_21 && (!fastDescent || (motorFault > 0));
			/*transitions G3*/
			_Y_18 = _X_30 && (slowAscent && (motorFault == 0));
			_Y_17 = _X_31 && (!slowAscent || (motorFault > 0));
			/*transitions G4*/
			_Y_25 = _X_40 && (slowDescent && (motorFault == 0));
			_Y_24 = _X_41 && (!slowDescent || (motorFault > 0));
			/*evolutions G1*/
			if (_Y_4) {
				_X_10 = 0;
			}
			if (_Y_3) {
				_X_11 = 0;
			}
			if (_Y_4) {
				_X_11 = 1;
			}
			if (_Y_3) {
				_X_10 = 1;
			}
			/*timers G1*/
			/*actions G1*/
			if (CB_edge_bool(_X_11, _X_11_PREV) < 0) {
				backward = 0;
				highSpeed = 0;
			}
			if (_X_11) {
				backward = 1;
				highSpeed = 1;
			}
			/*evolutions G2*/
			if (_Y_11) {
				_X_20 = 0;
			}
			if (_Y_10) {
				_X_21 = 0;
			}
			if (_Y_11) {
				_X_21 = 1;
			}
			if (_Y_10) {
				_X_20 = 1;
			}
			/*timers G2*/
			/*actions G2*/
			if (CB_edge_bool(_X_21, _X_21_PREV) < 0) {
				forward = 0;
				highSpeed = 0;
			}
			if (_X_21) {
				forward = 1;
				highSpeed = 1;
			}
			/*evolutions G3*/
			if (_Y_18) {
				_X_30 = 0;
			}
			if (_Y_17) {
				_X_31 = 0;
			}
			if (_Y_18) {
				_X_31 = 1;
			}
			if (_Y_17) {
				_X_30 = 1;
			}
			/*timers G3*/
			/*actions G3*/
			if (CB_edge_bool(_X_31, _X_31_PREV) < 0) {
				backward = 0;
				lowSpeed = 0;
			}
			if (_X_31) {
				backward = 1;
				lowSpeed = 1;
			}
			/*evolutions G4*/
			if (_Y_25) {
				_X_40 = 0;
			}
			if (_Y_24) {
				_X_41 = 0;
			}
			if (_Y_25) {
				_X_41 = 1;
			}
			if (_Y_24) {
				_X_40 = 1;
			}
			/*timers G4*/
			/*actions G4*/
			if (CB_edge_bool(_X_41, _X_41_PREV) < 0) {
				forward = 0;
				lowSpeed = 0;
			}
			if (_X_41) {
				forward = 1;
				lowSpeed = 1;
			}
			/*post-SFC*/
			_X_31_PREV = _X_31;
			acknowledgePB_PREV = acknowledgePB;
			_X_41_PREV = _X_41;
			_X_11_PREV = _X_11;
			_X_21_PREV = _X_21;
		}

		CB_post_int(descent_motorFault);
		CB_post_bool(descent_forward);
		CB_post_bool(descent_backward);
		CB_post_bool(descent_highSpeed);
		CB_post_bool(descent_lowSpeed);

		/******************** Post-conditions execution *********************/

		/*no Post-conditions*/
	}

	/*************************** self update ****************************/

	self.Bool += 13;
	self.Int += 1;

	return 0;
}

