/*2023-10-03T11:13:44-01:00*/

/********************************************************************
 * descent.h
 * 
 * generated by: plcgen 3.1.391
 ********************************************************************/

#ifndef _DRILL__DESCENT_H
#define _DRILL__DESCENT_H


/********************** Variable declarations ***********************/

extern CB_Index descent__num;
extern CB_Mem_Bool *descent_acknowledgePB;
extern CB_Mem_Bool *descent_slowAscent;
extern CB_Mem_Bool *descent_fastAscent;
extern CB_Mem_Bool *descent_slowDescent;
extern CB_Mem_Bool *descent_fastDescent;
extern CB_Mem_Bool *descent_equipmentFault;
extern CB_Mem_Int *descent_motorFault;
extern CB_Mem_Bool *descent_forward;
extern CB_Mem_Bool *descent_backward;
extern CB_Mem_Bool *descent_highSpeed;
extern CB_Mem_Bool *descent_lowSpeed;

/********************** Function declarations ***********************/

extern int _drill__descent_init(void);
extern int drill__descent(void);

#endif /*_DRILL__DESCENT_H*/
