/*2023-10-03T11:13:52-01:00*/

/********************************************************************
 * door.h
 * 
 * generated by: plcgen 3.1.391
 ********************************************************************/

#ifndef _TNI_TRAIN__DOOR_H
#define _TNI_TRAIN__DOOR_H


/********************** Variable declarations ***********************/

extern CB_Index door__num;
extern CB_Mem_Float *door_compressedAir;
extern CB_Mem_Bool *door_cmdSupply;
extern CB_Mem_Bool *door_sensorSupply;
extern CB_Mem_Bool *door_enableOpening;
extern CB_Mem_Bool *door_enableClosing;
extern CB_Mem_Bool *door_closedDoorState;
extern CB_Mem_Bool *door_openedDoorState;
extern CB_Mem_Int *door_faultState;

/********************** Function declarations ***********************/

extern int _tni_train__door_init(void);
extern int tni_train__door(void);

#endif /*_TNI_TRAIN__DOOR_H*/
