/*2023-10-03T11:12:46-01:00*/

/********************************************************************
 * cb_ctd.h
 * 
 * generated by: plcgen 3.1.391
 ********************************************************************/

#ifndef _TIMERS_COUNTERS__CB_CTD_H
#define _TIMERS_COUNTERS__CB_CTD_H


/********************** Variable declarations ***********************/

extern CB_Index cb_ctd__num;
extern CB_Mem_Bool *cb_ctd_CD;
extern CB_Mem_Bool *cb_ctd_LOAD;
extern CB_Mem_Int *cb_ctd_PV;
extern CB_Mem_Bool *cb_ctd_QD;
extern CB_Mem_Int *cb_ctd_CV;

/********************** Function declarations ***********************/

extern int _timers_counters__cb_ctd_init(void);
extern int timers_counters__cb_ctd(void);

#endif /*_TIMERS_COUNTERS__CB_CTD_H*/
