/*2023-10-03T11:13:22-01:00*/

/********************************************************************
 * power_supply.c
 * 
 * generated by: plcgen 3.1.391
 ********************************************************************/

#include "cb_comp.h"
#include "iec_1131.h"

#include "power_supply.h"



/**************************** Variables *****************************/

CB_Index power_supply__num = 0;
CB_Mem_Bool *power_supply_inputEnergy;
CB_Mem_Bool *power_supply_outputEnergy;
CB_Mem_Bool *power_supply_d_electrical;
CB_Mem_Bool *power_supply_v_d_electrical;

/**************************** Variables *****************************/

#define inputEnergy (power_supply_inputEnergy->CB_current_value)
#define outputEnergy (power_supply_outputEnergy->CB_current_value)
#define d_electrical (power_supply_d_electrical->CB_current_value)
#define v_d_electrical (power_supply_v_d_electrical->CB_current_value)


/************************ Components offsets ************************/


/********************* Initialization function **********************/

int _equipment_library__power_supply_init(void)
{
	(power_supply_inputEnergy)->CB_current_value = 1; /*inputEnergy*/
	self.Bool+=2;


	return 0;
}


/************************ Behavior function *************************/

int equipment_library__power_supply(void)
{
	if (exec_term_node(self_num)) {

		/*********************** Internals variables ************************/

		power_supply_d_electrical = self.Bool+0;
		power_supply_v_d_electrical = self.Bool+1;

		/********************* Pre-conditions execution *********************/

		/*no Pre-conditions*/

		/************************ Behavior execution ************************/

		{
			/* ----------------------------------------------------------------	*/
			/* Type : Model of Operative Behaviour					*/
			/* Category :  Power								*/
			/* Author : Dassault Systemes						*/
			/* Update date : June 2018							*/
			/* ----------------------------------------------------------------	*/
			/* This module simulates a transformation of electrical energy.  	*/
			/* This simulates a power supply.						*/
			/* ----------------------------------------------------------------	*/

			if (d_electrical)
				outputEnergy = v_d_electrical;

			else		/* 	else it returns the input value 			*/
				outputEnergy = inputEnergy;
		}

		CB_post_bool(power_supply_outputEnergy);

		/******************** Post-conditions execution *********************/

		/*no Post-conditions*/
	}

	/*************************** self update ****************************/

	self.Bool += 2;

	return 0;
}

