/*2023-10-03T11:13:22-01:00*/

/********************************************************************
 * power_supply.h
 * 
 * generated by: plcgen 3.1.391
 ********************************************************************/

#ifndef _EQUIPMENT_LIBRARY__POWER_SUPPLY_H
#define _EQUIPMENT_LIBRARY__POWER_SUPPLY_H


/********************** Variable declarations ***********************/

extern CB_Index power_supply__num;
extern CB_Mem_Bool *power_supply_inputEnergy;
extern CB_Mem_Bool *power_supply_outputEnergy;
extern CB_Mem_Bool *power_supply_d_electrical;
extern CB_Mem_Bool *power_supply_v_d_electrical;

/********************** Function declarations ***********************/

extern int _equipment_library__power_supply_init(void);
extern int equipment_library__power_supply(void);

#endif /*_EQUIPMENT_LIBRARY__POWER_SUPPLY_H*/
