/*2023-10-03T11:13:22-01:00*/

/********************************************************************
 * switch_2pos_1output.h
 * 
 * generated by: plcgen 3.1.391
 ********************************************************************/

#ifndef _EQUIPMENT_LIBRARY__SWITCH_2POS_1OUTPUT_H
#define _EQUIPMENT_LIBRARY__SWITCH_2POS_1OUTPUT_H


/********************** Variable declarations ***********************/

extern CB_Index switch_2pos_1output__num;
extern CB_Mem_Bool *switch_2pos_1output_variable;
extern CB_Mem_Bool *switch_2pos_1output_leftPosition;
extern CB_Mem_Bool *switch_2pos_1output_rightPosition;

/********************** Function declarations ***********************/

extern int _equipment_library__switch_2pos_1output_init(void);
extern int equipment_library__switch_2pos_1output(void);

#endif /*_EQUIPMENT_LIBRARY__SWITCH_2POS_1OUTPUT_H*/
