/*2024-04-12T15:53:24-01:00*/

/********************************************************************
 * comp_new.c
 * 
 * generated by: plcgen 3.1.391
 ********************************************************************/

#include "cb_comp.h"
#include "iec_1131.h"

#include "comp_new.h"


/**************************** Variables *****************************/

CB_Index comp_new__num = 0;

/**************************** Variables *****************************/



/************************ Components offsets ************************/


/********************* Initialization function **********************/

int _apnew__comp_new_init(void)
{


	return 0;
}


/************************ Behavior function *************************/

int apnew__comp_new(void)
{
	if (exec_term_node(self_num)) {

		/*********************** Internals variables ************************/


		/********************* Pre-conditions execution *********************/

		/*no Pre-conditions*/

		/************************ Behavior execution ************************/

		{
		}


		/******************** Post-conditions execution *********************/

		/*no Post-conditions*/
	}

	/*************************** self update ****************************/


	return 0;
}

