/*2023-10-03T11:13:17-01:00*/

/********************************************************************
 * ramp_2dir_1speed.c
 * 
 * generated by: plcgen 3.1.391
 ********************************************************************/

#include "cb_comp.h"
#include "iec_1131.h"

#include "ramp_2dir_1speed.h"



/**************************** Variables *****************************/

CB_Index ramp_2dir_1speed__num = 0;
CB_Mem_Bool *ramp_2dir_1speed_fwdState;
CB_Mem_Bool *ramp_2dir_1speed_bwdState;
CB_Mem_Float *ramp_2dir_1speed_positionRamp;
CB_Mem_Float *ramp_2dir_1speed_percentRamp;
CB_Mem_Float *ramp_2dir_1speed_increment;
CB_Mem_Float *ramp_2dir_1speed_pBound;
CB_Mem_Float *ramp_2dir_1speed_maxRamp;
CB_Mem_Float *ramp_2dir_1speed_timeRamp;
CB_Mem_Bool *ramp_2dir_1speed_d_locking;
CB_Mem_Float *ramp_2dir_1speed_v_d_locking;

/**************************** Variables *****************************/

#define fwdState (ramp_2dir_1speed_fwdState->CB_current_value)
#define bwdState (ramp_2dir_1speed_bwdState->CB_current_value)
#define positionRamp (ramp_2dir_1speed_positionRamp->CB_current_value)
#define percentRamp (ramp_2dir_1speed_percentRamp->CB_current_value)
#define increment (ramp_2dir_1speed_increment->CB_current_value)
#define pBound (ramp_2dir_1speed_pBound->CB_current_value)
#define maxRamp (ramp_2dir_1speed_maxRamp->CB_current_value)
#define timeRamp (ramp_2dir_1speed_timeRamp->CB_current_value)
#define d_locking (ramp_2dir_1speed_d_locking->CB_current_value)
#define v_d_locking (ramp_2dir_1speed_v_d_locking->CB_current_value)


/************************ Components offsets ************************/


/********************* Initialization function **********************/

int _equipment_library__ramp_2dir_1speed_init(void)
{
	(self.Float+2)->CB_current_value = 1000.0; /*maxRamp*/
	(self.Float+3)->CB_current_value = 10.0; /*timeRamp*/
	self.Bool+=1;
	self.Float+=5;


	return 0;
}


/************************ Behavior function *************************/

int equipment_library__ramp_2dir_1speed(void)
{
	if (exec_term_node(self_num)) {

		/*********************** Internals variables ************************/

		ramp_2dir_1speed_increment = self.Float+0;
		ramp_2dir_1speed_pBound = self.Float+1;
		ramp_2dir_1speed_maxRamp = self.Float+2;
		ramp_2dir_1speed_timeRamp = self.Float+3;
		ramp_2dir_1speed_d_locking = self.Bool+0;
		ramp_2dir_1speed_v_d_locking = self.Float+4;

		/********************* Pre-conditions execution *********************/

		/*no Pre-conditions*/

		/************************ Behavior execution ************************/

		{
			/* ----------------------------------------------------------------	*/
			/* Type : Model of Operative Behaviour					*/
			/* Category :  Actuators							*/
			/* Author : Dassault Systemes						*/
			/* Update date : June 2018							*/
			/* ----------------------------------------------------------------	*/
			/* This module simulates the behaviour of a bounded ramp according	*/
			/* to the state of 2 boolean inputs (fwdState and bwdState).		*/
			/* ----------------------------------------------------------------	*/

			if (! d_locking)  {
				/* Compute the increment of translation according to the simulation clock	*/
				if (timeRamp > 0.0)
					increment=(maxRamp/timeRamp)*(CLOCK_PERIOD/1000000.0);

				/* Compute the target according to inputs		*/
				if (fwdState) pBound = maxRamp;
				if (bwdState) pBound = maxRamp * -1.0;
				if (! fwdState && ! bwdState) pBound = 0.0;

				/* Compute the value of the ramp	*/
				if ( positionRamp < pBound ) {
					positionRamp += increment;
					if (positionRamp > pBound) positionRamp = pBound;
				}
				if ( positionRamp > pBound ) {
					positionRamp -= increment;
					if (positionRamp < pBound) positionRamp = pBound;
				}
			}

			/* ----------------------------------------------------------------	*/
			/* Compute the percentage of the height of the ramp			*/
			/* ----------------------------------------------------------------	*/
			if (maxRamp > 0.0)
				percentRamp = ((positionRamp/maxRamp)*100);


		}

		CB_post_float(ramp_2dir_1speed_positionRamp);
		CB_post_float(ramp_2dir_1speed_percentRamp);

		/******************** Post-conditions execution *********************/

		/*no Post-conditions*/
	}

	/*************************** self update ****************************/

	self.Bool += 1;
	self.Float += 5;

	return 0;
}

