/*2023-10-03T11:13:47-01:00*/

/********************************************************************
 * lcd.h
 * 
 * generated by: plcgen 3.1.391
 ********************************************************************/

#ifndef _TNI_CLOCK__LCD_H
#define _TNI_CLOCK__LCD_H


/********************** Variable declarations ***********************/

extern CB_Index lcd__num;
extern CB_Mem_Int *lcd_displayValue;
extern CB_Mem_Char *lcd_displayString;
extern CB_Mem_Int *lcd_i;

/********************** Function declarations ***********************/

extern int _tni_clock__lcd_init(void);
extern int tni_clock__lcd(void);

#endif /*_TNI_CLOCK__LCD_H*/
